/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the LxcGetSnapshotResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LxcGetSnapshotResponseDataInner{}

// LxcGetSnapshotResponseDataInner struct for LxcGetSnapshotResponseDataInner
type LxcGetSnapshotResponseDataInner struct {

	// Snapshot description.
	Description string `json:"description"`

	// Snapshot identifier. Value 'current' identifies the current VM.
	Name string `json:"name"`

	// Parent snapshot identifier.
	Parent *string `json:"parent,omitempty"`

	// Snapshot creation time
	Snaptime *int64 `json:"snaptime,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _LxcGetSnapshotResponseDataInner LxcGetSnapshotResponseDataInner

// NewLxcGetSnapshotResponseDataInner instantiates a new LxcGetSnapshotResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLxcGetSnapshotResponseDataInner(description string, name string) *LxcGetSnapshotResponseDataInner {
	this := LxcGetSnapshotResponseDataInner{}
	this.Description = description
	this.Name = name
	return &this
}

// NewLxcGetSnapshotResponseDataInnerWithDefaults instantiates a new LxcGetSnapshotResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLxcGetSnapshotResponseDataInnerWithDefaults() *LxcGetSnapshotResponseDataInner {
	this := LxcGetSnapshotResponseDataInner{}





	return &this
}


// GetDescription returns the Description field value
func (o *LxcGetSnapshotResponseDataInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *LxcGetSnapshotResponseDataInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *LxcGetSnapshotResponseDataInner) SetDescription(v string) {
	o.Description = v
}


// GetName returns the Name field value
func (o *LxcGetSnapshotResponseDataInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LxcGetSnapshotResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LxcGetSnapshotResponseDataInner) SetName(v string) {
	o.Name = v
}


// GetParent returns the Parent field value if set, zero value otherwise.
func (o *LxcGetSnapshotResponseDataInner) GetParent() string {
	if o == nil || IsNil(o.Parent) {
		var ret string
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LxcGetSnapshotResponseDataInner) GetParentOk() (*string, bool) {
	if o == nil || IsNil(o.Parent) {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *LxcGetSnapshotResponseDataInner) HasParent() bool {
	if o != nil && !IsNil(o.Parent) {
		return true
	}

	return false
}

// SetParent gets a reference to the given string and assigns it to the Parent field.
func (o *LxcGetSnapshotResponseDataInner) SetParent(v string) {
	o.Parent = &v
}


// GetSnaptime returns the Snaptime field value if set, zero value otherwise.
func (o *LxcGetSnapshotResponseDataInner) GetSnaptime() int64 {
	if o == nil || IsNil(o.Snaptime) {
		var ret int64
		return ret
	}
	return *o.Snaptime
}

// GetSnaptimeOk returns a tuple with the Snaptime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LxcGetSnapshotResponseDataInner) GetSnaptimeOk() (*int64, bool) {
	if o == nil || IsNil(o.Snaptime) {
		return nil, false
	}
	return o.Snaptime, true
}

// HasSnaptime returns a boolean if a field has been set.
func (o *LxcGetSnapshotResponseDataInner) HasSnaptime() bool {
	if o != nil && !IsNil(o.Snaptime) {
		return true
	}

	return false
}

// SetSnaptime gets a reference to the given int64 and assigns it to the Snaptime field.
func (o *LxcGetSnapshotResponseDataInner) SetSnaptime(v int64) {
	o.Snaptime = &v
}


func (o LxcGetSnapshotResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LxcGetSnapshotResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["description"] = o.Description
	
	toSerialize["name"] = o.Name
	
	if !IsNil(o.Parent) {
		toSerialize["parent"] = o.Parent
	}
	
	if !IsNil(o.Snaptime) {
		toSerialize["snaptime"] = o.Snaptime
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LxcGetSnapshotResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLxcGetSnapshotResponseDataInner := _LxcGetSnapshotResponseDataInner{}

	err = json.Unmarshal(data, &varLxcGetSnapshotResponseDataInner)

	if err != nil {
		return err
	}

	*o = LxcGetSnapshotResponseDataInner(varLxcGetSnapshotResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "name")
		delete(additionalProperties, "parent")
		delete(additionalProperties, "snaptime")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLxcGetSnapshotResponseDataInner struct {
	value *LxcGetSnapshotResponseDataInner
	isSet bool
}

func (v NullableLxcGetSnapshotResponseDataInner) Get() *LxcGetSnapshotResponseDataInner {
	return v.value
}

func (v *NullableLxcGetSnapshotResponseDataInner) Set(val *LxcGetSnapshotResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLxcGetSnapshotResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLxcGetSnapshotResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLxcGetSnapshotResponseDataInner(val *LxcGetSnapshotResponseDataInner) *NullableLxcGetSnapshotResponseDataInner {
	return &NullableLxcGetSnapshotResponseDataInner{value: val, isSet: true}
}

func (v NullableLxcGetSnapshotResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLxcGetSnapshotResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


