/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
)

// PveEfitypeEnum the model 'PveEfitypeEnum'
type PveEfitypeEnum string

// List of PveEfitypeEnum
const (
	PVEEFITYPEENUM__2M PveEfitypeEnum = "2m"
	PVEEFITYPEENUM__4M PveEfitypeEnum = "4m"
)

// All allowed values of PveEfitypeEnum enum
var AllowedPveEfitypeEnumEnumValues = []PveEfitypeEnum{
	"2m",
	"4m",
}

func (v *PveEfitypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PveEfitypeEnum(value)
	for _, existing := range AllowedPveEfitypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PveEfitypeEnum", value)
}

// NewPveEfitypeEnumFromValue returns a pointer to a valid PveEfitypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPveEfitypeEnumFromValue(v string) (*PveEfitypeEnum, error) {
	ev := PveEfitypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PveEfitypeEnum: valid values are %v", v, AllowedPveEfitypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PveEfitypeEnum) IsValid() bool {
	for _, existing := range AllowedPveEfitypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PveEfitypeEnum value
func (v PveEfitypeEnum) Ptr() *PveEfitypeEnum {
	return &v
}

type NullablePveEfitypeEnum struct {
	value *PveEfitypeEnum
	isSet bool
}

func (v NullablePveEfitypeEnum) Get() *PveEfitypeEnum {
	return v.value
}

func (v *NullablePveEfitypeEnum) Set(val *PveEfitypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePveEfitypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePveEfitypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveEfitypeEnum(val *PveEfitypeEnum) *NullablePveEfitypeEnum {
	return &NullablePveEfitypeEnum{value: val, isSet: true}
}

func (v NullablePveEfitypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveEfitypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

