/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the StorageCreateStorageResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageCreateStorageResponseData{}

// StorageCreateStorageResponseData struct for StorageCreateStorageResponseData
type StorageCreateStorageResponseData struct {

	Config *StorageCreateStorageResponseDataConfig `json:"config,omitempty"`

	// The ID of the created storage.
	Storage string `json:"storage"`

	// The type of the created storage.
	Type PveNodesStorageTypeEnum `json:"type"`

	AdditionalProperties map[string]interface{}
}

type _StorageCreateStorageResponseData StorageCreateStorageResponseData

// NewStorageCreateStorageResponseData instantiates a new StorageCreateStorageResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageCreateStorageResponseData(storage string, type_ PveNodesStorageTypeEnum) *StorageCreateStorageResponseData {
	this := StorageCreateStorageResponseData{}
	this.Storage = storage
	this.Type = type_
	return &this
}

// NewStorageCreateStorageResponseDataWithDefaults instantiates a new StorageCreateStorageResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageCreateStorageResponseDataWithDefaults() *StorageCreateStorageResponseData {
	this := StorageCreateStorageResponseData{}




	return &this
}


// GetConfig returns the Config field value if set, zero value otherwise.
func (o *StorageCreateStorageResponseData) GetConfig() StorageCreateStorageResponseDataConfig {
	if o == nil || IsNil(o.Config) {
		var ret StorageCreateStorageResponseDataConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageCreateStorageResponseData) GetConfigOk() (*StorageCreateStorageResponseDataConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *StorageCreateStorageResponseData) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given StorageCreateStorageResponseDataConfig and assigns it to the Config field.
func (o *StorageCreateStorageResponseData) SetConfig(v StorageCreateStorageResponseDataConfig) {
	o.Config = &v
}


// GetStorage returns the Storage field value
func (o *StorageCreateStorageResponseData) GetStorage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value
// and a boolean to check if the value has been set.
func (o *StorageCreateStorageResponseData) GetStorageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Storage, true
}

// SetStorage sets field value
func (o *StorageCreateStorageResponseData) SetStorage(v string) {
	o.Storage = v
}


// GetType returns the Type field value
func (o *StorageCreateStorageResponseData) GetType() PveNodesStorageTypeEnum {
	if o == nil {
		var ret PveNodesStorageTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StorageCreateStorageResponseData) GetTypeOk() (*PveNodesStorageTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StorageCreateStorageResponseData) SetType(v PveNodesStorageTypeEnum) {
	o.Type = v
}


func (o StorageCreateStorageResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageCreateStorageResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	
	toSerialize["storage"] = o.Storage
	
	toSerialize["type"] = o.Type
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StorageCreateStorageResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"storage",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStorageCreateStorageResponseData := _StorageCreateStorageResponseData{}

	err = json.Unmarshal(data, &varStorageCreateStorageResponseData)

	if err != nil {
		return err
	}

	*o = StorageCreateStorageResponseData(varStorageCreateStorageResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "config")
		delete(additionalProperties, "storage")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStorageCreateStorageResponseData struct {
	value *StorageCreateStorageResponseData
	isSet bool
}

func (v NullableStorageCreateStorageResponseData) Get() *StorageCreateStorageResponseData {
	return v.value
}

func (v *NullableStorageCreateStorageResponseData) Set(val *StorageCreateStorageResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageCreateStorageResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageCreateStorageResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageCreateStorageResponseData(val *StorageCreateStorageResponseData) *NullableStorageCreateStorageResponseData {
	return &NullableStorageCreateStorageResponseData{value: val, isSet: true}
}

func (v NullableStorageCreateStorageResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageCreateStorageResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


