/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterBackupGetBackupResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterBackupGetBackupResponseDataInner{}

// ClusterBackupGetBackupResponseDataInner struct for ClusterBackupGetBackupResponseDataInner
type ClusterBackupGetBackupResponseDataInner struct {

	// The job ID.
	Id string `json:"id" validate:"regexp=\\\\S+"`

	AdditionalProperties map[string]interface{}
}

type _ClusterBackupGetBackupResponseDataInner ClusterBackupGetBackupResponseDataInner

// NewClusterBackupGetBackupResponseDataInner instantiates a new ClusterBackupGetBackupResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterBackupGetBackupResponseDataInner(id string) *ClusterBackupGetBackupResponseDataInner {
	this := ClusterBackupGetBackupResponseDataInner{}
	this.Id = id
	return &this
}

// NewClusterBackupGetBackupResponseDataInnerWithDefaults instantiates a new ClusterBackupGetBackupResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterBackupGetBackupResponseDataInnerWithDefaults() *ClusterBackupGetBackupResponseDataInner {
	this := ClusterBackupGetBackupResponseDataInner{}


	return &this
}


// GetId returns the Id field value
func (o *ClusterBackupGetBackupResponseDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ClusterBackupGetBackupResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ClusterBackupGetBackupResponseDataInner) SetId(v string) {
	o.Id = v
}


func (o ClusterBackupGetBackupResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterBackupGetBackupResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["id"] = o.Id
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterBackupGetBackupResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterBackupGetBackupResponseDataInner := _ClusterBackupGetBackupResponseDataInner{}

	err = json.Unmarshal(data, &varClusterBackupGetBackupResponseDataInner)

	if err != nil {
		return err
	}

	*o = ClusterBackupGetBackupResponseDataInner(varClusterBackupGetBackupResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterBackupGetBackupResponseDataInner struct {
	value *ClusterBackupGetBackupResponseDataInner
	isSet bool
}

func (v NullableClusterBackupGetBackupResponseDataInner) Get() *ClusterBackupGetBackupResponseDataInner {
	return v.value
}

func (v *NullableClusterBackupGetBackupResponseDataInner) Set(val *ClusterBackupGetBackupResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterBackupGetBackupResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterBackupGetBackupResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterBackupGetBackupResponseDataInner(val *ClusterBackupGetBackupResponseDataInner) *NullableClusterBackupGetBackupResponseDataInner {
	return &NullableClusterBackupGetBackupResponseDataInner{value: val, isSet: true}
}

func (v NullableClusterBackupGetBackupResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterBackupGetBackupResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


