/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterSdnGetDnsResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterSdnGetDnsResponseDataInner{}

// ClusterSdnGetDnsResponseDataInner struct for ClusterSdnGetDnsResponseDataInner
type ClusterSdnGetDnsResponseDataInner struct {

	Dns string `json:"dns"`

	Type string `json:"type"`

	AdditionalProperties map[string]interface{}
}

type _ClusterSdnGetDnsResponseDataInner ClusterSdnGetDnsResponseDataInner

// NewClusterSdnGetDnsResponseDataInner instantiates a new ClusterSdnGetDnsResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterSdnGetDnsResponseDataInner(dns string, type_ string) *ClusterSdnGetDnsResponseDataInner {
	this := ClusterSdnGetDnsResponseDataInner{}
	this.Dns = dns
	this.Type = type_
	return &this
}

// NewClusterSdnGetDnsResponseDataInnerWithDefaults instantiates a new ClusterSdnGetDnsResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterSdnGetDnsResponseDataInnerWithDefaults() *ClusterSdnGetDnsResponseDataInner {
	this := ClusterSdnGetDnsResponseDataInner{}



	return &this
}


// GetDns returns the Dns field value
func (o *ClusterSdnGetDnsResponseDataInner) GetDns() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dns
}

// GetDnsOk returns a tuple with the Dns field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnGetDnsResponseDataInner) GetDnsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dns, true
}

// SetDns sets field value
func (o *ClusterSdnGetDnsResponseDataInner) SetDns(v string) {
	o.Dns = v
}


// GetType returns the Type field value
func (o *ClusterSdnGetDnsResponseDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnGetDnsResponseDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ClusterSdnGetDnsResponseDataInner) SetType(v string) {
	o.Type = v
}


func (o ClusterSdnGetDnsResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterSdnGetDnsResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["dns"] = o.Dns
	
	toSerialize["type"] = o.Type
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterSdnGetDnsResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dns",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterSdnGetDnsResponseDataInner := _ClusterSdnGetDnsResponseDataInner{}

	err = json.Unmarshal(data, &varClusterSdnGetDnsResponseDataInner)

	if err != nil {
		return err
	}

	*o = ClusterSdnGetDnsResponseDataInner(varClusterSdnGetDnsResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dns")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterSdnGetDnsResponseDataInner struct {
	value *ClusterSdnGetDnsResponseDataInner
	isSet bool
}

func (v NullableClusterSdnGetDnsResponseDataInner) Get() *ClusterSdnGetDnsResponseDataInner {
	return v.value
}

func (v *NullableClusterSdnGetDnsResponseDataInner) Set(val *ClusterSdnGetDnsResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterSdnGetDnsResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterSdnGetDnsResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterSdnGetDnsResponseDataInner(val *ClusterSdnGetDnsResponseDataInner) *NullableClusterSdnGetDnsResponseDataInner {
	return &NullableClusterSdnGetDnsResponseDataInner{value: val, isSet: true}
}

func (v NullableClusterSdnGetDnsResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterSdnGetDnsResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


