/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterHaMigrateResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterHaMigrateResponseData{}

// ClusterHaMigrateResponseData struct for ClusterHaMigrateResponseData
type ClusterHaMigrateResponseData struct {

	// HA resources, which are blocking the given HA resource from being migrated to the requested target node.
	BlockingResources []ClusterHaMigrateResponseDataBlockingResourcesInner `json:"blocking-resources,omitempty"`

	// HA resources, which are migrated to the same requested target node as the given HA resource, because these are in positive affinity with the HA resource.
	ComigratedResources []interface{} `json:"comigrated-resources,omitempty"`

	// Node, which was requested to be migrated to.
	RequestedNode string `json:"requested-node"`

	// HA resource, which is requested to be migrated.
	Sid string `json:"sid"`

	AdditionalProperties map[string]interface{}
}

type _ClusterHaMigrateResponseData ClusterHaMigrateResponseData

// NewClusterHaMigrateResponseData instantiates a new ClusterHaMigrateResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterHaMigrateResponseData(requestedNode string, sid string) *ClusterHaMigrateResponseData {
	this := ClusterHaMigrateResponseData{}
	this.RequestedNode = requestedNode
	this.Sid = sid
	return &this
}

// NewClusterHaMigrateResponseDataWithDefaults instantiates a new ClusterHaMigrateResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterHaMigrateResponseDataWithDefaults() *ClusterHaMigrateResponseData {
	this := ClusterHaMigrateResponseData{}





	return &this
}


// GetBlockingResources returns the BlockingResources field value if set, zero value otherwise.
func (o *ClusterHaMigrateResponseData) GetBlockingResources() []ClusterHaMigrateResponseDataBlockingResourcesInner {
	if o == nil || IsNil(o.BlockingResources) {
		var ret []ClusterHaMigrateResponseDataBlockingResourcesInner
		return ret
	}
	return o.BlockingResources
}

// GetBlockingResourcesOk returns a tuple with the BlockingResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterHaMigrateResponseData) GetBlockingResourcesOk() ([]ClusterHaMigrateResponseDataBlockingResourcesInner, bool) {
	if o == nil || IsNil(o.BlockingResources) {
		return nil, false
	}
	return o.BlockingResources, true
}

// HasBlockingResources returns a boolean if a field has been set.
func (o *ClusterHaMigrateResponseData) HasBlockingResources() bool {
	if o != nil && !IsNil(o.BlockingResources) {
		return true
	}

	return false
}

// SetBlockingResources gets a reference to the given []ClusterHaMigrateResponseDataBlockingResourcesInner and assigns it to the BlockingResources field.
func (o *ClusterHaMigrateResponseData) SetBlockingResources(v []ClusterHaMigrateResponseDataBlockingResourcesInner) {
	o.BlockingResources = v
}


// GetComigratedResources returns the ComigratedResources field value if set, zero value otherwise.
func (o *ClusterHaMigrateResponseData) GetComigratedResources() []interface{} {
	if o == nil || IsNil(o.ComigratedResources) {
		var ret []interface{}
		return ret
	}
	return o.ComigratedResources
}

// GetComigratedResourcesOk returns a tuple with the ComigratedResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterHaMigrateResponseData) GetComigratedResourcesOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.ComigratedResources) {
		return nil, false
	}
	return o.ComigratedResources, true
}

// HasComigratedResources returns a boolean if a field has been set.
func (o *ClusterHaMigrateResponseData) HasComigratedResources() bool {
	if o != nil && !IsNil(o.ComigratedResources) {
		return true
	}

	return false
}

// SetComigratedResources gets a reference to the given []interface{} and assigns it to the ComigratedResources field.
func (o *ClusterHaMigrateResponseData) SetComigratedResources(v []interface{}) {
	o.ComigratedResources = v
}


// GetRequestedNode returns the RequestedNode field value
func (o *ClusterHaMigrateResponseData) GetRequestedNode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestedNode
}

// GetRequestedNodeOk returns a tuple with the RequestedNode field value
// and a boolean to check if the value has been set.
func (o *ClusterHaMigrateResponseData) GetRequestedNodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestedNode, true
}

// SetRequestedNode sets field value
func (o *ClusterHaMigrateResponseData) SetRequestedNode(v string) {
	o.RequestedNode = v
}


// GetSid returns the Sid field value
func (o *ClusterHaMigrateResponseData) GetSid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sid
}

// GetSidOk returns a tuple with the Sid field value
// and a boolean to check if the value has been set.
func (o *ClusterHaMigrateResponseData) GetSidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sid, true
}

// SetSid sets field value
func (o *ClusterHaMigrateResponseData) SetSid(v string) {
	o.Sid = v
}


func (o ClusterHaMigrateResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterHaMigrateResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.BlockingResources) {
		toSerialize["blocking-resources"] = o.BlockingResources
	}
	
	if !IsNil(o.ComigratedResources) {
		toSerialize["comigrated-resources"] = o.ComigratedResources
	}
	
	toSerialize["requested-node"] = o.RequestedNode
	
	toSerialize["sid"] = o.Sid
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterHaMigrateResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requested-node",
		"sid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterHaMigrateResponseData := _ClusterHaMigrateResponseData{}

	err = json.Unmarshal(data, &varClusterHaMigrateResponseData)

	if err != nil {
		return err
	}

	*o = ClusterHaMigrateResponseData(varClusterHaMigrateResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "blocking-resources")
		delete(additionalProperties, "comigrated-resources")
		delete(additionalProperties, "requested-node")
		delete(additionalProperties, "sid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterHaMigrateResponseData struct {
	value *ClusterHaMigrateResponseData
	isSet bool
}

func (v NullableClusterHaMigrateResponseData) Get() *ClusterHaMigrateResponseData {
	return v.value
}

func (v *NullableClusterHaMigrateResponseData) Set(val *ClusterHaMigrateResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterHaMigrateResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterHaMigrateResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterHaMigrateResponseData(val *ClusterHaMigrateResponseData) *NullableClusterHaMigrateResponseData {
	return &NullableClusterHaMigrateResponseData{value: val, isSet: true}
}

func (v NullableClusterHaMigrateResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterHaMigrateResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


