/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner{}

// ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner struct for ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner
type ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner struct {

	// Configuration key of the volume.
	Id string `json:"id"`

	// Whether the volume is included in the backup or not.
	Included PveBoolean `json:"included"`

	// Name of the volume.
	Name string `json:"name"`

	// The reason why the volume is included (or excluded).
	Reason string `json:"reason"`

	AdditionalProperties map[string]interface{}
}

type _ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner

// NewClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner instantiates a new ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner(id string, included PveBoolean, name string, reason string) *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner {
	this := ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner{}
	this.Id = id
	this.Included = included
	this.Name = name
	this.Reason = reason
	return &this
}

// NewClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInnerWithDefaults instantiates a new ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInnerWithDefaults() *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner {
	this := ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner{}





	return &this
}


// GetId returns the Id field value
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) SetId(v string) {
	o.Id = v
}


// GetIncluded returns the Included field value
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) GetIncluded() PveBoolean {
	if o == nil {
		var ret PveBoolean
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) GetIncludedOk() (*PveBoolean, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Included, true
}

// SetIncluded sets field value
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) SetIncluded(v PveBoolean) {
	o.Included = v
}


// GetName returns the Name field value
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) SetName(v string) {
	o.Name = v
}


// GetReason returns the Reason field value
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) SetReason(v string) {
	o.Reason = v
}


func (o ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["id"] = o.Id
	
	toSerialize["included"] = o.Included
	
	toSerialize["name"] = o.Name
	
	toSerialize["reason"] = o.Reason
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"included",
		"name",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner := _ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner{}

	err = json.Unmarshal(data, &varClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner)

	if err != nil {
		return err
	}

	*o = ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner(varClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "included")
		delete(additionalProperties, "name")
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner struct {
	value *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner
	isSet bool
}

func (v NullableClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) Get() *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner {
	return v.value
}

func (v *NullableClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) Set(val *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner(val *ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) *NullableClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner {
	return &NullableClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner{value: val, isSet: true}
}

func (v NullableClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


