/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesScanLvmthinscanResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesScanLvmthinscanResponseDataInner{}

// NodesScanLvmthinscanResponseDataInner struct for NodesScanLvmthinscanResponseDataInner
type NodesScanLvmthinscanResponseDataInner struct {

	// The LVM Thin Pool name (LVM logical volume).
	Lv string `json:"lv"`

	AdditionalProperties map[string]interface{}
}

type _NodesScanLvmthinscanResponseDataInner NodesScanLvmthinscanResponseDataInner

// NewNodesScanLvmthinscanResponseDataInner instantiates a new NodesScanLvmthinscanResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesScanLvmthinscanResponseDataInner(lv string) *NodesScanLvmthinscanResponseDataInner {
	this := NodesScanLvmthinscanResponseDataInner{}
	this.Lv = lv
	return &this
}

// NewNodesScanLvmthinscanResponseDataInnerWithDefaults instantiates a new NodesScanLvmthinscanResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesScanLvmthinscanResponseDataInnerWithDefaults() *NodesScanLvmthinscanResponseDataInner {
	this := NodesScanLvmthinscanResponseDataInner{}


	return &this
}


// GetLv returns the Lv field value
func (o *NodesScanLvmthinscanResponseDataInner) GetLv() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lv
}

// GetLvOk returns a tuple with the Lv field value
// and a boolean to check if the value has been set.
func (o *NodesScanLvmthinscanResponseDataInner) GetLvOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lv, true
}

// SetLv sets field value
func (o *NodesScanLvmthinscanResponseDataInner) SetLv(v string) {
	o.Lv = v
}


func (o NodesScanLvmthinscanResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesScanLvmthinscanResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["lv"] = o.Lv
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesScanLvmthinscanResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lv",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesScanLvmthinscanResponseDataInner := _NodesScanLvmthinscanResponseDataInner{}

	err = json.Unmarshal(data, &varNodesScanLvmthinscanResponseDataInner)

	if err != nil {
		return err
	}

	*o = NodesScanLvmthinscanResponseDataInner(varNodesScanLvmthinscanResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "lv")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesScanLvmthinscanResponseDataInner struct {
	value *NodesScanLvmthinscanResponseDataInner
	isSet bool
}

func (v NullableNodesScanLvmthinscanResponseDataInner) Get() *NodesScanLvmthinscanResponseDataInner {
	return v.value
}

func (v *NullableNodesScanLvmthinscanResponseDataInner) Set(val *NodesScanLvmthinscanResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesScanLvmthinscanResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesScanLvmthinscanResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesScanLvmthinscanResponseDataInner(val *NodesScanLvmthinscanResponseDataInner) *NullableNodesScanLvmthinscanResponseDataInner {
	return &NullableNodesScanLvmthinscanResponseDataInner{value: val, isSet: true}
}

func (v NullableNodesScanLvmthinscanResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesScanLvmthinscanResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


