/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterBackupGetVolumeBackupIncludedResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterBackupGetVolumeBackupIncludedResponseData{}

// ClusterBackupGetVolumeBackupIncludedResponseData struct for ClusterBackupGetVolumeBackupIncludedResponseData
type ClusterBackupGetVolumeBackupIncludedResponseData struct {

	Children []ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInner `json:"children"`

	AdditionalProperties map[string]interface{}
}

type _ClusterBackupGetVolumeBackupIncludedResponseData ClusterBackupGetVolumeBackupIncludedResponseData

// NewClusterBackupGetVolumeBackupIncludedResponseData instantiates a new ClusterBackupGetVolumeBackupIncludedResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterBackupGetVolumeBackupIncludedResponseData(children []ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInner) *ClusterBackupGetVolumeBackupIncludedResponseData {
	this := ClusterBackupGetVolumeBackupIncludedResponseData{}
	this.Children = children
	return &this
}

// NewClusterBackupGetVolumeBackupIncludedResponseDataWithDefaults instantiates a new ClusterBackupGetVolumeBackupIncludedResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterBackupGetVolumeBackupIncludedResponseDataWithDefaults() *ClusterBackupGetVolumeBackupIncludedResponseData {
	this := ClusterBackupGetVolumeBackupIncludedResponseData{}


	return &this
}


// GetChildren returns the Children field value
func (o *ClusterBackupGetVolumeBackupIncludedResponseData) GetChildren() []ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInner {
	if o == nil {
		var ret []ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInner
		return ret
	}

	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value
// and a boolean to check if the value has been set.
func (o *ClusterBackupGetVolumeBackupIncludedResponseData) GetChildrenOk() ([]ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Children, true
}

// SetChildren sets field value
func (o *ClusterBackupGetVolumeBackupIncludedResponseData) SetChildren(v []ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInner) {
	o.Children = v
}


func (o ClusterBackupGetVolumeBackupIncludedResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterBackupGetVolumeBackupIncludedResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["children"] = o.Children
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterBackupGetVolumeBackupIncludedResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"children",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterBackupGetVolumeBackupIncludedResponseData := _ClusterBackupGetVolumeBackupIncludedResponseData{}

	err = json.Unmarshal(data, &varClusterBackupGetVolumeBackupIncludedResponseData)

	if err != nil {
		return err
	}

	*o = ClusterBackupGetVolumeBackupIncludedResponseData(varClusterBackupGetVolumeBackupIncludedResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "children")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterBackupGetVolumeBackupIncludedResponseData struct {
	value *ClusterBackupGetVolumeBackupIncludedResponseData
	isSet bool
}

func (v NullableClusterBackupGetVolumeBackupIncludedResponseData) Get() *ClusterBackupGetVolumeBackupIncludedResponseData {
	return v.value
}

func (v *NullableClusterBackupGetVolumeBackupIncludedResponseData) Set(val *ClusterBackupGetVolumeBackupIncludedResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterBackupGetVolumeBackupIncludedResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterBackupGetVolumeBackupIncludedResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterBackupGetVolumeBackupIncludedResponseData(val *ClusterBackupGetVolumeBackupIncludedResponseData) *NullableClusterBackupGetVolumeBackupIncludedResponseData {
	return &NullableClusterBackupGetVolumeBackupIncludedResponseData{value: val, isSet: true}
}

func (v NullableClusterBackupGetVolumeBackupIncludedResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterBackupGetVolumeBackupIncludedResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


