/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PveIvshmemField - struct for PveIvshmemField
type PveIvshmemField struct {
	PveIvshmemConfig *PveIvshmemConfig
	String *string
}

// PveIvshmemConfigAsPveIvshmemField is a convenience function that returns PveIvshmemConfig wrapped in PveIvshmemField
func PveIvshmemConfigAsPveIvshmemField(v *PveIvshmemConfig) PveIvshmemField {
	return PveIvshmemField{
		PveIvshmemConfig: v,
	}
}

// stringAsPveIvshmemField is a convenience function that returns string wrapped in PveIvshmemField
func StringAsPveIvshmemField(v *string) PveIvshmemField {
	return PveIvshmemField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PveIvshmemField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PveIvshmemConfig
	err = newStrictDecoder(data).Decode(&dst.PveIvshmemConfig)
	if err == nil {
		jsonPveIvshmemConfig, _ := json.Marshal(dst.PveIvshmemConfig)
		if string(jsonPveIvshmemConfig) == "{}" { // empty struct
			dst.PveIvshmemConfig = nil
		} else {
			if err = validator.Validate(dst.PveIvshmemConfig); err != nil {
				dst.PveIvshmemConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PveIvshmemConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PveIvshmemConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PveIvshmemField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PveIvshmemField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PveIvshmemField) MarshalJSON() ([]byte, error) {
	if src.PveIvshmemConfig != nil {
		return json.Marshal(&src.PveIvshmemConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PveIvshmemField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PveIvshmemConfig != nil {
		return obj.PveIvshmemConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PveIvshmemField) GetActualInstanceValue() (interface{}) {
	if obj.PveIvshmemConfig != nil {
		return *obj.PveIvshmemConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePveIvshmemField struct {
	value *PveIvshmemField
	isSet bool
}

func (v NullablePveIvshmemField) Get() *PveIvshmemField {
	return v.value
}

func (v *NullablePveIvshmemField) Set(val *PveIvshmemField) {
	v.value = val
	v.isSet = true
}

func (v NullablePveIvshmemField) IsSet() bool {
	return v.isSet
}

func (v *NullablePveIvshmemField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveIvshmemField(val *PveIvshmemField) *NullablePveIvshmemField {
	return &NullablePveIvshmemField{value: val, isSet: true}
}

func (v NullablePveIvshmemField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveIvshmemField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


