/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterCephMetadataResponseDataMdsValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterCephMetadataResponseDataMdsValue{}

// ClusterCephMetadataResponseDataMdsValue struct for ClusterCephMetadataResponseDataMdsValue
type ClusterCephMetadataResponseDataMdsValue struct {

	// Bind addresses and ports.
	Addr *string `json:"addr,omitempty"`

	// Ceph release codename currently used.
	CephRelease string `json:"ceph_release"`

	// Version info currently used by the service.
	CephVersion string `json:"ceph_version"`

	// Short version (numerical) info currently used by the service.
	CephVersionShort string `json:"ceph_version_short"`

	// Hostname on which the service is running.
	Hostname string `json:"hostname"`

	// Memory of the service currently in swap.
	MemSwapKb int64 `json:"mem_swap_kb"`

	// Memory consumption of the service.
	MemTotalKb int64 `json:"mem_total_kb"`

	// Name of the service instance.
	Name *string `json:"name,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _ClusterCephMetadataResponseDataMdsValue ClusterCephMetadataResponseDataMdsValue

// NewClusterCephMetadataResponseDataMdsValue instantiates a new ClusterCephMetadataResponseDataMdsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterCephMetadataResponseDataMdsValue(cephRelease string, cephVersion string, cephVersionShort string, hostname string, memSwapKb int64, memTotalKb int64) *ClusterCephMetadataResponseDataMdsValue {
	this := ClusterCephMetadataResponseDataMdsValue{}
	this.CephRelease = cephRelease
	this.CephVersion = cephVersion
	this.CephVersionShort = cephVersionShort
	this.Hostname = hostname
	this.MemSwapKb = memSwapKb
	this.MemTotalKb = memTotalKb
	return &this
}

// NewClusterCephMetadataResponseDataMdsValueWithDefaults instantiates a new ClusterCephMetadataResponseDataMdsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterCephMetadataResponseDataMdsValueWithDefaults() *ClusterCephMetadataResponseDataMdsValue {
	this := ClusterCephMetadataResponseDataMdsValue{}









	return &this
}


// GetAddr returns the Addr field value if set, zero value otherwise.
func (o *ClusterCephMetadataResponseDataMdsValue) GetAddr() string {
	if o == nil || IsNil(o.Addr) {
		var ret string
		return ret
	}
	return *o.Addr
}

// GetAddrOk returns a tuple with the Addr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterCephMetadataResponseDataMdsValue) GetAddrOk() (*string, bool) {
	if o == nil || IsNil(o.Addr) {
		return nil, false
	}
	return o.Addr, true
}

// HasAddr returns a boolean if a field has been set.
func (o *ClusterCephMetadataResponseDataMdsValue) HasAddr() bool {
	if o != nil && !IsNil(o.Addr) {
		return true
	}

	return false
}

// SetAddr gets a reference to the given string and assigns it to the Addr field.
func (o *ClusterCephMetadataResponseDataMdsValue) SetAddr(v string) {
	o.Addr = &v
}


// GetCephRelease returns the CephRelease field value
func (o *ClusterCephMetadataResponseDataMdsValue) GetCephRelease() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CephRelease
}

// GetCephReleaseOk returns a tuple with the CephRelease field value
// and a boolean to check if the value has been set.
func (o *ClusterCephMetadataResponseDataMdsValue) GetCephReleaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CephRelease, true
}

// SetCephRelease sets field value
func (o *ClusterCephMetadataResponseDataMdsValue) SetCephRelease(v string) {
	o.CephRelease = v
}


// GetCephVersion returns the CephVersion field value
func (o *ClusterCephMetadataResponseDataMdsValue) GetCephVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CephVersion
}

// GetCephVersionOk returns a tuple with the CephVersion field value
// and a boolean to check if the value has been set.
func (o *ClusterCephMetadataResponseDataMdsValue) GetCephVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CephVersion, true
}

// SetCephVersion sets field value
func (o *ClusterCephMetadataResponseDataMdsValue) SetCephVersion(v string) {
	o.CephVersion = v
}


// GetCephVersionShort returns the CephVersionShort field value
func (o *ClusterCephMetadataResponseDataMdsValue) GetCephVersionShort() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CephVersionShort
}

// GetCephVersionShortOk returns a tuple with the CephVersionShort field value
// and a boolean to check if the value has been set.
func (o *ClusterCephMetadataResponseDataMdsValue) GetCephVersionShortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CephVersionShort, true
}

// SetCephVersionShort sets field value
func (o *ClusterCephMetadataResponseDataMdsValue) SetCephVersionShort(v string) {
	o.CephVersionShort = v
}


// GetHostname returns the Hostname field value
func (o *ClusterCephMetadataResponseDataMdsValue) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *ClusterCephMetadataResponseDataMdsValue) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *ClusterCephMetadataResponseDataMdsValue) SetHostname(v string) {
	o.Hostname = v
}


// GetMemSwapKb returns the MemSwapKb field value
func (o *ClusterCephMetadataResponseDataMdsValue) GetMemSwapKb() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MemSwapKb
}

// GetMemSwapKbOk returns a tuple with the MemSwapKb field value
// and a boolean to check if the value has been set.
func (o *ClusterCephMetadataResponseDataMdsValue) GetMemSwapKbOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemSwapKb, true
}

// SetMemSwapKb sets field value
func (o *ClusterCephMetadataResponseDataMdsValue) SetMemSwapKb(v int64) {
	o.MemSwapKb = v
}


// GetMemTotalKb returns the MemTotalKb field value
func (o *ClusterCephMetadataResponseDataMdsValue) GetMemTotalKb() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MemTotalKb
}

// GetMemTotalKbOk returns a tuple with the MemTotalKb field value
// and a boolean to check if the value has been set.
func (o *ClusterCephMetadataResponseDataMdsValue) GetMemTotalKbOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemTotalKb, true
}

// SetMemTotalKb sets field value
func (o *ClusterCephMetadataResponseDataMdsValue) SetMemTotalKb(v int64) {
	o.MemTotalKb = v
}


// GetName returns the Name field value if set, zero value otherwise.
func (o *ClusterCephMetadataResponseDataMdsValue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterCephMetadataResponseDataMdsValue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClusterCephMetadataResponseDataMdsValue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClusterCephMetadataResponseDataMdsValue) SetName(v string) {
	o.Name = &v
}


func (o ClusterCephMetadataResponseDataMdsValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterCephMetadataResponseDataMdsValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Addr) {
		toSerialize["addr"] = o.Addr
	}
	
	toSerialize["ceph_release"] = o.CephRelease
	
	toSerialize["ceph_version"] = o.CephVersion
	
	toSerialize["ceph_version_short"] = o.CephVersionShort
	
	toSerialize["hostname"] = o.Hostname
	
	toSerialize["mem_swap_kb"] = o.MemSwapKb
	
	toSerialize["mem_total_kb"] = o.MemTotalKb
	
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterCephMetadataResponseDataMdsValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ceph_release",
		"ceph_version",
		"ceph_version_short",
		"hostname",
		"mem_swap_kb",
		"mem_total_kb",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterCephMetadataResponseDataMdsValue := _ClusterCephMetadataResponseDataMdsValue{}

	err = json.Unmarshal(data, &varClusterCephMetadataResponseDataMdsValue)

	if err != nil {
		return err
	}

	*o = ClusterCephMetadataResponseDataMdsValue(varClusterCephMetadataResponseDataMdsValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "addr")
		delete(additionalProperties, "ceph_release")
		delete(additionalProperties, "ceph_version")
		delete(additionalProperties, "ceph_version_short")
		delete(additionalProperties, "hostname")
		delete(additionalProperties, "mem_swap_kb")
		delete(additionalProperties, "mem_total_kb")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterCephMetadataResponseDataMdsValue struct {
	value *ClusterCephMetadataResponseDataMdsValue
	isSet bool
}

func (v NullableClusterCephMetadataResponseDataMdsValue) Get() *ClusterCephMetadataResponseDataMdsValue {
	return v.value
}

func (v *NullableClusterCephMetadataResponseDataMdsValue) Set(val *ClusterCephMetadataResponseDataMdsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterCephMetadataResponseDataMdsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterCephMetadataResponseDataMdsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterCephMetadataResponseDataMdsValue(val *ClusterCephMetadataResponseDataMdsValue) *NullableClusterCephMetadataResponseDataMdsValue {
	return &NullableClusterCephMetadataResponseDataMdsValue{value: val, isSet: true}
}

func (v NullableClusterCephMetadataResponseDataMdsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterCephMetadataResponseDataMdsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


