/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
)

// PveModeEnum the model 'PveModeEnum'
type PveModeEnum string

// List of PveModeEnum
const (
	PVEMODEENUM_LDAP PveModeEnum = "ldap"
	PVEMODEENUM_LDAPS PveModeEnum = "ldaps"
	PVEMODEENUM_LDAPSTARTTLS PveModeEnum = "ldap+starttls"
)

// All allowed values of PveModeEnum enum
var AllowedPveModeEnumEnumValues = []PveModeEnum{
	"ldap",
	"ldaps",
	"ldap+starttls",
}

func (v *PveModeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PveModeEnum(value)
	for _, existing := range AllowedPveModeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PveModeEnum", value)
}

// NewPveModeEnumFromValue returns a pointer to a valid PveModeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPveModeEnumFromValue(v string) (*PveModeEnum, error) {
	ev := PveModeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PveModeEnum: valid values are %v", v, AllowedPveModeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PveModeEnum) IsValid() bool {
	for _, existing := range AllowedPveModeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PveModeEnum value
func (v PveModeEnum) Ptr() *PveModeEnum {
	return &v
}

type NullablePveModeEnum struct {
	value *PveModeEnum
	isSet bool
}

func (v NullablePveModeEnum) Get() *PveModeEnum {
	return v.value
}

func (v *NullablePveModeEnum) Set(val *PveModeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePveModeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePveModeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveModeEnum(val *PveModeEnum) *NullablePveModeEnum {
	return &NullablePveModeEnum{value: val, isSet: true}
}

func (v NullablePveModeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveModeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

