/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PveClusterOptionsLanguageEnum the model 'PveClusterOptionsLanguageEnum'
type PveClusterOptionsLanguageEnum string

// List of PveClusterOptionsLanguageEnum
const (
	PVECLUSTEROPTIONSLANGUAGEENUM_AR PveClusterOptionsLanguageEnum = "ar"
	PVECLUSTEROPTIONSLANGUAGEENUM_CA PveClusterOptionsLanguageEnum = "ca"
	PVECLUSTEROPTIONSLANGUAGEENUM_DA PveClusterOptionsLanguageEnum = "da"
	PVECLUSTEROPTIONSLANGUAGEENUM_DE PveClusterOptionsLanguageEnum = "de"
	PVECLUSTEROPTIONSLANGUAGEENUM_EN PveClusterOptionsLanguageEnum = "en"
	PVECLUSTEROPTIONSLANGUAGEENUM_ES PveClusterOptionsLanguageEnum = "es"
	PVECLUSTEROPTIONSLANGUAGEENUM_EU PveClusterOptionsLanguageEnum = "eu"
	PVECLUSTEROPTIONSLANGUAGEENUM_FA PveClusterOptionsLanguageEnum = "fa"
	PVECLUSTEROPTIONSLANGUAGEENUM_FR PveClusterOptionsLanguageEnum = "fr"
	PVECLUSTEROPTIONSLANGUAGEENUM_HR PveClusterOptionsLanguageEnum = "hr"
	PVECLUSTEROPTIONSLANGUAGEENUM_HE PveClusterOptionsLanguageEnum = "he"
	PVECLUSTEROPTIONSLANGUAGEENUM_IT PveClusterOptionsLanguageEnum = "it"
	PVECLUSTEROPTIONSLANGUAGEENUM_JA PveClusterOptionsLanguageEnum = "ja"
	PVECLUSTEROPTIONSLANGUAGEENUM_KA PveClusterOptionsLanguageEnum = "ka"
	PVECLUSTEROPTIONSLANGUAGEENUM_KR PveClusterOptionsLanguageEnum = "kr"
	PVECLUSTEROPTIONSLANGUAGEENUM_NB PveClusterOptionsLanguageEnum = "nb"
	PVECLUSTEROPTIONSLANGUAGEENUM_NL PveClusterOptionsLanguageEnum = "nl"
	PVECLUSTEROPTIONSLANGUAGEENUM_NN PveClusterOptionsLanguageEnum = "nn"
	PVECLUSTEROPTIONSLANGUAGEENUM_PL PveClusterOptionsLanguageEnum = "pl"
	PVECLUSTEROPTIONSLANGUAGEENUM_PT_BR PveClusterOptionsLanguageEnum = "pt_BR"
	PVECLUSTEROPTIONSLANGUAGEENUM_RU PveClusterOptionsLanguageEnum = "ru"
	PVECLUSTEROPTIONSLANGUAGEENUM_SL PveClusterOptionsLanguageEnum = "sl"
	PVECLUSTEROPTIONSLANGUAGEENUM_SV PveClusterOptionsLanguageEnum = "sv"
	PVECLUSTEROPTIONSLANGUAGEENUM_TR PveClusterOptionsLanguageEnum = "tr"
	PVECLUSTEROPTIONSLANGUAGEENUM_UKR PveClusterOptionsLanguageEnum = "ukr"
	PVECLUSTEROPTIONSLANGUAGEENUM_ZH_CN PveClusterOptionsLanguageEnum = "zh_CN"
	PVECLUSTEROPTIONSLANGUAGEENUM_ZH_TW PveClusterOptionsLanguageEnum = "zh_TW"
)

// All allowed values of PveClusterOptionsLanguageEnum enum
var AllowedPveClusterOptionsLanguageEnumEnumValues = []PveClusterOptionsLanguageEnum{
	"ar",
	"ca",
	"da",
	"de",
	"en",
	"es",
	"eu",
	"fa",
	"fr",
	"hr",
	"he",
	"it",
	"ja",
	"ka",
	"kr",
	"nb",
	"nl",
	"nn",
	"pl",
	"pt_BR",
	"ru",
	"sl",
	"sv",
	"tr",
	"ukr",
	"zh_CN",
	"zh_TW",
}

func (v *PveClusterOptionsLanguageEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PveClusterOptionsLanguageEnum(value)
	for _, existing := range AllowedPveClusterOptionsLanguageEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PveClusterOptionsLanguageEnum", value)
}

// NewPveClusterOptionsLanguageEnumFromValue returns a pointer to a valid PveClusterOptionsLanguageEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPveClusterOptionsLanguageEnumFromValue(v string) (*PveClusterOptionsLanguageEnum, error) {
	ev := PveClusterOptionsLanguageEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PveClusterOptionsLanguageEnum: valid values are %v", v, AllowedPveClusterOptionsLanguageEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PveClusterOptionsLanguageEnum) IsValid() bool {
	for _, existing := range AllowedPveClusterOptionsLanguageEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PveClusterOptionsLanguageEnum value
func (v PveClusterOptionsLanguageEnum) Ptr() *PveClusterOptionsLanguageEnum {
	return &v
}

type NullablePveClusterOptionsLanguageEnum struct {
	value *PveClusterOptionsLanguageEnum
	isSet bool
}

func (v NullablePveClusterOptionsLanguageEnum) Get() *PveClusterOptionsLanguageEnum {
	return v.value
}

func (v *NullablePveClusterOptionsLanguageEnum) Set(val *PveClusterOptionsLanguageEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePveClusterOptionsLanguageEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePveClusterOptionsLanguageEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveClusterOptionsLanguageEnum(val *PveClusterOptionsLanguageEnum) *NullablePveClusterOptionsLanguageEnum {
	return &NullablePveClusterOptionsLanguageEnum{value: val, isSet: true}
}

func (v NullablePveClusterOptionsLanguageEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveClusterOptionsLanguageEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

