/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
)

// PvePoolsTypeEnum the model 'PvePoolsTypeEnum'
type PvePoolsTypeEnum string

// List of PvePoolsTypeEnum
const (
	PVEPOOLSTYPEENUM_QEMU PvePoolsTypeEnum = "qemu"
	PVEPOOLSTYPEENUM_LXC PvePoolsTypeEnum = "lxc"
	PVEPOOLSTYPEENUM_STORAGE PvePoolsTypeEnum = "storage"
)

// All allowed values of PvePoolsTypeEnum enum
var AllowedPvePoolsTypeEnumEnumValues = []PvePoolsTypeEnum{
	"qemu",
	"lxc",
	"storage",
}

func (v *PvePoolsTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PvePoolsTypeEnum(value)
	for _, existing := range AllowedPvePoolsTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PvePoolsTypeEnum", value)
}

// NewPvePoolsTypeEnumFromValue returns a pointer to a valid PvePoolsTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPvePoolsTypeEnumFromValue(v string) (*PvePoolsTypeEnum, error) {
	ev := PvePoolsTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PvePoolsTypeEnum: valid values are %v", v, AllowedPvePoolsTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PvePoolsTypeEnum) IsValid() bool {
	for _, existing := range AllowedPvePoolsTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PvePoolsTypeEnum value
func (v PvePoolsTypeEnum) Ptr() *PvePoolsTypeEnum {
	return &v
}

type NullablePvePoolsTypeEnum struct {
	value *PvePoolsTypeEnum
	isSet bool
}

func (v NullablePvePoolsTypeEnum) Get() *PvePoolsTypeEnum {
	return v.value
}

func (v *NullablePvePoolsTypeEnum) Set(val *PvePoolsTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePvePoolsTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePvePoolsTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePvePoolsTypeEnum(val *PvePoolsTypeEnum) *NullablePvePoolsTypeEnum {
	return &NullablePvePoolsTypeEnum{value: val, isSet: true}
}

func (v NullablePvePoolsTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePvePoolsTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

