/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PveDevField - struct for PveDevField
type PveDevField struct {
	PveDevConfig *PveDevConfig
	String *string
}

// PveDevConfigAsPveDevField is a convenience function that returns PveDevConfig wrapped in PveDevField
func PveDevConfigAsPveDevField(v *PveDevConfig) PveDevField {
	return PveDevField{
		PveDevConfig: v,
	}
}

// stringAsPveDevField is a convenience function that returns string wrapped in PveDevField
func StringAsPveDevField(v *string) PveDevField {
	return PveDevField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PveDevField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PveDevConfig
	err = newStrictDecoder(data).Decode(&dst.PveDevConfig)
	if err == nil {
		jsonPveDevConfig, _ := json.Marshal(dst.PveDevConfig)
		if string(jsonPveDevConfig) == "{}" { // empty struct
			dst.PveDevConfig = nil
		} else {
			if err = validator.Validate(dst.PveDevConfig); err != nil {
				dst.PveDevConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PveDevConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PveDevConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PveDevField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PveDevField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PveDevField) MarshalJSON() ([]byte, error) {
	if src.PveDevConfig != nil {
		return json.Marshal(&src.PveDevConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PveDevField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PveDevConfig != nil {
		return obj.PveDevConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PveDevField) GetActualInstanceValue() (interface{}) {
	if obj.PveDevConfig != nil {
		return *obj.PveDevConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePveDevField struct {
	value *PveDevField
	isSet bool
}

func (v NullablePveDevField) Get() *PveDevField {
	return v.value
}

func (v *NullablePveDevField) Set(val *PveDevField) {
	v.value = val
	v.isSet = true
}

func (v NullablePveDevField) IsSet() bool {
	return v.isSet
}

func (v *NullablePveDevField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveDevField(val *PveDevField) *NullablePveDevField {
	return &NullablePveDevField{value: val, isSet: true}
}

func (v NullablePveDevField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveDevField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


