/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PveAgentConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PveAgentConfig{}

// PveAgentConfig struct for PveAgentConfig
type PveAgentConfig struct {

	// Enable/disable communication with a QEMU Guest Agent (QGA) running in the VM.
	Enabled PveBoolean `json:"enabled"`

	// Freeze/thaw guest filesystems on backup for consistency.
	FreezeFsOnBackup *PveBoolean `json:"freeze-fs-on-backup,omitempty"`

	// Run fstrim after moving a disk or migrating the VM.
	FstrimClonedDisks *PveBoolean `json:"fstrim_cloned_disks,omitempty"`

	// Select the agent type
	Type *PveQemuTypeEnum `json:"type,omitempty"`

}

type _PveAgentConfig PveAgentConfig

// NewPveAgentConfig instantiates a new PveAgentConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPveAgentConfig(enabled PveBoolean) *PveAgentConfig {
	this := PveAgentConfig{}
	this.Enabled = enabled
	var freezeFsOnBackup PveBoolean = PVEBOOLEAN__1
	this.FreezeFsOnBackup = &freezeFsOnBackup
	var fstrimClonedDisks PveBoolean = PVEBOOLEAN__0
	this.FstrimClonedDisks = &fstrimClonedDisks
	var type_ PveQemuTypeEnum = PVEQEMUTYPEENUM_VIRTIO
	this.Type = &type_
	return &this
}

// NewPveAgentConfigWithDefaults instantiates a new PveAgentConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPveAgentConfigWithDefaults() *PveAgentConfig {
	this := PveAgentConfig{}

	var enabled PveBoolean = PVEBOOLEAN__0
	this.Enabled = enabled

	var freezeFsOnBackup PveBoolean = PVEBOOLEAN__1
	this.FreezeFsOnBackup = &freezeFsOnBackup

	var fstrimClonedDisks PveBoolean = PVEBOOLEAN__0
	this.FstrimClonedDisks = &fstrimClonedDisks

	var type_ PveQemuTypeEnum = PVEQEMUTYPEENUM_VIRTIO
	this.Type = &type_

	return &this
}


// GetEnabled returns the Enabled field value
func (o *PveAgentConfig) GetEnabled() PveBoolean {
	if o == nil {
		var ret PveBoolean
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *PveAgentConfig) GetEnabledOk() (*PveBoolean, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *PveAgentConfig) SetEnabled(v PveBoolean) {
	o.Enabled = v
}


// GetFreezeFsOnBackup returns the FreezeFsOnBackup field value if set, zero value otherwise.
func (o *PveAgentConfig) GetFreezeFsOnBackup() PveBoolean {
	if o == nil || IsNil(o.FreezeFsOnBackup) {
		var ret PveBoolean
		return ret
	}
	return *o.FreezeFsOnBackup
}

// GetFreezeFsOnBackupOk returns a tuple with the FreezeFsOnBackup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveAgentConfig) GetFreezeFsOnBackupOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.FreezeFsOnBackup) {
		return nil, false
	}
	return o.FreezeFsOnBackup, true
}

// HasFreezeFsOnBackup returns a boolean if a field has been set.
func (o *PveAgentConfig) HasFreezeFsOnBackup() bool {
	if o != nil && !IsNil(o.FreezeFsOnBackup) {
		return true
	}

	return false
}

// SetFreezeFsOnBackup gets a reference to the given PveBoolean and assigns it to the FreezeFsOnBackup field.
func (o *PveAgentConfig) SetFreezeFsOnBackup(v PveBoolean) {
	o.FreezeFsOnBackup = &v
}


// GetFstrimClonedDisks returns the FstrimClonedDisks field value if set, zero value otherwise.
func (o *PveAgentConfig) GetFstrimClonedDisks() PveBoolean {
	if o == nil || IsNil(o.FstrimClonedDisks) {
		var ret PveBoolean
		return ret
	}
	return *o.FstrimClonedDisks
}

// GetFstrimClonedDisksOk returns a tuple with the FstrimClonedDisks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveAgentConfig) GetFstrimClonedDisksOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.FstrimClonedDisks) {
		return nil, false
	}
	return o.FstrimClonedDisks, true
}

// HasFstrimClonedDisks returns a boolean if a field has been set.
func (o *PveAgentConfig) HasFstrimClonedDisks() bool {
	if o != nil && !IsNil(o.FstrimClonedDisks) {
		return true
	}

	return false
}

// SetFstrimClonedDisks gets a reference to the given PveBoolean and assigns it to the FstrimClonedDisks field.
func (o *PveAgentConfig) SetFstrimClonedDisks(v PveBoolean) {
	o.FstrimClonedDisks = &v
}


// GetType returns the Type field value if set, zero value otherwise.
func (o *PveAgentConfig) GetType() PveQemuTypeEnum {
	if o == nil || IsNil(o.Type) {
		var ret PveQemuTypeEnum
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveAgentConfig) GetTypeOk() (*PveQemuTypeEnum, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PveAgentConfig) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given PveQemuTypeEnum and assigns it to the Type field.
func (o *PveAgentConfig) SetType(v PveQemuTypeEnum) {
	o.Type = &v
}


func (o PveAgentConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PveAgentConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["enabled"] = o.Enabled
	
	if !IsNil(o.FreezeFsOnBackup) {
		toSerialize["freeze-fs-on-backup"] = o.FreezeFsOnBackup
	}
	
	if !IsNil(o.FstrimClonedDisks) {
		toSerialize["fstrim_cloned_disks"] = o.FstrimClonedDisks
	}
	
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	
	return toSerialize, nil
}

func (o *PveAgentConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPveAgentConfig := _PveAgentConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPveAgentConfig)

	if err != nil {
		return err
	}

	*o = PveAgentConfig(varPveAgentConfig)

	return err
}

type NullablePveAgentConfig struct {
	value *PveAgentConfig
	isSet bool
}

func (v NullablePveAgentConfig) Get() *PveAgentConfig {
	return v.value
}

func (v *NullablePveAgentConfig) Set(val *PveAgentConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePveAgentConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePveAgentConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveAgentConfig(val *PveAgentConfig) *NullablePveAgentConfig {
	return &NullablePveAgentConfig{value: val, isSet: true}
}

func (v NullablePveAgentConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveAgentConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


// pveShorthandValue converts a value into the unquoted form expected
// by Proxmox's `key=value,…` CLI shorthand. Uses encoding/json (already
// imported) to avoid pulling in fmt in models that don't otherwise need
// it, then strips the surrounding quotes for strings.
func PveAgentConfig_pveShorthandValue(v interface{}) string {
	if v == nil {
		return ""
	}
	b, err := json.Marshal(v)
	if err != nil {
		return ""
	}
	s := string(b)
	if n := len(s); n >= 2 && s[0] == '"' && s[n-1] == '"' {
		return s[1 : n-1]
	}
	return s
}

// ToShorthand serialises the PveAgentConfig into Proxmox's CLI-style
// shorthand string (`key=value,…`). The property marked
// `x-pve-default-key` is emitted positionally without a `key=` prefix;
// aliases collapse multiple property names to the same wire key.
//
// Example: {Model: "virtio", Bridge: "vmbr0", Firewall: 1}
//       => "virtio,bridge=vmbr0,firewall=1"
func (o *PveAgentConfig) ToShorthand() string {
	if o == nil {
		return ""
	}
	var result string
	sep := ""
	
	result += sep + PveAgentConfig_pveShorthandValue(o.Enabled)
	sep = ","
	
	
	if o.FreezeFsOnBackup != nil {
		result += sep + "freeze-fs-on-backup=" + PveAgentConfig_pveShorthandValue(*o.FreezeFsOnBackup)
		sep = ","
	}
	
	if o.FstrimClonedDisks != nil {
		result += sep + "fstrim_cloned_disks=" + PveAgentConfig_pveShorthandValue(*o.FstrimClonedDisks)
		sep = ","
	}
	
	if o.Type != nil {
		result += sep + "type=" + PveAgentConfig_pveShorthandValue(*o.Type)
		sep = ","
	}
	
	return result
}

