/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PveEfidiskField - struct for PveEfidiskField
type PveEfidiskField struct {
	PveEfidiskConfig *PveEfidiskConfig
	String *string
}

// PveEfidiskConfigAsPveEfidiskField is a convenience function that returns PveEfidiskConfig wrapped in PveEfidiskField
func PveEfidiskConfigAsPveEfidiskField(v *PveEfidiskConfig) PveEfidiskField {
	return PveEfidiskField{
		PveEfidiskConfig: v,
	}
}

// stringAsPveEfidiskField is a convenience function that returns string wrapped in PveEfidiskField
func StringAsPveEfidiskField(v *string) PveEfidiskField {
	return PveEfidiskField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PveEfidiskField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PveEfidiskConfig
	err = newStrictDecoder(data).Decode(&dst.PveEfidiskConfig)
	if err == nil {
		jsonPveEfidiskConfig, _ := json.Marshal(dst.PveEfidiskConfig)
		if string(jsonPveEfidiskConfig) == "{}" { // empty struct
			dst.PveEfidiskConfig = nil
		} else {
			if err = validator.Validate(dst.PveEfidiskConfig); err != nil {
				dst.PveEfidiskConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PveEfidiskConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PveEfidiskConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PveEfidiskField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PveEfidiskField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PveEfidiskField) MarshalJSON() ([]byte, error) {
	if src.PveEfidiskConfig != nil {
		return json.Marshal(&src.PveEfidiskConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PveEfidiskField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PveEfidiskConfig != nil {
		return obj.PveEfidiskConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PveEfidiskField) GetActualInstanceValue() (interface{}) {
	if obj.PveEfidiskConfig != nil {
		return *obj.PveEfidiskConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePveEfidiskField struct {
	value *PveEfidiskField
	isSet bool
}

func (v NullablePveEfidiskField) Get() *PveEfidiskField {
	return v.value
}

func (v *NullablePveEfidiskField) Set(val *PveEfidiskField) {
	v.value = val
	v.isSet = true
}

func (v NullablePveEfidiskField) IsSet() bool {
	return v.isSet
}

func (v *NullablePveEfidiskField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveEfidiskField(val *PveEfidiskField) *NullablePveEfidiskField {
	return &NullablePveEfidiskField{value: val, isSet: true}
}

func (v NullablePveEfidiskField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveEfidiskField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


