/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterConfigNodesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterConfigNodesResponse{}

// ClusterConfigNodesResponse struct for ClusterConfigNodesResponse
type ClusterConfigNodesResponse struct {

	Data []ClusterConfigNodesResponseDataInner `json:"data"`

	// Optional total count, present for paginated list responses.
	Total *int32 `json:"total,omitempty"`

	// Optional change summary returned by some PUT operations (one entry per modified field).
	Changes map[string]interface{} `json:"changes,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _ClusterConfigNodesResponse ClusterConfigNodesResponse

// NewClusterConfigNodesResponse instantiates a new ClusterConfigNodesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterConfigNodesResponse(data []ClusterConfigNodesResponseDataInner) *ClusterConfigNodesResponse {
	this := ClusterConfigNodesResponse{}
	this.Data = data
	return &this
}

// NewClusterConfigNodesResponseWithDefaults instantiates a new ClusterConfigNodesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterConfigNodesResponseWithDefaults() *ClusterConfigNodesResponse {
	this := ClusterConfigNodesResponse{}




	return &this
}


// GetData returns the Data field value
func (o *ClusterConfigNodesResponse) GetData() []ClusterConfigNodesResponseDataInner {
	if o == nil {
		var ret []ClusterConfigNodesResponseDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ClusterConfigNodesResponse) GetDataOk() ([]ClusterConfigNodesResponseDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ClusterConfigNodesResponse) SetData(v []ClusterConfigNodesResponseDataInner) {
	o.Data = v
}


// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ClusterConfigNodesResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterConfigNodesResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ClusterConfigNodesResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ClusterConfigNodesResponse) SetTotal(v int32) {
	o.Total = &v
}


// GetChanges returns the Changes field value if set, zero value otherwise.
func (o *ClusterConfigNodesResponse) GetChanges() map[string]interface{} {
	if o == nil || IsNil(o.Changes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Changes
}

// GetChangesOk returns a tuple with the Changes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterConfigNodesResponse) GetChangesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Changes) {
		return map[string]interface{}{}, false
	}
	return o.Changes, true
}

// HasChanges returns a boolean if a field has been set.
func (o *ClusterConfigNodesResponse) HasChanges() bool {
	if o != nil && !IsNil(o.Changes) {
		return true
	}

	return false
}

// SetChanges gets a reference to the given map[string]interface{} and assigns it to the Changes field.
func (o *ClusterConfigNodesResponse) SetChanges(v map[string]interface{}) {
	o.Changes = v
}


func (o ClusterConfigNodesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterConfigNodesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["data"] = o.Data
	
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	
	if !IsNil(o.Changes) {
		toSerialize["changes"] = o.Changes
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterConfigNodesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterConfigNodesResponse := _ClusterConfigNodesResponse{}

	err = json.Unmarshal(data, &varClusterConfigNodesResponse)

	if err != nil {
		return err
	}

	*o = ClusterConfigNodesResponse(varClusterConfigNodesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "total")
		delete(additionalProperties, "changes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterConfigNodesResponse struct {
	value *ClusterConfigNodesResponse
	isSet bool
}

func (v NullableClusterConfigNodesResponse) Get() *ClusterConfigNodesResponse {
	return v.value
}

func (v *NullableClusterConfigNodesResponse) Set(val *ClusterConfigNodesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterConfigNodesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterConfigNodesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterConfigNodesResponse(val *ClusterConfigNodesResponse) *NullableClusterConfigNodesResponse {
	return &NullableClusterConfigNodesResponse{value: val, isSet: true}
}

func (v NullableClusterConfigNodesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterConfigNodesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


