/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClusterSdnAddNodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterSdnAddNodeRequest{}

// ClusterSdnAddNodeRequest struct for ClusterSdnAddNodeRequest
type ClusterSdnAddNodeRequest struct {

	// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`

	Interfaces []interface{} `json:"interfaces"`

	// IPv4 address for this node
	Ip *string `json:"ip,omitempty" validate:"regexp=^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"`

	// IPv6 address for this node
	Ip6 *string `json:"ip6,omitempty" validate:"regexp=^(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}$"`

	// the token for unlocking the global SDN configuration
	LockToken *string `json:"lock-token,omitempty"`

	// Identifier for nodes in an SDN fabric
	NodeId string `json:"node_id" validate:"regexp=^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\\\-]*[a-zA-Z0-9])?)$"`

	// Type of configuration entry in an SDN Fabric section config
	Protocol PveProtocolEnum `json:"protocol"`

}

type _ClusterSdnAddNodeRequest ClusterSdnAddNodeRequest

// NewClusterSdnAddNodeRequest instantiates a new ClusterSdnAddNodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterSdnAddNodeRequest(interfaces []interface{}, nodeId string, protocol PveProtocolEnum) *ClusterSdnAddNodeRequest {
	this := ClusterSdnAddNodeRequest{}
	this.Interfaces = interfaces
	this.NodeId = nodeId
	this.Protocol = protocol
	return &this
}

// NewClusterSdnAddNodeRequestWithDefaults instantiates a new ClusterSdnAddNodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterSdnAddNodeRequestWithDefaults() *ClusterSdnAddNodeRequest {
	this := ClusterSdnAddNodeRequest{}








	return &this
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ClusterSdnAddNodeRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnAddNodeRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ClusterSdnAddNodeRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ClusterSdnAddNodeRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetInterfaces returns the Interfaces field value
func (o *ClusterSdnAddNodeRequest) GetInterfaces() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Interfaces
}

// GetInterfacesOk returns a tuple with the Interfaces field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnAddNodeRequest) GetInterfacesOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Interfaces, true
}

// SetInterfaces sets field value
func (o *ClusterSdnAddNodeRequest) SetInterfaces(v []interface{}) {
	o.Interfaces = v
}


// GetIp returns the Ip field value if set, zero value otherwise.
func (o *ClusterSdnAddNodeRequest) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnAddNodeRequest) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *ClusterSdnAddNodeRequest) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *ClusterSdnAddNodeRequest) SetIp(v string) {
	o.Ip = &v
}


// GetIp6 returns the Ip6 field value if set, zero value otherwise.
func (o *ClusterSdnAddNodeRequest) GetIp6() string {
	if o == nil || IsNil(o.Ip6) {
		var ret string
		return ret
	}
	return *o.Ip6
}

// GetIp6Ok returns a tuple with the Ip6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnAddNodeRequest) GetIp6Ok() (*string, bool) {
	if o == nil || IsNil(o.Ip6) {
		return nil, false
	}
	return o.Ip6, true
}

// HasIp6 returns a boolean if a field has been set.
func (o *ClusterSdnAddNodeRequest) HasIp6() bool {
	if o != nil && !IsNil(o.Ip6) {
		return true
	}

	return false
}

// SetIp6 gets a reference to the given string and assigns it to the Ip6 field.
func (o *ClusterSdnAddNodeRequest) SetIp6(v string) {
	o.Ip6 = &v
}


// GetLockToken returns the LockToken field value if set, zero value otherwise.
func (o *ClusterSdnAddNodeRequest) GetLockToken() string {
	if o == nil || IsNil(o.LockToken) {
		var ret string
		return ret
	}
	return *o.LockToken
}

// GetLockTokenOk returns a tuple with the LockToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnAddNodeRequest) GetLockTokenOk() (*string, bool) {
	if o == nil || IsNil(o.LockToken) {
		return nil, false
	}
	return o.LockToken, true
}

// HasLockToken returns a boolean if a field has been set.
func (o *ClusterSdnAddNodeRequest) HasLockToken() bool {
	if o != nil && !IsNil(o.LockToken) {
		return true
	}

	return false
}

// SetLockToken gets a reference to the given string and assigns it to the LockToken field.
func (o *ClusterSdnAddNodeRequest) SetLockToken(v string) {
	o.LockToken = &v
}


// GetNodeId returns the NodeId field value
func (o *ClusterSdnAddNodeRequest) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnAddNodeRequest) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *ClusterSdnAddNodeRequest) SetNodeId(v string) {
	o.NodeId = v
}


// GetProtocol returns the Protocol field value
func (o *ClusterSdnAddNodeRequest) GetProtocol() PveProtocolEnum {
	if o == nil {
		var ret PveProtocolEnum
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnAddNodeRequest) GetProtocolOk() (*PveProtocolEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *ClusterSdnAddNodeRequest) SetProtocol(v PveProtocolEnum) {
	o.Protocol = v
}


func (o ClusterSdnAddNodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterSdnAddNodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	toSerialize["interfaces"] = o.Interfaces
	
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	
	if !IsNil(o.Ip6) {
		toSerialize["ip6"] = o.Ip6
	}
	
	if !IsNil(o.LockToken) {
		toSerialize["lock-token"] = o.LockToken
	}
	
	toSerialize["node_id"] = o.NodeId
	
	toSerialize["protocol"] = o.Protocol
	
	return toSerialize, nil
}

func (o *ClusterSdnAddNodeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"interfaces",
		"node_id",
		"protocol",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterSdnAddNodeRequest := _ClusterSdnAddNodeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterSdnAddNodeRequest)

	if err != nil {
		return err
	}

	*o = ClusterSdnAddNodeRequest(varClusterSdnAddNodeRequest)

	return err
}

type NullableClusterSdnAddNodeRequest struct {
	value *ClusterSdnAddNodeRequest
	isSet bool
}

func (v NullableClusterSdnAddNodeRequest) Get() *ClusterSdnAddNodeRequest {
	return v.value
}

func (v *NullableClusterSdnAddNodeRequest) Set(val *ClusterSdnAddNodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterSdnAddNodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterSdnAddNodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterSdnAddNodeRequest(val *ClusterSdnAddNodeRequest) *NullableClusterSdnAddNodeRequest {
	return &NullableClusterSdnAddNodeRequest{value: val, isSet: true}
}

func (v NullableClusterSdnAddNodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterSdnAddNodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


