/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterSdnListAllResponseDataFabricsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterSdnListAllResponseDataFabricsInner{}

// ClusterSdnListAllResponseDataFabricsInner struct for ClusterSdnListAllResponseDataFabricsInner
type ClusterSdnListAllResponseDataFabricsInner struct {

	// OSPF area. Either a IPv4 address or a 32-bit number. Gets validated in rust.
	Area *string `json:"area,omitempty"`

	// The csnp_interval property for Openfabric
	CsnpInterval *float32 `json:"csnp_interval,omitempty"`

	// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`

	// The hello_interval property for Openfabric
	HelloInterval *float32 `json:"hello_interval,omitempty"`

	// Identifier for SDN fabrics
	Id string `json:"id" validate:"regexp=[a-zA-Z0-9][a-zA-Z0-9-]{0,6}[a-zA-Z0-9]"`

	// The IP prefix for Node IPs
	Ip6Prefix *string `json:"ip6_prefix,omitempty" validate:"regexp=^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\\/[0-9]+|(?:[0-9]{1,3}\\\\.){3}[0-9]{1,3}\\/[0-9]{1,2})$"`

	// The IP prefix for Node IPs
	IpPrefix *string `json:"ip_prefix,omitempty" validate:"regexp=^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\\/[0-9]+|(?:[0-9]{1,3}\\\\.){3}[0-9]{1,3}\\/[0-9]{1,2})$"`

	// the token for unlocking the global SDN configuration
	LockToken *string `json:"lock-token,omitempty"`

	// A seconds interval, between 1 and 65535 inclusive, of how often to send an authenticated empty packet to the peer for the purpose of keeping a stateful firewall or NAT mapping valid persistently. For example, if the interface very rarely sends traffic, but it might at anytime receive traffic from another node, and it is behind NAT, the interface might benefit from having a persistent keepalive interval of 25 seconds. If unset or set to 0, it is turned off
	PersistentKeepalive *float32 `json:"persistent_keepalive,omitempty"`

	// Type of configuration entry in an SDN Fabric section config
	Protocol PveProtocolEnum `json:"protocol"`

	Redistribute []interface{} `json:"redistribute"`

	// A prefix list that should be used for filtering routes that are to be installed into the kernel routing table
	RouteFilter *string `json:"route_filter,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _ClusterSdnListAllResponseDataFabricsInner ClusterSdnListAllResponseDataFabricsInner

// NewClusterSdnListAllResponseDataFabricsInner instantiates a new ClusterSdnListAllResponseDataFabricsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterSdnListAllResponseDataFabricsInner(id string, protocol PveProtocolEnum, redistribute []interface{}) *ClusterSdnListAllResponseDataFabricsInner {
	this := ClusterSdnListAllResponseDataFabricsInner{}
	this.Id = id
	this.Protocol = protocol
	this.Redistribute = redistribute
	return &this
}

// NewClusterSdnListAllResponseDataFabricsInnerWithDefaults instantiates a new ClusterSdnListAllResponseDataFabricsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterSdnListAllResponseDataFabricsInnerWithDefaults() *ClusterSdnListAllResponseDataFabricsInner {
	this := ClusterSdnListAllResponseDataFabricsInner{}













	return &this
}


// GetArea returns the Area field value if set, zero value otherwise.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetArea() string {
	if o == nil || IsNil(o.Area) {
		var ret string
		return ret
	}
	return *o.Area
}

// GetAreaOk returns a tuple with the Area field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetAreaOk() (*string, bool) {
	if o == nil || IsNil(o.Area) {
		return nil, false
	}
	return o.Area, true
}

// HasArea returns a boolean if a field has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) HasArea() bool {
	if o != nil && !IsNil(o.Area) {
		return true
	}

	return false
}

// SetArea gets a reference to the given string and assigns it to the Area field.
func (o *ClusterSdnListAllResponseDataFabricsInner) SetArea(v string) {
	o.Area = &v
}


// GetCsnpInterval returns the CsnpInterval field value if set, zero value otherwise.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetCsnpInterval() float32 {
	if o == nil || IsNil(o.CsnpInterval) {
		var ret float32
		return ret
	}
	return *o.CsnpInterval
}

// GetCsnpIntervalOk returns a tuple with the CsnpInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetCsnpIntervalOk() (*float32, bool) {
	if o == nil || IsNil(o.CsnpInterval) {
		return nil, false
	}
	return o.CsnpInterval, true
}

// HasCsnpInterval returns a boolean if a field has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) HasCsnpInterval() bool {
	if o != nil && !IsNil(o.CsnpInterval) {
		return true
	}

	return false
}

// SetCsnpInterval gets a reference to the given float32 and assigns it to the CsnpInterval field.
func (o *ClusterSdnListAllResponseDataFabricsInner) SetCsnpInterval(v float32) {
	o.CsnpInterval = &v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ClusterSdnListAllResponseDataFabricsInner) SetDigest(v string) {
	o.Digest = &v
}


// GetHelloInterval returns the HelloInterval field value if set, zero value otherwise.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetHelloInterval() float32 {
	if o == nil || IsNil(o.HelloInterval) {
		var ret float32
		return ret
	}
	return *o.HelloInterval
}

// GetHelloIntervalOk returns a tuple with the HelloInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetHelloIntervalOk() (*float32, bool) {
	if o == nil || IsNil(o.HelloInterval) {
		return nil, false
	}
	return o.HelloInterval, true
}

// HasHelloInterval returns a boolean if a field has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) HasHelloInterval() bool {
	if o != nil && !IsNil(o.HelloInterval) {
		return true
	}

	return false
}

// SetHelloInterval gets a reference to the given float32 and assigns it to the HelloInterval field.
func (o *ClusterSdnListAllResponseDataFabricsInner) SetHelloInterval(v float32) {
	o.HelloInterval = &v
}


// GetId returns the Id field value
func (o *ClusterSdnListAllResponseDataFabricsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ClusterSdnListAllResponseDataFabricsInner) SetId(v string) {
	o.Id = v
}


// GetIp6Prefix returns the Ip6Prefix field value if set, zero value otherwise.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetIp6Prefix() string {
	if o == nil || IsNil(o.Ip6Prefix) {
		var ret string
		return ret
	}
	return *o.Ip6Prefix
}

// GetIp6PrefixOk returns a tuple with the Ip6Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetIp6PrefixOk() (*string, bool) {
	if o == nil || IsNil(o.Ip6Prefix) {
		return nil, false
	}
	return o.Ip6Prefix, true
}

// HasIp6Prefix returns a boolean if a field has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) HasIp6Prefix() bool {
	if o != nil && !IsNil(o.Ip6Prefix) {
		return true
	}

	return false
}

// SetIp6Prefix gets a reference to the given string and assigns it to the Ip6Prefix field.
func (o *ClusterSdnListAllResponseDataFabricsInner) SetIp6Prefix(v string) {
	o.Ip6Prefix = &v
}


// GetIpPrefix returns the IpPrefix field value if set, zero value otherwise.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetIpPrefix() string {
	if o == nil || IsNil(o.IpPrefix) {
		var ret string
		return ret
	}
	return *o.IpPrefix
}

// GetIpPrefixOk returns a tuple with the IpPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetIpPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.IpPrefix) {
		return nil, false
	}
	return o.IpPrefix, true
}

// HasIpPrefix returns a boolean if a field has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) HasIpPrefix() bool {
	if o != nil && !IsNil(o.IpPrefix) {
		return true
	}

	return false
}

// SetIpPrefix gets a reference to the given string and assigns it to the IpPrefix field.
func (o *ClusterSdnListAllResponseDataFabricsInner) SetIpPrefix(v string) {
	o.IpPrefix = &v
}


// GetLockToken returns the LockToken field value if set, zero value otherwise.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetLockToken() string {
	if o == nil || IsNil(o.LockToken) {
		var ret string
		return ret
	}
	return *o.LockToken
}

// GetLockTokenOk returns a tuple with the LockToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetLockTokenOk() (*string, bool) {
	if o == nil || IsNil(o.LockToken) {
		return nil, false
	}
	return o.LockToken, true
}

// HasLockToken returns a boolean if a field has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) HasLockToken() bool {
	if o != nil && !IsNil(o.LockToken) {
		return true
	}

	return false
}

// SetLockToken gets a reference to the given string and assigns it to the LockToken field.
func (o *ClusterSdnListAllResponseDataFabricsInner) SetLockToken(v string) {
	o.LockToken = &v
}


// GetPersistentKeepalive returns the PersistentKeepalive field value if set, zero value otherwise.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetPersistentKeepalive() float32 {
	if o == nil || IsNil(o.PersistentKeepalive) {
		var ret float32
		return ret
	}
	return *o.PersistentKeepalive
}

// GetPersistentKeepaliveOk returns a tuple with the PersistentKeepalive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetPersistentKeepaliveOk() (*float32, bool) {
	if o == nil || IsNil(o.PersistentKeepalive) {
		return nil, false
	}
	return o.PersistentKeepalive, true
}

// HasPersistentKeepalive returns a boolean if a field has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) HasPersistentKeepalive() bool {
	if o != nil && !IsNil(o.PersistentKeepalive) {
		return true
	}

	return false
}

// SetPersistentKeepalive gets a reference to the given float32 and assigns it to the PersistentKeepalive field.
func (o *ClusterSdnListAllResponseDataFabricsInner) SetPersistentKeepalive(v float32) {
	o.PersistentKeepalive = &v
}


// GetProtocol returns the Protocol field value
func (o *ClusterSdnListAllResponseDataFabricsInner) GetProtocol() PveProtocolEnum {
	if o == nil {
		var ret PveProtocolEnum
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetProtocolOk() (*PveProtocolEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *ClusterSdnListAllResponseDataFabricsInner) SetProtocol(v PveProtocolEnum) {
	o.Protocol = v
}


// GetRedistribute returns the Redistribute field value
func (o *ClusterSdnListAllResponseDataFabricsInner) GetRedistribute() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Redistribute
}

// GetRedistributeOk returns a tuple with the Redistribute field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetRedistributeOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Redistribute, true
}

// SetRedistribute sets field value
func (o *ClusterSdnListAllResponseDataFabricsInner) SetRedistribute(v []interface{}) {
	o.Redistribute = v
}


// GetRouteFilter returns the RouteFilter field value if set, zero value otherwise.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetRouteFilter() string {
	if o == nil || IsNil(o.RouteFilter) {
		var ret string
		return ret
	}
	return *o.RouteFilter
}

// GetRouteFilterOk returns a tuple with the RouteFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) GetRouteFilterOk() (*string, bool) {
	if o == nil || IsNil(o.RouteFilter) {
		return nil, false
	}
	return o.RouteFilter, true
}

// HasRouteFilter returns a boolean if a field has been set.
func (o *ClusterSdnListAllResponseDataFabricsInner) HasRouteFilter() bool {
	if o != nil && !IsNil(o.RouteFilter) {
		return true
	}

	return false
}

// SetRouteFilter gets a reference to the given string and assigns it to the RouteFilter field.
func (o *ClusterSdnListAllResponseDataFabricsInner) SetRouteFilter(v string) {
	o.RouteFilter = &v
}


func (o ClusterSdnListAllResponseDataFabricsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterSdnListAllResponseDataFabricsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Area) {
		toSerialize["area"] = o.Area
	}
	
	if !IsNil(o.CsnpInterval) {
		toSerialize["csnp_interval"] = o.CsnpInterval
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.HelloInterval) {
		toSerialize["hello_interval"] = o.HelloInterval
	}
	
	toSerialize["id"] = o.Id
	
	if !IsNil(o.Ip6Prefix) {
		toSerialize["ip6_prefix"] = o.Ip6Prefix
	}
	
	if !IsNil(o.IpPrefix) {
		toSerialize["ip_prefix"] = o.IpPrefix
	}
	
	if !IsNil(o.LockToken) {
		toSerialize["lock-token"] = o.LockToken
	}
	
	if !IsNil(o.PersistentKeepalive) {
		toSerialize["persistent_keepalive"] = o.PersistentKeepalive
	}
	
	toSerialize["protocol"] = o.Protocol
	
	toSerialize["redistribute"] = o.Redistribute
	
	if !IsNil(o.RouteFilter) {
		toSerialize["route_filter"] = o.RouteFilter
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterSdnListAllResponseDataFabricsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"protocol",
		"redistribute",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterSdnListAllResponseDataFabricsInner := _ClusterSdnListAllResponseDataFabricsInner{}

	err = json.Unmarshal(data, &varClusterSdnListAllResponseDataFabricsInner)

	if err != nil {
		return err
	}

	*o = ClusterSdnListAllResponseDataFabricsInner(varClusterSdnListAllResponseDataFabricsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "area")
		delete(additionalProperties, "csnp_interval")
		delete(additionalProperties, "digest")
		delete(additionalProperties, "hello_interval")
		delete(additionalProperties, "id")
		delete(additionalProperties, "ip6_prefix")
		delete(additionalProperties, "ip_prefix")
		delete(additionalProperties, "lock-token")
		delete(additionalProperties, "persistent_keepalive")
		delete(additionalProperties, "protocol")
		delete(additionalProperties, "redistribute")
		delete(additionalProperties, "route_filter")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterSdnListAllResponseDataFabricsInner struct {
	value *ClusterSdnListAllResponseDataFabricsInner
	isSet bool
}

func (v NullableClusterSdnListAllResponseDataFabricsInner) Get() *ClusterSdnListAllResponseDataFabricsInner {
	return v.value
}

func (v *NullableClusterSdnListAllResponseDataFabricsInner) Set(val *ClusterSdnListAllResponseDataFabricsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterSdnListAllResponseDataFabricsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterSdnListAllResponseDataFabricsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterSdnListAllResponseDataFabricsInner(val *ClusterSdnListAllResponseDataFabricsInner) *NullableClusterSdnListAllResponseDataFabricsInner {
	return &NullableClusterSdnListAllResponseDataFabricsInner{value: val, isSet: true}
}

func (v NullableClusterSdnListAllResponseDataFabricsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterSdnListAllResponseDataFabricsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


