/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterNotificationsGetWebhookEndpointResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterNotificationsGetWebhookEndpointResponseData{}

// ClusterNotificationsGetWebhookEndpointResponseData struct for ClusterNotificationsGetWebhookEndpointResponseData
type ClusterNotificationsGetWebhookEndpointResponseData struct {

	// HTTP body, base64 encoded
	Body *string `json:"body,omitempty"`

	// Comment
	Comment *string `json:"comment,omitempty"`

	// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`

	// Disable this target
	Disable *PveBoolean `json:"disable,omitempty"`

	// HTTP headers to set. These have to be formatted as a property string in the format name=<name>,value=<base64 of value>
	Header []string `json:"header,omitempty"`

	// HTTP method
	Method PveMethodEnum `json:"method"`

	// The name of the endpoint.
	Name string `json:"name" validate:"regexp=^[A-Za-z][A-Za-z0-9_]*$"`

	// Secrets to set. These have to be formatted as a property string in the format name=<name>,value=<base64 of value>
	Secret []string `json:"secret,omitempty"`

	// Server URL
	Url string `json:"url"`

	AdditionalProperties map[string]interface{}
}

type _ClusterNotificationsGetWebhookEndpointResponseData ClusterNotificationsGetWebhookEndpointResponseData

// NewClusterNotificationsGetWebhookEndpointResponseData instantiates a new ClusterNotificationsGetWebhookEndpointResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterNotificationsGetWebhookEndpointResponseData(method PveMethodEnum, name string, url string) *ClusterNotificationsGetWebhookEndpointResponseData {
	this := ClusterNotificationsGetWebhookEndpointResponseData{}
	var disable PveBoolean = PVEBOOLEAN__0
	this.Disable = &disable
	this.Method = method
	this.Name = name
	this.Url = url
	return &this
}

// NewClusterNotificationsGetWebhookEndpointResponseDataWithDefaults instantiates a new ClusterNotificationsGetWebhookEndpointResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterNotificationsGetWebhookEndpointResponseDataWithDefaults() *ClusterNotificationsGetWebhookEndpointResponseData {
	this := ClusterNotificationsGetWebhookEndpointResponseData{}




	var disable PveBoolean = PVEBOOLEAN__0
	this.Disable = &disable






	return &this
}


// GetBody returns the Body field value if set, zero value otherwise.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) SetBody(v string) {
	o.Body = &v
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) SetComment(v string) {
	o.Comment = &v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) SetDigest(v string) {
	o.Digest = &v
}


// GetDisable returns the Disable field value if set, zero value otherwise.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetDisable() PveBoolean {
	if o == nil || IsNil(o.Disable) {
		var ret PveBoolean
		return ret
	}
	return *o.Disable
}

// GetDisableOk returns a tuple with the Disable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetDisableOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Disable) {
		return nil, false
	}
	return o.Disable, true
}

// HasDisable returns a boolean if a field has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) HasDisable() bool {
	if o != nil && !IsNil(o.Disable) {
		return true
	}

	return false
}

// SetDisable gets a reference to the given PveBoolean and assigns it to the Disable field.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) SetDisable(v PveBoolean) {
	o.Disable = &v
}


// GetHeader returns the Header field value if set, zero value otherwise.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetHeader() []string {
	if o == nil || IsNil(o.Header) {
		var ret []string
		return ret
	}
	return o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetHeaderOk() ([]string, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given []string and assigns it to the Header field.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) SetHeader(v []string) {
	o.Header = v
}


// GetMethod returns the Method field value
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetMethod() PveMethodEnum {
	if o == nil {
		var ret PveMethodEnum
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetMethodOk() (*PveMethodEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *ClusterNotificationsGetWebhookEndpointResponseData) SetMethod(v PveMethodEnum) {
	o.Method = v
}


// GetName returns the Name field value
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ClusterNotificationsGetWebhookEndpointResponseData) SetName(v string) {
	o.Name = v
}


// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetSecret() []string {
	if o == nil || IsNil(o.Secret) {
		var ret []string
		return ret
	}
	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetSecretOk() ([]string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given []string and assigns it to the Secret field.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) SetSecret(v []string) {
	o.Secret = v
}


// GetUrl returns the Url field value
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ClusterNotificationsGetWebhookEndpointResponseData) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ClusterNotificationsGetWebhookEndpointResponseData) SetUrl(v string) {
	o.Url = v
}


func (o ClusterNotificationsGetWebhookEndpointResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterNotificationsGetWebhookEndpointResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.Disable) {
		toSerialize["disable"] = o.Disable
	}
	
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	
	toSerialize["method"] = o.Method
	
	toSerialize["name"] = o.Name
	
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	
	toSerialize["url"] = o.Url
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterNotificationsGetWebhookEndpointResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"method",
		"name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterNotificationsGetWebhookEndpointResponseData := _ClusterNotificationsGetWebhookEndpointResponseData{}

	err = json.Unmarshal(data, &varClusterNotificationsGetWebhookEndpointResponseData)

	if err != nil {
		return err
	}

	*o = ClusterNotificationsGetWebhookEndpointResponseData(varClusterNotificationsGetWebhookEndpointResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "body")
		delete(additionalProperties, "comment")
		delete(additionalProperties, "digest")
		delete(additionalProperties, "disable")
		delete(additionalProperties, "header")
		delete(additionalProperties, "method")
		delete(additionalProperties, "name")
		delete(additionalProperties, "secret")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterNotificationsGetWebhookEndpointResponseData struct {
	value *ClusterNotificationsGetWebhookEndpointResponseData
	isSet bool
}

func (v NullableClusterNotificationsGetWebhookEndpointResponseData) Get() *ClusterNotificationsGetWebhookEndpointResponseData {
	return v.value
}

func (v *NullableClusterNotificationsGetWebhookEndpointResponseData) Set(val *ClusterNotificationsGetWebhookEndpointResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterNotificationsGetWebhookEndpointResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterNotificationsGetWebhookEndpointResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterNotificationsGetWebhookEndpointResponseData(val *ClusterNotificationsGetWebhookEndpointResponseData) *NullableClusterNotificationsGetWebhookEndpointResponseData {
	return &NullableClusterNotificationsGetWebhookEndpointResponseData{value: val, isSet: true}
}

func (v NullableClusterNotificationsGetWebhookEndpointResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterNotificationsGetWebhookEndpointResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


