/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PveLocationConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PveLocationConfig{}

// PveLocationConfig struct for PveLocationConfig
type PveLocationConfig struct {

	// The latitude of the nodes location in degrees.
	Latitude float32 `json:"latitude"`

	// The longitude of the nodes location in degrees.
	Longitude float32 `json:"longitude"`

	// The name of the location of this node
	Name *string `json:"name,omitempty"`

}

type _PveLocationConfig PveLocationConfig

// NewPveLocationConfig instantiates a new PveLocationConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPveLocationConfig(latitude float32, longitude float32) *PveLocationConfig {
	this := PveLocationConfig{}
	this.Latitude = latitude
	this.Longitude = longitude
	return &this
}

// NewPveLocationConfigWithDefaults instantiates a new PveLocationConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPveLocationConfigWithDefaults() *PveLocationConfig {
	this := PveLocationConfig{}




	return &this
}


// GetLatitude returns the Latitude field value
func (o *PveLocationConfig) GetLatitude() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *PveLocationConfig) GetLatitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *PveLocationConfig) SetLatitude(v float32) {
	o.Latitude = v
}


// GetLongitude returns the Longitude field value
func (o *PveLocationConfig) GetLongitude() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *PveLocationConfig) GetLongitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *PveLocationConfig) SetLongitude(v float32) {
	o.Longitude = v
}


// GetName returns the Name field value if set, zero value otherwise.
func (o *PveLocationConfig) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveLocationConfig) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PveLocationConfig) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PveLocationConfig) SetName(v string) {
	o.Name = &v
}


func (o PveLocationConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PveLocationConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["latitude"] = o.Latitude
	
	toSerialize["longitude"] = o.Longitude
	
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	
	return toSerialize, nil
}

func (o *PveLocationConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"latitude",
		"longitude",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPveLocationConfig := _PveLocationConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPveLocationConfig)

	if err != nil {
		return err
	}

	*o = PveLocationConfig(varPveLocationConfig)

	return err
}

type NullablePveLocationConfig struct {
	value *PveLocationConfig
	isSet bool
}

func (v NullablePveLocationConfig) Get() *PveLocationConfig {
	return v.value
}

func (v *NullablePveLocationConfig) Set(val *PveLocationConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePveLocationConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePveLocationConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveLocationConfig(val *PveLocationConfig) *NullablePveLocationConfig {
	return &NullablePveLocationConfig{value: val, isSet: true}
}

func (v NullablePveLocationConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveLocationConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


// pveShorthandValue converts a value into the unquoted form expected
// by Proxmox's `key=value,…` CLI shorthand. Uses encoding/json (already
// imported) to avoid pulling in fmt in models that don't otherwise need
// it, then strips the surrounding quotes for strings.
func PveLocationConfig_pveShorthandValue(v interface{}) string {
	if v == nil {
		return ""
	}
	b, err := json.Marshal(v)
	if err != nil {
		return ""
	}
	s := string(b)
	if n := len(s); n >= 2 && s[0] == '"' && s[n-1] == '"' {
		return s[1 : n-1]
	}
	return s
}

// ToShorthand serialises the PveLocationConfig into Proxmox's CLI-style
// shorthand string (`key=value,…`). The property marked
// `x-pve-default-key` is emitted positionally without a `key=` prefix;
// aliases collapse multiple property names to the same wire key.
//
// Example: {Model: "virtio", Bridge: "vmbr0", Firewall: 1}
//       => "virtio,bridge=vmbr0,firewall=1"
func (o *PveLocationConfig) ToShorthand() string {
	if o == nil {
		return ""
	}
	var result string
	sep := ""
	
	
	result += sep + "latitude=" + PveLocationConfig_pveShorthandValue(o.Latitude)
	sep = ","
	
	result += sep + "longitude=" + PveLocationConfig_pveShorthandValue(o.Longitude)
	sep = ","
	
	if o.Name != nil {
		result += sep + "name=" + PveLocationConfig_pveShorthandValue(*o.Name)
		sep = ","
	}
	
	return result
}

