/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PveTpmstateConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PveTpmstateConfig{}

// PveTpmstateConfig struct for PveTpmstateConfig
type PveTpmstateConfig struct {

	// The drive's backing volume.
	File string `json:"file" validate:"regexp=^(?:[A-Za-z0-9_\\\\-]+:.+|\\/.+)$"`

	// Format of the image.
	Format *PveQemuFormatEnum `json:"format,omitempty"`

	// Create a new disk, importing from this source (volume ID or absolute path). When an absolute path is specified, it's up to you to ensure that the source is not actively used by another process during the import!
	ImportFrom *string `json:"import-from,omitempty" validate:"regexp=^(?:[A-Za-z0-9_\\\\-]+:.+|\\/.+)$"`

	// Disk size. This is purely informational and has no effect.
	Size *string `json:"size,omitempty" validate:"regexp=^\\\\d+(?:\\\\.\\\\d+)?[KMGT]?$"`

	// The TPM interface version. v2.0 is newer and should be preferred. Note that this cannot be changed later on.
	Version *PveVersionEnum `json:"version,omitempty"`

	Volume *string `json:"volume,omitempty"`

}

type _PveTpmstateConfig PveTpmstateConfig

// NewPveTpmstateConfig instantiates a new PveTpmstateConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPveTpmstateConfig(file string) *PveTpmstateConfig {
	this := PveTpmstateConfig{}
	this.File = file
	var version PveVersionEnum = PVEVERSIONENUM_V1_2
	this.Version = &version
	return &this
}

// NewPveTpmstateConfigWithDefaults instantiates a new PveTpmstateConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPveTpmstateConfigWithDefaults() *PveTpmstateConfig {
	this := PveTpmstateConfig{}





	var version PveVersionEnum = PVEVERSIONENUM_V1_2
	this.Version = &version


	return &this
}


// GetFile returns the File field value
func (o *PveTpmstateConfig) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *PveTpmstateConfig) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *PveTpmstateConfig) SetFile(v string) {
	o.File = v
}


// GetFormat returns the Format field value if set, zero value otherwise.
func (o *PveTpmstateConfig) GetFormat() PveQemuFormatEnum {
	if o == nil || IsNil(o.Format) {
		var ret PveQemuFormatEnum
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveTpmstateConfig) GetFormatOk() (*PveQemuFormatEnum, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *PveTpmstateConfig) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given PveQemuFormatEnum and assigns it to the Format field.
func (o *PveTpmstateConfig) SetFormat(v PveQemuFormatEnum) {
	o.Format = &v
}


// GetImportFrom returns the ImportFrom field value if set, zero value otherwise.
func (o *PveTpmstateConfig) GetImportFrom() string {
	if o == nil || IsNil(o.ImportFrom) {
		var ret string
		return ret
	}
	return *o.ImportFrom
}

// GetImportFromOk returns a tuple with the ImportFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveTpmstateConfig) GetImportFromOk() (*string, bool) {
	if o == nil || IsNil(o.ImportFrom) {
		return nil, false
	}
	return o.ImportFrom, true
}

// HasImportFrom returns a boolean if a field has been set.
func (o *PveTpmstateConfig) HasImportFrom() bool {
	if o != nil && !IsNil(o.ImportFrom) {
		return true
	}

	return false
}

// SetImportFrom gets a reference to the given string and assigns it to the ImportFrom field.
func (o *PveTpmstateConfig) SetImportFrom(v string) {
	o.ImportFrom = &v
}


// GetSize returns the Size field value if set, zero value otherwise.
func (o *PveTpmstateConfig) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveTpmstateConfig) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *PveTpmstateConfig) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *PveTpmstateConfig) SetSize(v string) {
	o.Size = &v
}


// GetVersion returns the Version field value if set, zero value otherwise.
func (o *PveTpmstateConfig) GetVersion() PveVersionEnum {
	if o == nil || IsNil(o.Version) {
		var ret PveVersionEnum
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveTpmstateConfig) GetVersionOk() (*PveVersionEnum, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *PveTpmstateConfig) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given PveVersionEnum and assigns it to the Version field.
func (o *PveTpmstateConfig) SetVersion(v PveVersionEnum) {
	o.Version = &v
}


// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *PveTpmstateConfig) GetVolume() string {
	if o == nil || IsNil(o.Volume) {
		var ret string
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveTpmstateConfig) GetVolumeOk() (*string, bool) {
	if o == nil || IsNil(o.Volume) {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *PveTpmstateConfig) HasVolume() bool {
	if o != nil && !IsNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given string and assigns it to the Volume field.
func (o *PveTpmstateConfig) SetVolume(v string) {
	o.Volume = &v
}


func (o PveTpmstateConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PveTpmstateConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["file"] = o.File
	
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	
	if !IsNil(o.ImportFrom) {
		toSerialize["import-from"] = o.ImportFrom
	}
	
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	
	if !IsNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	
	return toSerialize, nil
}

func (o *PveTpmstateConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPveTpmstateConfig := _PveTpmstateConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPveTpmstateConfig)

	if err != nil {
		return err
	}

	*o = PveTpmstateConfig(varPveTpmstateConfig)

	return err
}

type NullablePveTpmstateConfig struct {
	value *PveTpmstateConfig
	isSet bool
}

func (v NullablePveTpmstateConfig) Get() *PveTpmstateConfig {
	return v.value
}

func (v *NullablePveTpmstateConfig) Set(val *PveTpmstateConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePveTpmstateConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePveTpmstateConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveTpmstateConfig(val *PveTpmstateConfig) *NullablePveTpmstateConfig {
	return &NullablePveTpmstateConfig{value: val, isSet: true}
}

func (v NullablePveTpmstateConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveTpmstateConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


// pveShorthandValue converts a value into the unquoted form expected
// by Proxmox's `key=value,…` CLI shorthand. Uses encoding/json (already
// imported) to avoid pulling in fmt in models that don't otherwise need
// it, then strips the surrounding quotes for strings.
func PveTpmstateConfig_pveShorthandValue(v interface{}) string {
	if v == nil {
		return ""
	}
	b, err := json.Marshal(v)
	if err != nil {
		return ""
	}
	s := string(b)
	if n := len(s); n >= 2 && s[0] == '"' && s[n-1] == '"' {
		return s[1 : n-1]
	}
	return s
}

// ToShorthand serialises the PveTpmstateConfig into Proxmox's CLI-style
// shorthand string (`key=value,…`). The property marked
// `x-pve-default-key` is emitted positionally without a `key=` prefix;
// aliases collapse multiple property names to the same wire key.
//
// Example: {Model: "virtio", Bridge: "vmbr0", Firewall: 1}
//       => "virtio,bridge=vmbr0,firewall=1"
func (o *PveTpmstateConfig) ToShorthand() string {
	if o == nil {
		return ""
	}
	var result string
	sep := ""
	
	result += sep + PveTpmstateConfig_pveShorthandValue(o.File)
	sep = ","
	
	
	if o.Format != nil {
		result += sep + "format=" + PveTpmstateConfig_pveShorthandValue(*o.Format)
		sep = ","
	}
	
	if o.ImportFrom != nil {
		result += sep + "import-from=" + PveTpmstateConfig_pveShorthandValue(*o.ImportFrom)
		sep = ","
	}
	
	if o.Size != nil {
		result += sep + "size=" + PveTpmstateConfig_pveShorthandValue(*o.Size)
		sep = ","
	}
	
	if o.Version != nil {
		result += sep + "version=" + PveTpmstateConfig_pveShorthandValue(*o.Version)
		sep = ","
	}
	
	if o.Volume != nil {
		result += sep + "file=" + PveTpmstateConfig_pveShorthandValue(*o.Volume)
		sep = ","
	}
	
	return result
}

