/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClusterQemuUpdateCustomCpuModelsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterQemuUpdateCustomCpuModelsRequest{}

// ClusterQemuUpdateCustomCpuModelsRequest struct for ClusterQemuUpdateCustomCpuModelsRequest
type ClusterQemuUpdateCustomCpuModelsRequest struct {

	// A list of properties to delete.
	Delete *string `json:"delete,omitempty"`

	// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`

	// List of additional CPU flags separated by ';'. Use '+FLAG' to enable, '-FLAG' to disable a flag. There is a special 'nested-virt' shorthand which controls nested virtualization for the current CPU ('svm' for AMD and 'vmx' for Intel). Custom CPU models can specify any flag supported by QEMU/KVM, VM-specific flags must be from the following set for security reasons: aes, amd-no-ssb, amd-ssbd, hv-evmcs, hv-tlbflush, ibpb, md-clear, nested-virt, pcid, pdpe1gb, spec-ctrl, ssbd, virt-ssbd
	Flags *string `json:"flags,omitempty" validate:"regexp=(?:(?:([+-])([a-zA-Z0-9\\\\-_\\\\.]+))(;(?:([+-])([a-zA-Z0-9\\\\-_\\\\.]+)))*)"`

	// Number of physical address bits available to the guest.
	GuestPhysBits *int32 `json:"guest-phys-bits,omitempty"`

	// Do not identify as a KVM virtual machine. Only affects vCPUs with x86-64 architecture.
	Hidden *PveBoolean `json:"hidden,omitempty"`

	// The Hyper-V vendor ID. Some drivers or programs inside Windows guests need a specific ID.
	HvVendorId *string `json:"hv-vendor-id,omitempty" validate:"regexp=(?:[a-zA-Z0-9]{1,12})"`

	// Maximum input value for the basic CPUID leaves the guest can query - that is the vendor (leaf 0), family/model/stepping and feature bits (leaf 1), cache and topology info (leaves 4 and B), and so on. Higher-numbered leaves are hidden. Setting '30' is a common workaround for Hyper-V boot failures on Windows guests running on recent Intel hosts. Only applies when the vCPU architecture is x86_64.
	Level *int32 `json:"level,omitempty"`

	// The physical memory address bits that are reported to the guest OS. Should be smaller or equal to the host's. Set to 'host' to use value from host CPU, but note that doing so will break live migration to CPUs with other values.
	PhysBits *string `json:"phys-bits,omitempty"`

	// CPU model and vendor to report to the guest. Must be a QEMU/KVM supported model. Only valid for custom CPU model definitions, default models will always report themselves to the guest OS.
	ReportedModel *PveReportedModelEnum `json:"reported-model,omitempty"`

}

// NewClusterQemuUpdateCustomCpuModelsRequest instantiates a new ClusterQemuUpdateCustomCpuModelsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterQemuUpdateCustomCpuModelsRequest() *ClusterQemuUpdateCustomCpuModelsRequest {
	this := ClusterQemuUpdateCustomCpuModelsRequest{}
	var hidden PveBoolean = PVEBOOLEAN__0
	this.Hidden = &hidden
	var reportedModel PveReportedModelEnum = PVEREPORTEDMODELENUM_KVM64
	this.ReportedModel = &reportedModel
	return &this
}

// NewClusterQemuUpdateCustomCpuModelsRequestWithDefaults instantiates a new ClusterQemuUpdateCustomCpuModelsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterQemuUpdateCustomCpuModelsRequestWithDefaults() *ClusterQemuUpdateCustomCpuModelsRequest {
	this := ClusterQemuUpdateCustomCpuModelsRequest{}





	var hidden PveBoolean = PVEBOOLEAN__0
	this.Hidden = &hidden




	var reportedModel PveReportedModelEnum = PVEREPORTEDMODELENUM_KVM64
	this.ReportedModel = &reportedModel

	return &this
}


// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetDelete() string {
	if o == nil || IsNil(o.Delete) {
		var ret string
		return ret
	}
	return *o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetDeleteOk() (*string, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given string and assigns it to the Delete field.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) SetDelete(v string) {
	o.Delete = &v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetFlags() string {
	if o == nil || IsNil(o.Flags) {
		var ret string
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetFlagsOk() (*string, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given string and assigns it to the Flags field.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) SetFlags(v string) {
	o.Flags = &v
}


// GetGuestPhysBits returns the GuestPhysBits field value if set, zero value otherwise.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetGuestPhysBits() int32 {
	if o == nil || IsNil(o.GuestPhysBits) {
		var ret int32
		return ret
	}
	return *o.GuestPhysBits
}

// GetGuestPhysBitsOk returns a tuple with the GuestPhysBits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetGuestPhysBitsOk() (*int32, bool) {
	if o == nil || IsNil(o.GuestPhysBits) {
		return nil, false
	}
	return o.GuestPhysBits, true
}

// HasGuestPhysBits returns a boolean if a field has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) HasGuestPhysBits() bool {
	if o != nil && !IsNil(o.GuestPhysBits) {
		return true
	}

	return false
}

// SetGuestPhysBits gets a reference to the given int32 and assigns it to the GuestPhysBits field.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) SetGuestPhysBits(v int32) {
	o.GuestPhysBits = &v
}


// GetHidden returns the Hidden field value if set, zero value otherwise.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetHidden() PveBoolean {
	if o == nil || IsNil(o.Hidden) {
		var ret PveBoolean
		return ret
	}
	return *o.Hidden
}

// GetHiddenOk returns a tuple with the Hidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetHiddenOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Hidden) {
		return nil, false
	}
	return o.Hidden, true
}

// HasHidden returns a boolean if a field has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) HasHidden() bool {
	if o != nil && !IsNil(o.Hidden) {
		return true
	}

	return false
}

// SetHidden gets a reference to the given PveBoolean and assigns it to the Hidden field.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) SetHidden(v PveBoolean) {
	o.Hidden = &v
}


// GetHvVendorId returns the HvVendorId field value if set, zero value otherwise.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetHvVendorId() string {
	if o == nil || IsNil(o.HvVendorId) {
		var ret string
		return ret
	}
	return *o.HvVendorId
}

// GetHvVendorIdOk returns a tuple with the HvVendorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetHvVendorIdOk() (*string, bool) {
	if o == nil || IsNil(o.HvVendorId) {
		return nil, false
	}
	return o.HvVendorId, true
}

// HasHvVendorId returns a boolean if a field has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) HasHvVendorId() bool {
	if o != nil && !IsNil(o.HvVendorId) {
		return true
	}

	return false
}

// SetHvVendorId gets a reference to the given string and assigns it to the HvVendorId field.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) SetHvVendorId(v string) {
	o.HvVendorId = &v
}


// GetLevel returns the Level field value if set, zero value otherwise.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetLevel() int32 {
	if o == nil || IsNil(o.Level) {
		var ret int32
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given int32 and assigns it to the Level field.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) SetLevel(v int32) {
	o.Level = &v
}


// GetPhysBits returns the PhysBits field value if set, zero value otherwise.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetPhysBits() string {
	if o == nil || IsNil(o.PhysBits) {
		var ret string
		return ret
	}
	return *o.PhysBits
}

// GetPhysBitsOk returns a tuple with the PhysBits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetPhysBitsOk() (*string, bool) {
	if o == nil || IsNil(o.PhysBits) {
		return nil, false
	}
	return o.PhysBits, true
}

// HasPhysBits returns a boolean if a field has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) HasPhysBits() bool {
	if o != nil && !IsNil(o.PhysBits) {
		return true
	}

	return false
}

// SetPhysBits gets a reference to the given string and assigns it to the PhysBits field.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) SetPhysBits(v string) {
	o.PhysBits = &v
}


// GetReportedModel returns the ReportedModel field value if set, zero value otherwise.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetReportedModel() PveReportedModelEnum {
	if o == nil || IsNil(o.ReportedModel) {
		var ret PveReportedModelEnum
		return ret
	}
	return *o.ReportedModel
}

// GetReportedModelOk returns a tuple with the ReportedModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) GetReportedModelOk() (*PveReportedModelEnum, bool) {
	if o == nil || IsNil(o.ReportedModel) {
		return nil, false
	}
	return o.ReportedModel, true
}

// HasReportedModel returns a boolean if a field has been set.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) HasReportedModel() bool {
	if o != nil && !IsNil(o.ReportedModel) {
		return true
	}

	return false
}

// SetReportedModel gets a reference to the given PveReportedModelEnum and assigns it to the ReportedModel field.
func (o *ClusterQemuUpdateCustomCpuModelsRequest) SetReportedModel(v PveReportedModelEnum) {
	o.ReportedModel = &v
}


func (o ClusterQemuUpdateCustomCpuModelsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterQemuUpdateCustomCpuModelsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	
	if !IsNil(o.GuestPhysBits) {
		toSerialize["guest-phys-bits"] = o.GuestPhysBits
	}
	
	if !IsNil(o.Hidden) {
		toSerialize["hidden"] = o.Hidden
	}
	
	if !IsNil(o.HvVendorId) {
		toSerialize["hv-vendor-id"] = o.HvVendorId
	}
	
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	
	if !IsNil(o.PhysBits) {
		toSerialize["phys-bits"] = o.PhysBits
	}
	
	if !IsNil(o.ReportedModel) {
		toSerialize["reported-model"] = o.ReportedModel
	}
	
	return toSerialize, nil
}

type NullableClusterQemuUpdateCustomCpuModelsRequest struct {
	value *ClusterQemuUpdateCustomCpuModelsRequest
	isSet bool
}

func (v NullableClusterQemuUpdateCustomCpuModelsRequest) Get() *ClusterQemuUpdateCustomCpuModelsRequest {
	return v.value
}

func (v *NullableClusterQemuUpdateCustomCpuModelsRequest) Set(val *ClusterQemuUpdateCustomCpuModelsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterQemuUpdateCustomCpuModelsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterQemuUpdateCustomCpuModelsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterQemuUpdateCustomCpuModelsRequest(val *ClusterQemuUpdateCustomCpuModelsRequest) *NullableClusterQemuUpdateCustomCpuModelsRequest {
	return &NullableClusterQemuUpdateCustomCpuModelsRequest{value: val, isSet: true}
}

func (v NullableClusterQemuUpdateCustomCpuModelsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterQemuUpdateCustomCpuModelsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


