/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClusterConfigJoinRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterConfigJoinRequest{}

// ClusterConfigJoinRequest struct for ClusterConfigJoinRequest
type ClusterConfigJoinRequest struct {

	// Certificate SHA 256 fingerprint.
	Fingerprint string `json:"fingerprint" validate:"regexp=([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}"`

	// Do not throw error if node already exists.
	Force *PveBoolean `json:"force,omitempty"`

	// Hostname (or IP) of an existing cluster member.
	Hostname string `json:"hostname"`

	// Node id for this node.
	Nodeid *int64 `json:"nodeid,omitempty"`

	// Superuser (root) password of peer node.
	Password string `json:"password"`

	// Number of votes for this node
	Votes *int64 `json:"votes,omitempty"`

	// Links — each map entry expands to `link<index>` on the wire (PVE accepts the indexed form). Indices range 0..7.
	Links map[int32]PveLinkField `json:"-"`
}

type _ClusterConfigJoinRequest ClusterConfigJoinRequest

// NewClusterConfigJoinRequest instantiates a new ClusterConfigJoinRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterConfigJoinRequest(fingerprint string, hostname string, password string) *ClusterConfigJoinRequest {
	this := ClusterConfigJoinRequest{}
	this.Fingerprint = fingerprint
	this.Hostname = hostname
	this.Password = password
	return &this
}

// NewClusterConfigJoinRequestWithDefaults instantiates a new ClusterConfigJoinRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterConfigJoinRequestWithDefaults() *ClusterConfigJoinRequest {
	this := ClusterConfigJoinRequest{}







	return &this
}


// GetFingerprint returns the Fingerprint field value
func (o *ClusterConfigJoinRequest) GetFingerprint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fingerprint
}

// GetFingerprintOk returns a tuple with the Fingerprint field value
// and a boolean to check if the value has been set.
func (o *ClusterConfigJoinRequest) GetFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fingerprint, true
}

// SetFingerprint sets field value
func (o *ClusterConfigJoinRequest) SetFingerprint(v string) {
	o.Fingerprint = v
}


// GetForce returns the Force field value if set, zero value otherwise.
func (o *ClusterConfigJoinRequest) GetForce() PveBoolean {
	if o == nil || IsNil(o.Force) {
		var ret PveBoolean
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterConfigJoinRequest) GetForceOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Force) {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *ClusterConfigJoinRequest) HasForce() bool {
	if o != nil && !IsNil(o.Force) {
		return true
	}

	return false
}

// SetForce gets a reference to the given PveBoolean and assigns it to the Force field.
func (o *ClusterConfigJoinRequest) SetForce(v PveBoolean) {
	o.Force = &v
}


// GetHostname returns the Hostname field value
func (o *ClusterConfigJoinRequest) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *ClusterConfigJoinRequest) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *ClusterConfigJoinRequest) SetHostname(v string) {
	o.Hostname = v
}


// GetNodeid returns the Nodeid field value if set, zero value otherwise.
func (o *ClusterConfigJoinRequest) GetNodeid() int64 {
	if o == nil || IsNil(o.Nodeid) {
		var ret int64
		return ret
	}
	return *o.Nodeid
}

// GetNodeidOk returns a tuple with the Nodeid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterConfigJoinRequest) GetNodeidOk() (*int64, bool) {
	if o == nil || IsNil(o.Nodeid) {
		return nil, false
	}
	return o.Nodeid, true
}

// HasNodeid returns a boolean if a field has been set.
func (o *ClusterConfigJoinRequest) HasNodeid() bool {
	if o != nil && !IsNil(o.Nodeid) {
		return true
	}

	return false
}

// SetNodeid gets a reference to the given int64 and assigns it to the Nodeid field.
func (o *ClusterConfigJoinRequest) SetNodeid(v int64) {
	o.Nodeid = &v
}


// GetPassword returns the Password field value
func (o *ClusterConfigJoinRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *ClusterConfigJoinRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *ClusterConfigJoinRequest) SetPassword(v string) {
	o.Password = v
}


// GetVotes returns the Votes field value if set, zero value otherwise.
func (o *ClusterConfigJoinRequest) GetVotes() int64 {
	if o == nil || IsNil(o.Votes) {
		var ret int64
		return ret
	}
	return *o.Votes
}

// GetVotesOk returns a tuple with the Votes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterConfigJoinRequest) GetVotesOk() (*int64, bool) {
	if o == nil || IsNil(o.Votes) {
		return nil, false
	}
	return o.Votes, true
}

// HasVotes returns a boolean if a field has been set.
func (o *ClusterConfigJoinRequest) HasVotes() bool {
	if o != nil && !IsNil(o.Votes) {
		return true
	}

	return false
}

// SetVotes gets a reference to the given int64 and assigns it to the Votes field.
func (o *ClusterConfigJoinRequest) SetVotes(v int64) {
	o.Votes = &v
}


func (o ClusterConfigJoinRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterConfigJoinRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["fingerprint"] = o.Fingerprint
	
	if !IsNil(o.Force) {
		toSerialize["force"] = o.Force
	}
	
	toSerialize["hostname"] = o.Hostname
	
	if !IsNil(o.Nodeid) {
		toSerialize["nodeid"] = o.Nodeid
	}
	
	toSerialize["password"] = o.Password
	
	if !IsNil(o.Votes) {
		toSerialize["votes"] = o.Votes
	}
	
	// Expand the Links map back into individual link<n>
	// wire keys that PVE actually accepts.
	for _idx, _v := range o.Links {
		_idxBytes, _ := json.Marshal(_idx)
		toSerialize["link"+string(_idxBytes)] = _v
	}
	return toSerialize, nil
}

func (o *ClusterConfigJoinRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fingerprint",
		"hostname",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterConfigJoinRequest := _ClusterConfigJoinRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterConfigJoinRequest)

	if err != nil {
		return err
	}

	*o = ClusterConfigJoinRequest(varClusterConfigJoinRequest)

	return err
}

type NullableClusterConfigJoinRequest struct {
	value *ClusterConfigJoinRequest
	isSet bool
}

func (v NullableClusterConfigJoinRequest) Get() *ClusterConfigJoinRequest {
	return v.value
}

func (v *NullableClusterConfigJoinRequest) Set(val *ClusterConfigJoinRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterConfigJoinRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterConfigJoinRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterConfigJoinRequest(val *ClusterConfigJoinRequest) *NullableClusterConfigJoinRequest {
	return &NullableClusterConfigJoinRequest{value: val, isSet: true}
}

func (v NullableClusterConfigJoinRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterConfigJoinRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


