/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PveCompressEnum the model 'PveCompressEnum'
type PveCompressEnum string

// List of PveCompressEnum
const (
	PVECOMPRESSENUM__0 PveCompressEnum = "0"
	PVECOMPRESSENUM__1 PveCompressEnum = "1"
	PVECOMPRESSENUM_GZIP PveCompressEnum = "gzip"
	PVECOMPRESSENUM_LZO PveCompressEnum = "lzo"
	PVECOMPRESSENUM_ZSTD PveCompressEnum = "zstd"
)

// All allowed values of PveCompressEnum enum
var AllowedPveCompressEnumEnumValues = []PveCompressEnum{
	"0",
	"1",
	"gzip",
	"lzo",
	"zstd",
}

func (v *PveCompressEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PveCompressEnum(value)
	for _, existing := range AllowedPveCompressEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PveCompressEnum", value)
}

// NewPveCompressEnumFromValue returns a pointer to a valid PveCompressEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPveCompressEnumFromValue(v string) (*PveCompressEnum, error) {
	ev := PveCompressEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PveCompressEnum: valid values are %v", v, AllowedPveCompressEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PveCompressEnum) IsValid() bool {
	for _, existing := range AllowedPveCompressEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PveCompressEnum value
func (v PveCompressEnum) Ptr() *PveCompressEnum {
	return &v
}

type NullablePveCompressEnum struct {
	value *PveCompressEnum
	isSet bool
}

func (v NullablePveCompressEnum) Get() *PveCompressEnum {
	return v.value
}

func (v *NullablePveCompressEnum) Set(val *PveCompressEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePveCompressEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePveCompressEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveCompressEnum(val *PveCompressEnum) *NullablePveCompressEnum {
	return &NullablePveCompressEnum{value: val, isSet: true}
}

func (v NullablePveCompressEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveCompressEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

