/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesHardwarePciIndexResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesHardwarePciIndexResponseDataInner{}

// NodesHardwarePciIndexResponseDataInner struct for NodesHardwarePciIndexResponseDataInner
type NodesHardwarePciIndexResponseDataInner struct {

	Method string `json:"method"`

	AdditionalProperties map[string]interface{}
}

type _NodesHardwarePciIndexResponseDataInner NodesHardwarePciIndexResponseDataInner

// NewNodesHardwarePciIndexResponseDataInner instantiates a new NodesHardwarePciIndexResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesHardwarePciIndexResponseDataInner(method string) *NodesHardwarePciIndexResponseDataInner {
	this := NodesHardwarePciIndexResponseDataInner{}
	this.Method = method
	return &this
}

// NewNodesHardwarePciIndexResponseDataInnerWithDefaults instantiates a new NodesHardwarePciIndexResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesHardwarePciIndexResponseDataInnerWithDefaults() *NodesHardwarePciIndexResponseDataInner {
	this := NodesHardwarePciIndexResponseDataInner{}


	return &this
}


// GetMethod returns the Method field value
func (o *NodesHardwarePciIndexResponseDataInner) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *NodesHardwarePciIndexResponseDataInner) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *NodesHardwarePciIndexResponseDataInner) SetMethod(v string) {
	o.Method = v
}


func (o NodesHardwarePciIndexResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesHardwarePciIndexResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["method"] = o.Method
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesHardwarePciIndexResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"method",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesHardwarePciIndexResponseDataInner := _NodesHardwarePciIndexResponseDataInner{}

	err = json.Unmarshal(data, &varNodesHardwarePciIndexResponseDataInner)

	if err != nil {
		return err
	}

	*o = NodesHardwarePciIndexResponseDataInner(varNodesHardwarePciIndexResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "method")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesHardwarePciIndexResponseDataInner struct {
	value *NodesHardwarePciIndexResponseDataInner
	isSet bool
}

func (v NullableNodesHardwarePciIndexResponseDataInner) Get() *NodesHardwarePciIndexResponseDataInner {
	return v.value
}

func (v *NullableNodesHardwarePciIndexResponseDataInner) Set(val *NodesHardwarePciIndexResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesHardwarePciIndexResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesHardwarePciIndexResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesHardwarePciIndexResponseDataInner(val *NodesHardwarePciIndexResponseDataInner) *NullableNodesHardwarePciIndexResponseDataInner {
	return &NullableNodesHardwarePciIndexResponseDataInner{value: val, isSet: true}
}

func (v NullableNodesHardwarePciIndexResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesHardwarePciIndexResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


