/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccessAclUpdateAclRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessAclUpdateAclRequest{}

// AccessAclUpdateAclRequest struct for AccessAclUpdateAclRequest
type AccessAclUpdateAclRequest struct {

	// Remove permissions (instead of adding it).
	Delete *PveBoolean `json:"delete,omitempty"`

	// List of groups.
	Groups *string `json:"groups,omitempty"`

	// Access control path
	Path string `json:"path"`

	// Allow to propagate (inherit) permissions.
	Propagate *PveBoolean `json:"propagate,omitempty"`

	// List of roles.
	Roles string `json:"roles"`

	// List of API tokens.
	Tokens *string `json:"tokens,omitempty"`

	// List of users.
	Users *string `json:"users,omitempty"`

}

type _AccessAclUpdateAclRequest AccessAclUpdateAclRequest

// NewAccessAclUpdateAclRequest instantiates a new AccessAclUpdateAclRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessAclUpdateAclRequest(path string, roles string) *AccessAclUpdateAclRequest {
	this := AccessAclUpdateAclRequest{}
	this.Path = path
	var propagate PveBoolean = PVEBOOLEAN__1
	this.Propagate = &propagate
	this.Roles = roles
	return &this
}

// NewAccessAclUpdateAclRequestWithDefaults instantiates a new AccessAclUpdateAclRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessAclUpdateAclRequestWithDefaults() *AccessAclUpdateAclRequest {
	this := AccessAclUpdateAclRequest{}




	var propagate PveBoolean = PVEBOOLEAN__1
	this.Propagate = &propagate




	return &this
}


// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *AccessAclUpdateAclRequest) GetDelete() PveBoolean {
	if o == nil || IsNil(o.Delete) {
		var ret PveBoolean
		return ret
	}
	return *o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessAclUpdateAclRequest) GetDeleteOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *AccessAclUpdateAclRequest) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given PveBoolean and assigns it to the Delete field.
func (o *AccessAclUpdateAclRequest) SetDelete(v PveBoolean) {
	o.Delete = &v
}


// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *AccessAclUpdateAclRequest) GetGroups() string {
	if o == nil || IsNil(o.Groups) {
		var ret string
		return ret
	}
	return *o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessAclUpdateAclRequest) GetGroupsOk() (*string, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *AccessAclUpdateAclRequest) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given string and assigns it to the Groups field.
func (o *AccessAclUpdateAclRequest) SetGroups(v string) {
	o.Groups = &v
}


// GetPath returns the Path field value
func (o *AccessAclUpdateAclRequest) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *AccessAclUpdateAclRequest) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *AccessAclUpdateAclRequest) SetPath(v string) {
	o.Path = v
}


// GetPropagate returns the Propagate field value if set, zero value otherwise.
func (o *AccessAclUpdateAclRequest) GetPropagate() PveBoolean {
	if o == nil || IsNil(o.Propagate) {
		var ret PveBoolean
		return ret
	}
	return *o.Propagate
}

// GetPropagateOk returns a tuple with the Propagate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessAclUpdateAclRequest) GetPropagateOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Propagate) {
		return nil, false
	}
	return o.Propagate, true
}

// HasPropagate returns a boolean if a field has been set.
func (o *AccessAclUpdateAclRequest) HasPropagate() bool {
	if o != nil && !IsNil(o.Propagate) {
		return true
	}

	return false
}

// SetPropagate gets a reference to the given PveBoolean and assigns it to the Propagate field.
func (o *AccessAclUpdateAclRequest) SetPropagate(v PveBoolean) {
	o.Propagate = &v
}


// GetRoles returns the Roles field value
func (o *AccessAclUpdateAclRequest) GetRoles() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *AccessAclUpdateAclRequest) GetRolesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Roles, true
}

// SetRoles sets field value
func (o *AccessAclUpdateAclRequest) SetRoles(v string) {
	o.Roles = v
}


// GetTokens returns the Tokens field value if set, zero value otherwise.
func (o *AccessAclUpdateAclRequest) GetTokens() string {
	if o == nil || IsNil(o.Tokens) {
		var ret string
		return ret
	}
	return *o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessAclUpdateAclRequest) GetTokensOk() (*string, bool) {
	if o == nil || IsNil(o.Tokens) {
		return nil, false
	}
	return o.Tokens, true
}

// HasTokens returns a boolean if a field has been set.
func (o *AccessAclUpdateAclRequest) HasTokens() bool {
	if o != nil && !IsNil(o.Tokens) {
		return true
	}

	return false
}

// SetTokens gets a reference to the given string and assigns it to the Tokens field.
func (o *AccessAclUpdateAclRequest) SetTokens(v string) {
	o.Tokens = &v
}


// GetUsers returns the Users field value if set, zero value otherwise.
func (o *AccessAclUpdateAclRequest) GetUsers() string {
	if o == nil || IsNil(o.Users) {
		var ret string
		return ret
	}
	return *o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessAclUpdateAclRequest) GetUsersOk() (*string, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *AccessAclUpdateAclRequest) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given string and assigns it to the Users field.
func (o *AccessAclUpdateAclRequest) SetUsers(v string) {
	o.Users = &v
}


func (o AccessAclUpdateAclRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessAclUpdateAclRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	
	toSerialize["path"] = o.Path
	
	if !IsNil(o.Propagate) {
		toSerialize["propagate"] = o.Propagate
	}
	
	toSerialize["roles"] = o.Roles
	
	if !IsNil(o.Tokens) {
		toSerialize["tokens"] = o.Tokens
	}
	
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	
	return toSerialize, nil
}

func (o *AccessAclUpdateAclRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
		"roles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessAclUpdateAclRequest := _AccessAclUpdateAclRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccessAclUpdateAclRequest)

	if err != nil {
		return err
	}

	*o = AccessAclUpdateAclRequest(varAccessAclUpdateAclRequest)

	return err
}

type NullableAccessAclUpdateAclRequest struct {
	value *AccessAclUpdateAclRequest
	isSet bool
}

func (v NullableAccessAclUpdateAclRequest) Get() *AccessAclUpdateAclRequest {
	return v.value
}

func (v *NullableAccessAclUpdateAclRequest) Set(val *AccessAclUpdateAclRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessAclUpdateAclRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessAclUpdateAclRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessAclUpdateAclRequest(val *AccessAclUpdateAclRequest) *NullableAccessAclUpdateAclRequest {
	return &NullableAccessAclUpdateAclRequest{value: val, isSet: true}
}

func (v NullableAccessAclUpdateAclRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessAclUpdateAclRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


