/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
)

// PvePreallocationEnum the model 'PvePreallocationEnum'
type PvePreallocationEnum string

// List of PvePreallocationEnum
const (
	PVEPREALLOCATIONENUM_OFF PvePreallocationEnum = "off"
	PVEPREALLOCATIONENUM_METADATA PvePreallocationEnum = "metadata"
	PVEPREALLOCATIONENUM_FALLOC PvePreallocationEnum = "falloc"
	PVEPREALLOCATIONENUM_FULL PvePreallocationEnum = "full"
)

// All allowed values of PvePreallocationEnum enum
var AllowedPvePreallocationEnumEnumValues = []PvePreallocationEnum{
	"off",
	"metadata",
	"falloc",
	"full",
}

func (v *PvePreallocationEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PvePreallocationEnum(value)
	for _, existing := range AllowedPvePreallocationEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PvePreallocationEnum", value)
}

// NewPvePreallocationEnumFromValue returns a pointer to a valid PvePreallocationEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPvePreallocationEnumFromValue(v string) (*PvePreallocationEnum, error) {
	ev := PvePreallocationEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PvePreallocationEnum: valid values are %v", v, AllowedPvePreallocationEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PvePreallocationEnum) IsValid() bool {
	for _, existing := range AllowedPvePreallocationEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PvePreallocationEnum value
func (v PvePreallocationEnum) Ptr() *PvePreallocationEnum {
	return &v
}

type NullablePvePreallocationEnum struct {
	value *PvePreallocationEnum
	isSet bool
}

func (v NullablePvePreallocationEnum) Get() *PvePreallocationEnum {
	return v.value
}

func (v *NullablePvePreallocationEnum) Set(val *PvePreallocationEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePvePreallocationEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePvePreallocationEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePvePreallocationEnum(val *PvePreallocationEnum) *NullablePvePreallocationEnum {
	return &NullablePvePreallocationEnum{value: val, isSet: true}
}

func (v NullablePvePreallocationEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePvePreallocationEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

