/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PveNotifyField - struct for PveNotifyField
type PveNotifyField struct {
	PveNotifyConfig *PveNotifyConfig
	String *string
}

// PveNotifyConfigAsPveNotifyField is a convenience function that returns PveNotifyConfig wrapped in PveNotifyField
func PveNotifyConfigAsPveNotifyField(v *PveNotifyConfig) PveNotifyField {
	return PveNotifyField{
		PveNotifyConfig: v,
	}
}

// stringAsPveNotifyField is a convenience function that returns string wrapped in PveNotifyField
func StringAsPveNotifyField(v *string) PveNotifyField {
	return PveNotifyField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PveNotifyField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PveNotifyConfig
	err = newStrictDecoder(data).Decode(&dst.PveNotifyConfig)
	if err == nil {
		jsonPveNotifyConfig, _ := json.Marshal(dst.PveNotifyConfig)
		if string(jsonPveNotifyConfig) == "{}" { // empty struct
			dst.PveNotifyConfig = nil
		} else {
			if err = validator.Validate(dst.PveNotifyConfig); err != nil {
				dst.PveNotifyConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PveNotifyConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PveNotifyConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PveNotifyField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PveNotifyField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PveNotifyField) MarshalJSON() ([]byte, error) {
	if src.PveNotifyConfig != nil {
		return json.Marshal(&src.PveNotifyConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PveNotifyField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PveNotifyConfig != nil {
		return obj.PveNotifyConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PveNotifyField) GetActualInstanceValue() (interface{}) {
	if obj.PveNotifyConfig != nil {
		return *obj.PveNotifyConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePveNotifyField struct {
	value *PveNotifyField
	isSet bool
}

func (v NullablePveNotifyField) Get() *PveNotifyField {
	return v.value
}

func (v *NullablePveNotifyField) Set(val *PveNotifyField) {
	v.value = val
	v.isSet = true
}

func (v NullablePveNotifyField) IsSet() bool {
	return v.isSet
}

func (v *NullablePveNotifyField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveNotifyField(val *PveNotifyField) *NullablePveNotifyField {
	return &NullablePveNotifyField{value: val, isSet: true}
}

func (v NullablePveNotifyField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveNotifyField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


