/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
)

// checks if the PoolsGetPoolsResponseDataInnerMembersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PoolsGetPoolsResponseDataInnerMembersInner{}

// PoolsGetPoolsResponseDataInnerMembersInner struct for PoolsGetPoolsResponseDataInnerMembersInner
type PoolsGetPoolsResponseDataInnerMembersInner struct {

	Id string `json:"id"`

	Node string `json:"node"`

	Storage *string `json:"storage,omitempty"`

	Type PvePoolsTypeTypeEnum `json:"type"`

	Vmid *int64 `json:"vmid,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _PoolsGetPoolsResponseDataInnerMembersInner PoolsGetPoolsResponseDataInnerMembersInner

// NewPoolsGetPoolsResponseDataInnerMembersInner instantiates a new PoolsGetPoolsResponseDataInnerMembersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoolsGetPoolsResponseDataInnerMembersInner(id string, node string, type_ PvePoolsTypeTypeEnum) *PoolsGetPoolsResponseDataInnerMembersInner {
	this := PoolsGetPoolsResponseDataInnerMembersInner{}
	this.Id = id
	this.Node = node
	this.Type = type_
	return &this
}

// NewPoolsGetPoolsResponseDataInnerMembersInnerWithDefaults instantiates a new PoolsGetPoolsResponseDataInnerMembersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoolsGetPoolsResponseDataInnerMembersInnerWithDefaults() *PoolsGetPoolsResponseDataInnerMembersInner {
	this := PoolsGetPoolsResponseDataInnerMembersInner{}






	return &this
}


// GetId returns the Id field value
func (o *PoolsGetPoolsResponseDataInnerMembersInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PoolsGetPoolsResponseDataInnerMembersInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PoolsGetPoolsResponseDataInnerMembersInner) SetId(v string) {
	o.Id = v
}


// GetNode returns the Node field value
func (o *PoolsGetPoolsResponseDataInnerMembersInner) GetNode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Node
}

// GetNodeOk returns a tuple with the Node field value
// and a boolean to check if the value has been set.
func (o *PoolsGetPoolsResponseDataInnerMembersInner) GetNodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Node, true
}

// SetNode sets field value
func (o *PoolsGetPoolsResponseDataInnerMembersInner) SetNode(v string) {
	o.Node = v
}


// GetStorage returns the Storage field value if set, zero value otherwise.
func (o *PoolsGetPoolsResponseDataInnerMembersInner) GetStorage() string {
	if o == nil || IsNil(o.Storage) {
		var ret string
		return ret
	}
	return *o.Storage
}

// GetStorageOk returns a tuple with the Storage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsGetPoolsResponseDataInnerMembersInner) GetStorageOk() (*string, bool) {
	if o == nil || IsNil(o.Storage) {
		return nil, false
	}
	return o.Storage, true
}

// HasStorage returns a boolean if a field has been set.
func (o *PoolsGetPoolsResponseDataInnerMembersInner) HasStorage() bool {
	if o != nil && !IsNil(o.Storage) {
		return true
	}

	return false
}

// SetStorage gets a reference to the given string and assigns it to the Storage field.
func (o *PoolsGetPoolsResponseDataInnerMembersInner) SetStorage(v string) {
	o.Storage = &v
}


// GetType returns the Type field value
func (o *PoolsGetPoolsResponseDataInnerMembersInner) GetType() PvePoolsTypeTypeEnum {
	if o == nil {
		var ret PvePoolsTypeTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PoolsGetPoolsResponseDataInnerMembersInner) GetTypeOk() (*PvePoolsTypeTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PoolsGetPoolsResponseDataInnerMembersInner) SetType(v PvePoolsTypeTypeEnum) {
	o.Type = v
}


// GetVmid returns the Vmid field value if set, zero value otherwise.
func (o *PoolsGetPoolsResponseDataInnerMembersInner) GetVmid() int64 {
	if o == nil || IsNil(o.Vmid) {
		var ret int64
		return ret
	}
	return *o.Vmid
}

// GetVmidOk returns a tuple with the Vmid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsGetPoolsResponseDataInnerMembersInner) GetVmidOk() (*int64, bool) {
	if o == nil || IsNil(o.Vmid) {
		return nil, false
	}
	return o.Vmid, true
}

// HasVmid returns a boolean if a field has been set.
func (o *PoolsGetPoolsResponseDataInnerMembersInner) HasVmid() bool {
	if o != nil && !IsNil(o.Vmid) {
		return true
	}

	return false
}

// SetVmid gets a reference to the given int64 and assigns it to the Vmid field.
func (o *PoolsGetPoolsResponseDataInnerMembersInner) SetVmid(v int64) {
	o.Vmid = &v
}


func (o PoolsGetPoolsResponseDataInnerMembersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PoolsGetPoolsResponseDataInnerMembersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["id"] = o.Id
	
	toSerialize["node"] = o.Node
	
	if !IsNil(o.Storage) {
		toSerialize["storage"] = o.Storage
	}
	
	toSerialize["type"] = o.Type
	
	if !IsNil(o.Vmid) {
		toSerialize["vmid"] = o.Vmid
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PoolsGetPoolsResponseDataInnerMembersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"node",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPoolsGetPoolsResponseDataInnerMembersInner := _PoolsGetPoolsResponseDataInnerMembersInner{}

	err = json.Unmarshal(data, &varPoolsGetPoolsResponseDataInnerMembersInner)

	if err != nil {
		return err
	}

	*o = PoolsGetPoolsResponseDataInnerMembersInner(varPoolsGetPoolsResponseDataInnerMembersInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "node")
		delete(additionalProperties, "storage")
		delete(additionalProperties, "type")
		delete(additionalProperties, "vmid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePoolsGetPoolsResponseDataInnerMembersInner struct {
	value *PoolsGetPoolsResponseDataInnerMembersInner
	isSet bool
}

func (v NullablePoolsGetPoolsResponseDataInnerMembersInner) Get() *PoolsGetPoolsResponseDataInnerMembersInner {
	return v.value
}

func (v *NullablePoolsGetPoolsResponseDataInnerMembersInner) Set(val *PoolsGetPoolsResponseDataInnerMembersInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolsGetPoolsResponseDataInnerMembersInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolsGetPoolsResponseDataInnerMembersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolsGetPoolsResponseDataInnerMembersInner(val *PoolsGetPoolsResponseDataInnerMembersInner) *NullablePoolsGetPoolsResponseDataInnerMembersInner {
	return &NullablePoolsGetPoolsResponseDataInnerMembersInner{value: val, isSet: true}
}

func (v NullablePoolsGetPoolsResponseDataInnerMembersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolsGetPoolsResponseDataInnerMembersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


