/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PveSdnControllerIsisConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PveSdnControllerIsisConfig{}

// PveSdnControllerIsisConfig struct for PveSdnControllerIsisConfig
type PveSdnControllerIsisConfig struct {

	// Name of the IS-IS domain.
	IsisDomain string `json:"isis-domain"`

	// Network Entity title for this node in the IS-IS network.
	IsisNet string `json:"isis-net" validate:"regexp=[a-fA-F0-9]{2}(\\\\.[a-fA-F0-9]{4}){3,9}\\\\.[a-fA-F0-9]{2}"`

	// Comma-separated list of interfaces where IS-IS should be active.
	IsisIfaces string `json:"isis-ifaces"`

	// The cluster node name.
	Node string `json:"node" validate:"regexp=^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\\\-]*[a-zA-Z0-9])?)$"`

	// Name of the loopback/dummy interface that provides the Router-IP.
	Loopback *string `json:"loopback,omitempty"`

	Type string `json:"type"`

}

type _PveSdnControllerIsisConfig PveSdnControllerIsisConfig

// NewPveSdnControllerIsisConfig instantiates a new PveSdnControllerIsisConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPveSdnControllerIsisConfig(isisDomain string, isisNet string, isisIfaces string, node string, type_ string) *PveSdnControllerIsisConfig {
	this := PveSdnControllerIsisConfig{}
	this.IsisDomain = isisDomain
	this.IsisNet = isisNet
	this.IsisIfaces = isisIfaces
	this.Node = node
	this.Type = type_
	return &this
}

// NewPveSdnControllerIsisConfigWithDefaults instantiates a new PveSdnControllerIsisConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPveSdnControllerIsisConfigWithDefaults() *PveSdnControllerIsisConfig {
	this := PveSdnControllerIsisConfig{}







	return &this
}


// GetIsisDomain returns the IsisDomain field value
func (o *PveSdnControllerIsisConfig) GetIsisDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IsisDomain
}

// GetIsisDomainOk returns a tuple with the IsisDomain field value
// and a boolean to check if the value has been set.
func (o *PveSdnControllerIsisConfig) GetIsisDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsisDomain, true
}

// SetIsisDomain sets field value
func (o *PveSdnControllerIsisConfig) SetIsisDomain(v string) {
	o.IsisDomain = v
}


// GetIsisNet returns the IsisNet field value
func (o *PveSdnControllerIsisConfig) GetIsisNet() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IsisNet
}

// GetIsisNetOk returns a tuple with the IsisNet field value
// and a boolean to check if the value has been set.
func (o *PveSdnControllerIsisConfig) GetIsisNetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsisNet, true
}

// SetIsisNet sets field value
func (o *PveSdnControllerIsisConfig) SetIsisNet(v string) {
	o.IsisNet = v
}


// GetIsisIfaces returns the IsisIfaces field value
func (o *PveSdnControllerIsisConfig) GetIsisIfaces() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IsisIfaces
}

// GetIsisIfacesOk returns a tuple with the IsisIfaces field value
// and a boolean to check if the value has been set.
func (o *PveSdnControllerIsisConfig) GetIsisIfacesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsisIfaces, true
}

// SetIsisIfaces sets field value
func (o *PveSdnControllerIsisConfig) SetIsisIfaces(v string) {
	o.IsisIfaces = v
}


// GetNode returns the Node field value
func (o *PveSdnControllerIsisConfig) GetNode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Node
}

// GetNodeOk returns a tuple with the Node field value
// and a boolean to check if the value has been set.
func (o *PveSdnControllerIsisConfig) GetNodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Node, true
}

// SetNode sets field value
func (o *PveSdnControllerIsisConfig) SetNode(v string) {
	o.Node = v
}


// GetLoopback returns the Loopback field value if set, zero value otherwise.
func (o *PveSdnControllerIsisConfig) GetLoopback() string {
	if o == nil || IsNil(o.Loopback) {
		var ret string
		return ret
	}
	return *o.Loopback
}

// GetLoopbackOk returns a tuple with the Loopback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveSdnControllerIsisConfig) GetLoopbackOk() (*string, bool) {
	if o == nil || IsNil(o.Loopback) {
		return nil, false
	}
	return o.Loopback, true
}

// HasLoopback returns a boolean if a field has been set.
func (o *PveSdnControllerIsisConfig) HasLoopback() bool {
	if o != nil && !IsNil(o.Loopback) {
		return true
	}

	return false
}

// SetLoopback gets a reference to the given string and assigns it to the Loopback field.
func (o *PveSdnControllerIsisConfig) SetLoopback(v string) {
	o.Loopback = &v
}


// GetType returns the Type field value
func (o *PveSdnControllerIsisConfig) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PveSdnControllerIsisConfig) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PveSdnControllerIsisConfig) SetType(v string) {
	o.Type = v
}


func (o PveSdnControllerIsisConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PveSdnControllerIsisConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["isis-domain"] = o.IsisDomain
	
	toSerialize["isis-net"] = o.IsisNet
	
	toSerialize["isis-ifaces"] = o.IsisIfaces
	
	toSerialize["node"] = o.Node
	
	if !IsNil(o.Loopback) {
		toSerialize["loopback"] = o.Loopback
	}
	
	toSerialize["type"] = o.Type
	
	return toSerialize, nil
}

func (o *PveSdnControllerIsisConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isis-domain",
		"isis-net",
		"isis-ifaces",
		"node",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPveSdnControllerIsisConfig := _PveSdnControllerIsisConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPveSdnControllerIsisConfig)

	if err != nil {
		return err
	}

	*o = PveSdnControllerIsisConfig(varPveSdnControllerIsisConfig)

	return err
}

type NullablePveSdnControllerIsisConfig struct {
	value *PveSdnControllerIsisConfig
	isSet bool
}

func (v NullablePveSdnControllerIsisConfig) Get() *PveSdnControllerIsisConfig {
	return v.value
}

func (v *NullablePveSdnControllerIsisConfig) Set(val *PveSdnControllerIsisConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePveSdnControllerIsisConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePveSdnControllerIsisConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveSdnControllerIsisConfig(val *PveSdnControllerIsisConfig) *NullablePveSdnControllerIsisConfig {
	return &NullablePveSdnControllerIsisConfig{value: val, isSet: true}
}

func (v NullablePveSdnControllerIsisConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveSdnControllerIsisConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


