/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
)

// checks if the PveFeaturesConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PveFeaturesConfig{}

// PveFeaturesConfig struct for PveFeaturesConfig
type PveFeaturesConfig struct {

	// Mount /sys in unprivileged containers as `rw` instead of `mixed`. This can break networking under newer (>= v245) systemd-network use.
	ForceRwSys *PveBoolean `json:"force_rw_sys,omitempty"`

	// Allow using 'fuse' file systems in a container. Note that interactions between fuse and the freezer cgroup can potentially cause I/O deadlocks.
	Fuse *PveBoolean `json:"fuse,omitempty"`

	// For unprivileged containers only: Allow the use of the keyctl() system call. This is required to use docker inside a container. By default unprivileged containers will see this system call as non-existent. This is mostly a workaround for systemd-networkd, as it will treat it as a fatal error when some keyctl() operations are denied by the kernel due to lacking permissions. Essentially, you can choose between running systemd-networkd or docker.
	Keyctl *PveBoolean `json:"keyctl,omitempty"`

	// Allow unprivileged containers to use mknod() to add certain device nodes. This requires a kernel with seccomp trap to user space support (5.3 or newer). This is experimental.
	Mknod *PveBoolean `json:"mknod,omitempty"`

	// Allow mounting file systems of specific types. This should be a list of file system types as used with the mount command. Note that this can have negative effects on the container's security. With access to a loop device, mounting a file can circumvent the mknod permission of the devices cgroup, mounting an NFS file system can block the host's I/O completely and prevent it from rebooting, etc.
	Mount *string `json:"mount,omitempty" validate:"regexp=(?:[a-zA-Z0-9_; ]+)"`

	// Allow nesting. Best used with unprivileged containers with additional id mapping. Note that this will expose procfs and sysfs contents of the host to the guest. This is also required by systemd to isolate services.
	Nesting *PveBoolean `json:"nesting,omitempty"`

}

// NewPveFeaturesConfig instantiates a new PveFeaturesConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPveFeaturesConfig() *PveFeaturesConfig {
	this := PveFeaturesConfig{}
	var forceRwSys PveBoolean = PVEBOOLEAN__0
	this.ForceRwSys = &forceRwSys
	var fuse PveBoolean = PVEBOOLEAN__0
	this.Fuse = &fuse
	var keyctl PveBoolean = PVEBOOLEAN__0
	this.Keyctl = &keyctl
	var mknod PveBoolean = PVEBOOLEAN__0
	this.Mknod = &mknod
	var nesting PveBoolean = PVEBOOLEAN__0
	this.Nesting = &nesting
	return &this
}

// NewPveFeaturesConfigWithDefaults instantiates a new PveFeaturesConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPveFeaturesConfigWithDefaults() *PveFeaturesConfig {
	this := PveFeaturesConfig{}

	var forceRwSys PveBoolean = PVEBOOLEAN__0
	this.ForceRwSys = &forceRwSys

	var fuse PveBoolean = PVEBOOLEAN__0
	this.Fuse = &fuse

	var keyctl PveBoolean = PVEBOOLEAN__0
	this.Keyctl = &keyctl

	var mknod PveBoolean = PVEBOOLEAN__0
	this.Mknod = &mknod


	var nesting PveBoolean = PVEBOOLEAN__0
	this.Nesting = &nesting

	return &this
}


// GetForceRwSys returns the ForceRwSys field value if set, zero value otherwise.
func (o *PveFeaturesConfig) GetForceRwSys() PveBoolean {
	if o == nil || IsNil(o.ForceRwSys) {
		var ret PveBoolean
		return ret
	}
	return *o.ForceRwSys
}

// GetForceRwSysOk returns a tuple with the ForceRwSys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveFeaturesConfig) GetForceRwSysOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.ForceRwSys) {
		return nil, false
	}
	return o.ForceRwSys, true
}

// HasForceRwSys returns a boolean if a field has been set.
func (o *PveFeaturesConfig) HasForceRwSys() bool {
	if o != nil && !IsNil(o.ForceRwSys) {
		return true
	}

	return false
}

// SetForceRwSys gets a reference to the given PveBoolean and assigns it to the ForceRwSys field.
func (o *PveFeaturesConfig) SetForceRwSys(v PveBoolean) {
	o.ForceRwSys = &v
}


// GetFuse returns the Fuse field value if set, zero value otherwise.
func (o *PveFeaturesConfig) GetFuse() PveBoolean {
	if o == nil || IsNil(o.Fuse) {
		var ret PveBoolean
		return ret
	}
	return *o.Fuse
}

// GetFuseOk returns a tuple with the Fuse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveFeaturesConfig) GetFuseOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Fuse) {
		return nil, false
	}
	return o.Fuse, true
}

// HasFuse returns a boolean if a field has been set.
func (o *PveFeaturesConfig) HasFuse() bool {
	if o != nil && !IsNil(o.Fuse) {
		return true
	}

	return false
}

// SetFuse gets a reference to the given PveBoolean and assigns it to the Fuse field.
func (o *PveFeaturesConfig) SetFuse(v PveBoolean) {
	o.Fuse = &v
}


// GetKeyctl returns the Keyctl field value if set, zero value otherwise.
func (o *PveFeaturesConfig) GetKeyctl() PveBoolean {
	if o == nil || IsNil(o.Keyctl) {
		var ret PveBoolean
		return ret
	}
	return *o.Keyctl
}

// GetKeyctlOk returns a tuple with the Keyctl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveFeaturesConfig) GetKeyctlOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Keyctl) {
		return nil, false
	}
	return o.Keyctl, true
}

// HasKeyctl returns a boolean if a field has been set.
func (o *PveFeaturesConfig) HasKeyctl() bool {
	if o != nil && !IsNil(o.Keyctl) {
		return true
	}

	return false
}

// SetKeyctl gets a reference to the given PveBoolean and assigns it to the Keyctl field.
func (o *PveFeaturesConfig) SetKeyctl(v PveBoolean) {
	o.Keyctl = &v
}


// GetMknod returns the Mknod field value if set, zero value otherwise.
func (o *PveFeaturesConfig) GetMknod() PveBoolean {
	if o == nil || IsNil(o.Mknod) {
		var ret PveBoolean
		return ret
	}
	return *o.Mknod
}

// GetMknodOk returns a tuple with the Mknod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveFeaturesConfig) GetMknodOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Mknod) {
		return nil, false
	}
	return o.Mknod, true
}

// HasMknod returns a boolean if a field has been set.
func (o *PveFeaturesConfig) HasMknod() bool {
	if o != nil && !IsNil(o.Mknod) {
		return true
	}

	return false
}

// SetMknod gets a reference to the given PveBoolean and assigns it to the Mknod field.
func (o *PveFeaturesConfig) SetMknod(v PveBoolean) {
	o.Mknod = &v
}


// GetMount returns the Mount field value if set, zero value otherwise.
func (o *PveFeaturesConfig) GetMount() string {
	if o == nil || IsNil(o.Mount) {
		var ret string
		return ret
	}
	return *o.Mount
}

// GetMountOk returns a tuple with the Mount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveFeaturesConfig) GetMountOk() (*string, bool) {
	if o == nil || IsNil(o.Mount) {
		return nil, false
	}
	return o.Mount, true
}

// HasMount returns a boolean if a field has been set.
func (o *PveFeaturesConfig) HasMount() bool {
	if o != nil && !IsNil(o.Mount) {
		return true
	}

	return false
}

// SetMount gets a reference to the given string and assigns it to the Mount field.
func (o *PveFeaturesConfig) SetMount(v string) {
	o.Mount = &v
}


// GetNesting returns the Nesting field value if set, zero value otherwise.
func (o *PveFeaturesConfig) GetNesting() PveBoolean {
	if o == nil || IsNil(o.Nesting) {
		var ret PveBoolean
		return ret
	}
	return *o.Nesting
}

// GetNestingOk returns a tuple with the Nesting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PveFeaturesConfig) GetNestingOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Nesting) {
		return nil, false
	}
	return o.Nesting, true
}

// HasNesting returns a boolean if a field has been set.
func (o *PveFeaturesConfig) HasNesting() bool {
	if o != nil && !IsNil(o.Nesting) {
		return true
	}

	return false
}

// SetNesting gets a reference to the given PveBoolean and assigns it to the Nesting field.
func (o *PveFeaturesConfig) SetNesting(v PveBoolean) {
	o.Nesting = &v
}


func (o PveFeaturesConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PveFeaturesConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.ForceRwSys) {
		toSerialize["force_rw_sys"] = o.ForceRwSys
	}
	
	if !IsNil(o.Fuse) {
		toSerialize["fuse"] = o.Fuse
	}
	
	if !IsNil(o.Keyctl) {
		toSerialize["keyctl"] = o.Keyctl
	}
	
	if !IsNil(o.Mknod) {
		toSerialize["mknod"] = o.Mknod
	}
	
	if !IsNil(o.Mount) {
		toSerialize["mount"] = o.Mount
	}
	
	if !IsNil(o.Nesting) {
		toSerialize["nesting"] = o.Nesting
	}
	
	return toSerialize, nil
}

type NullablePveFeaturesConfig struct {
	value *PveFeaturesConfig
	isSet bool
}

func (v NullablePveFeaturesConfig) Get() *PveFeaturesConfig {
	return v.value
}

func (v *NullablePveFeaturesConfig) Set(val *PveFeaturesConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePveFeaturesConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePveFeaturesConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveFeaturesConfig(val *PveFeaturesConfig) *NullablePveFeaturesConfig {
	return &NullablePveFeaturesConfig{value: val, isSet: true}
}

func (v NullablePveFeaturesConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveFeaturesConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


// pveShorthandValue converts a value into the unquoted form expected
// by Proxmox's `key=value,…` CLI shorthand. Uses encoding/json (already
// imported) to avoid pulling in fmt in models that don't otherwise need
// it, then strips the surrounding quotes for strings.
func PveFeaturesConfig_pveShorthandValue(v interface{}) string {
	if v == nil {
		return ""
	}
	b, err := json.Marshal(v)
	if err != nil {
		return ""
	}
	s := string(b)
	if n := len(s); n >= 2 && s[0] == '"' && s[n-1] == '"' {
		return s[1 : n-1]
	}
	return s
}

// ToShorthand serialises the PveFeaturesConfig into Proxmox's CLI-style
// shorthand string (`key=value,…`). The property marked
// `x-pve-default-key` is emitted positionally without a `key=` prefix;
// aliases collapse multiple property names to the same wire key.
//
// Example: {Model: "virtio", Bridge: "vmbr0", Firewall: 1}
//       => "virtio,bridge=vmbr0,firewall=1"
func (o *PveFeaturesConfig) ToShorthand() string {
	if o == nil {
		return ""
	}
	var result string
	sep := ""
	
	
	if o.ForceRwSys != nil {
		result += sep + "force_rw_sys=" + PveFeaturesConfig_pveShorthandValue(*o.ForceRwSys)
		sep = ","
	}
	
	if o.Fuse != nil {
		result += sep + "fuse=" + PveFeaturesConfig_pveShorthandValue(*o.Fuse)
		sep = ","
	}
	
	if o.Keyctl != nil {
		result += sep + "keyctl=" + PveFeaturesConfig_pveShorthandValue(*o.Keyctl)
		sep = ","
	}
	
	if o.Mknod != nil {
		result += sep + "mknod=" + PveFeaturesConfig_pveShorthandValue(*o.Mknod)
		sep = ","
	}
	
	if o.Mount != nil {
		result += sep + "mount=" + PveFeaturesConfig_pveShorthandValue(*o.Mount)
		sep = ","
	}
	
	if o.Nesting != nil {
		result += sep + "nesting=" + PveFeaturesConfig_pveShorthandValue(*o.Nesting)
		sep = ","
	}
	
	return result
}

