/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesScanIscsiscanResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesScanIscsiscanResponseDataInner{}

// NodesScanIscsiscanResponseDataInner struct for NodesScanIscsiscanResponseDataInner
type NodesScanIscsiscanResponseDataInner struct {

	// The iSCSI portal name.
	Portal string `json:"portal"`

	// The iSCSI target name.
	Target string `json:"target"`

	AdditionalProperties map[string]interface{}
}

type _NodesScanIscsiscanResponseDataInner NodesScanIscsiscanResponseDataInner

// NewNodesScanIscsiscanResponseDataInner instantiates a new NodesScanIscsiscanResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesScanIscsiscanResponseDataInner(portal string, target string) *NodesScanIscsiscanResponseDataInner {
	this := NodesScanIscsiscanResponseDataInner{}
	this.Portal = portal
	this.Target = target
	return &this
}

// NewNodesScanIscsiscanResponseDataInnerWithDefaults instantiates a new NodesScanIscsiscanResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesScanIscsiscanResponseDataInnerWithDefaults() *NodesScanIscsiscanResponseDataInner {
	this := NodesScanIscsiscanResponseDataInner{}



	return &this
}


// GetPortal returns the Portal field value
func (o *NodesScanIscsiscanResponseDataInner) GetPortal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Portal
}

// GetPortalOk returns a tuple with the Portal field value
// and a boolean to check if the value has been set.
func (o *NodesScanIscsiscanResponseDataInner) GetPortalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Portal, true
}

// SetPortal sets field value
func (o *NodesScanIscsiscanResponseDataInner) SetPortal(v string) {
	o.Portal = v
}


// GetTarget returns the Target field value
func (o *NodesScanIscsiscanResponseDataInner) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *NodesScanIscsiscanResponseDataInner) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *NodesScanIscsiscanResponseDataInner) SetTarget(v string) {
	o.Target = v
}


func (o NodesScanIscsiscanResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesScanIscsiscanResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["portal"] = o.Portal
	
	toSerialize["target"] = o.Target
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesScanIscsiscanResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"portal",
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesScanIscsiscanResponseDataInner := _NodesScanIscsiscanResponseDataInner{}

	err = json.Unmarshal(data, &varNodesScanIscsiscanResponseDataInner)

	if err != nil {
		return err
	}

	*o = NodesScanIscsiscanResponseDataInner(varNodesScanIscsiscanResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "portal")
		delete(additionalProperties, "target")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesScanIscsiscanResponseDataInner struct {
	value *NodesScanIscsiscanResponseDataInner
	isSet bool
}

func (v NullableNodesScanIscsiscanResponseDataInner) Get() *NodesScanIscsiscanResponseDataInner {
	return v.value
}

func (v *NullableNodesScanIscsiscanResponseDataInner) Set(val *NodesScanIscsiscanResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesScanIscsiscanResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesScanIscsiscanResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesScanIscsiscanResponseDataInner(val *NodesScanIscsiscanResponseDataInner) *NullableNodesScanIscsiscanResponseDataInner {
	return &NullableNodesScanIscsiscanResponseDataInner{value: val, isSet: true}
}

func (v NullableNodesScanIscsiscanResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesScanIscsiscanResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


