/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PvePolicyForwardEnum the model 'PvePolicyForwardEnum'
type PvePolicyForwardEnum string

// List of PvePolicyForwardEnum
const (
	PVEPOLICYFORWARDENUM_ACCEPT PvePolicyForwardEnum = "ACCEPT"
	PVEPOLICYFORWARDENUM_DROP PvePolicyForwardEnum = "DROP"
)

// All allowed values of PvePolicyForwardEnum enum
var AllowedPvePolicyForwardEnumEnumValues = []PvePolicyForwardEnum{
	"ACCEPT",
	"DROP",
}

func (v *PvePolicyForwardEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PvePolicyForwardEnum(value)
	for _, existing := range AllowedPvePolicyForwardEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PvePolicyForwardEnum", value)
}

// NewPvePolicyForwardEnumFromValue returns a pointer to a valid PvePolicyForwardEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPvePolicyForwardEnumFromValue(v string) (*PvePolicyForwardEnum, error) {
	ev := PvePolicyForwardEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PvePolicyForwardEnum: valid values are %v", v, AllowedPvePolicyForwardEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PvePolicyForwardEnum) IsValid() bool {
	for _, existing := range AllowedPvePolicyForwardEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PvePolicyForwardEnum value
func (v PvePolicyForwardEnum) Ptr() *PvePolicyForwardEnum {
	return &v
}

type NullablePvePolicyForwardEnum struct {
	value *PvePolicyForwardEnum
	isSet bool
}

func (v NullablePvePolicyForwardEnum) Get() *PvePolicyForwardEnum {
	return v.value
}

func (v *NullablePvePolicyForwardEnum) Set(val *PvePolicyForwardEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePvePolicyForwardEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePvePolicyForwardEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePvePolicyForwardEnum(val *PvePolicyForwardEnum) *NullablePvePolicyForwardEnum {
	return &NullablePvePolicyForwardEnum{value: val, isSet: true}
}

func (v NullablePvePolicyForwardEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePvePolicyForwardEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

