/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PveClipboardEnum the model 'PveClipboardEnum'
type PveClipboardEnum string

// List of PveClipboardEnum
const (
	PVECLIPBOARDENUM_VNC PveClipboardEnum = "vnc"
)

// All allowed values of PveClipboardEnum enum
var AllowedPveClipboardEnumEnumValues = []PveClipboardEnum{
	"vnc",
}

func (v *PveClipboardEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PveClipboardEnum(value)
	for _, existing := range AllowedPveClipboardEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PveClipboardEnum", value)
}

// NewPveClipboardEnumFromValue returns a pointer to a valid PveClipboardEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPveClipboardEnumFromValue(v string) (*PveClipboardEnum, error) {
	ev := PveClipboardEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PveClipboardEnum: valid values are %v", v, AllowedPveClipboardEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PveClipboardEnum) IsValid() bool {
	for _, existing := range AllowedPveClipboardEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PveClipboardEnum value
func (v PveClipboardEnum) Ptr() *PveClipboardEnum {
	return &v
}

type NullablePveClipboardEnum struct {
	value *PveClipboardEnum
	isSet bool
}

func (v NullablePveClipboardEnum) Get() *PveClipboardEnum {
	return v.value
}

func (v *NullablePveClipboardEnum) Set(val *PveClipboardEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePveClipboardEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePveClipboardEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveClipboardEnum(val *PveClipboardEnum) *NullablePveClipboardEnum {
	return &NullablePveClipboardEnum{value: val, isSet: true}
}

func (v NullablePveClipboardEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveClipboardEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

