/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PoolsCreatePoolRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PoolsCreatePoolRequest{}

// PoolsCreatePoolRequest struct for PoolsCreatePoolRequest
type PoolsCreatePoolRequest struct {

	Comment *string `json:"comment,omitempty"`

	Poolid string `json:"poolid" validate:"regexp=^[A-Za-z0-9.\\\\-_]+$"`

}

type _PoolsCreatePoolRequest PoolsCreatePoolRequest

// NewPoolsCreatePoolRequest instantiates a new PoolsCreatePoolRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoolsCreatePoolRequest(poolid string) *PoolsCreatePoolRequest {
	this := PoolsCreatePoolRequest{}
	this.Poolid = poolid
	return &this
}

// NewPoolsCreatePoolRequestWithDefaults instantiates a new PoolsCreatePoolRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoolsCreatePoolRequestWithDefaults() *PoolsCreatePoolRequest {
	this := PoolsCreatePoolRequest{}



	return &this
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *PoolsCreatePoolRequest) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsCreatePoolRequest) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *PoolsCreatePoolRequest) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *PoolsCreatePoolRequest) SetComment(v string) {
	o.Comment = &v
}


// GetPoolid returns the Poolid field value
func (o *PoolsCreatePoolRequest) GetPoolid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Poolid
}

// GetPoolidOk returns a tuple with the Poolid field value
// and a boolean to check if the value has been set.
func (o *PoolsCreatePoolRequest) GetPoolidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Poolid, true
}

// SetPoolid sets field value
func (o *PoolsCreatePoolRequest) SetPoolid(v string) {
	o.Poolid = v
}


func (o PoolsCreatePoolRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PoolsCreatePoolRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	toSerialize["poolid"] = o.Poolid
	
	return toSerialize, nil
}

func (o *PoolsCreatePoolRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"poolid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPoolsCreatePoolRequest := _PoolsCreatePoolRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPoolsCreatePoolRequest)

	if err != nil {
		return err
	}

	*o = PoolsCreatePoolRequest(varPoolsCreatePoolRequest)

	return err
}

type NullablePoolsCreatePoolRequest struct {
	value *PoolsCreatePoolRequest
	isSet bool
}

func (v NullablePoolsCreatePoolRequest) Get() *PoolsCreatePoolRequest {
	return v.value
}

func (v *NullablePoolsCreatePoolRequest) Set(val *PoolsCreatePoolRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolsCreatePoolRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolsCreatePoolRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolsCreatePoolRequest(val *PoolsCreatePoolRequest) *NullablePoolsCreatePoolRequest {
	return &NullablePoolsCreatePoolRequest{value: val, isSet: true}
}

func (v NullablePoolsCreatePoolRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolsCreatePoolRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


