/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LxcRemoteMigrateVmRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LxcRemoteMigrateVmRequest{}

// LxcRemoteMigrateVmRequest struct for LxcRemoteMigrateVmRequest
type LxcRemoteMigrateVmRequest struct {

	// Override I/O bandwidth limit (in KiB/s).
	Bwlimit *float32 `json:"bwlimit,omitempty"`

	// Delete the original CT and related data after successful migration. By default the original CT is kept on the source cluster in a stopped state.
	Delete *PveBoolean `json:"delete,omitempty"`

	// Use online/live migration.
	Online *PveBoolean `json:"online,omitempty"`

	// Use restart migration
	Restart *PveBoolean `json:"restart,omitempty"`

	// Mapping from source to target bridges. Providing only a single bridge ID maps all source bridges to that bridge. Providing the special value '1' will map each source bridge to itself.
	TargetBridge string `json:"target-bridge"`

	// Remote target endpoint
	TargetEndpoint string `json:"target-endpoint"`

	// Mapping from source to target storages. Providing only a single storage ID maps all source storages to that storage. Providing the special value '1' will map each source storage to itself.
	TargetStorage string `json:"target-storage"`

	// The (unique) ID of the VM.
	TargetVmid *int32 `json:"target-vmid,omitempty"`

	// Timeout in seconds for shutdown for restart migration
	Timeout *int64 `json:"timeout,omitempty"`

}

type _LxcRemoteMigrateVmRequest LxcRemoteMigrateVmRequest

// NewLxcRemoteMigrateVmRequest instantiates a new LxcRemoteMigrateVmRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLxcRemoteMigrateVmRequest(targetBridge string, targetEndpoint string, targetStorage string) *LxcRemoteMigrateVmRequest {
	this := LxcRemoteMigrateVmRequest{}
	var delete PveBoolean = PVEBOOLEAN__0
	this.Delete = &delete
	this.TargetBridge = targetBridge
	this.TargetEndpoint = targetEndpoint
	this.TargetStorage = targetStorage
	var timeout int64 = 180
	this.Timeout = &timeout
	return &this
}

// NewLxcRemoteMigrateVmRequestWithDefaults instantiates a new LxcRemoteMigrateVmRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLxcRemoteMigrateVmRequestWithDefaults() *LxcRemoteMigrateVmRequest {
	this := LxcRemoteMigrateVmRequest{}


	var delete PveBoolean = PVEBOOLEAN__0
	this.Delete = &delete







	var timeout int64 = 180
	this.Timeout = &timeout

	return &this
}


// GetBwlimit returns the Bwlimit field value if set, zero value otherwise.
func (o *LxcRemoteMigrateVmRequest) GetBwlimit() float32 {
	if o == nil || IsNil(o.Bwlimit) {
		var ret float32
		return ret
	}
	return *o.Bwlimit
}

// GetBwlimitOk returns a tuple with the Bwlimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LxcRemoteMigrateVmRequest) GetBwlimitOk() (*float32, bool) {
	if o == nil || IsNil(o.Bwlimit) {
		return nil, false
	}
	return o.Bwlimit, true
}

// HasBwlimit returns a boolean if a field has been set.
func (o *LxcRemoteMigrateVmRequest) HasBwlimit() bool {
	if o != nil && !IsNil(o.Bwlimit) {
		return true
	}

	return false
}

// SetBwlimit gets a reference to the given float32 and assigns it to the Bwlimit field.
func (o *LxcRemoteMigrateVmRequest) SetBwlimit(v float32) {
	o.Bwlimit = &v
}


// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *LxcRemoteMigrateVmRequest) GetDelete() PveBoolean {
	if o == nil || IsNil(o.Delete) {
		var ret PveBoolean
		return ret
	}
	return *o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LxcRemoteMigrateVmRequest) GetDeleteOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *LxcRemoteMigrateVmRequest) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given PveBoolean and assigns it to the Delete field.
func (o *LxcRemoteMigrateVmRequest) SetDelete(v PveBoolean) {
	o.Delete = &v
}


// GetOnline returns the Online field value if set, zero value otherwise.
func (o *LxcRemoteMigrateVmRequest) GetOnline() PveBoolean {
	if o == nil || IsNil(o.Online) {
		var ret PveBoolean
		return ret
	}
	return *o.Online
}

// GetOnlineOk returns a tuple with the Online field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LxcRemoteMigrateVmRequest) GetOnlineOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Online) {
		return nil, false
	}
	return o.Online, true
}

// HasOnline returns a boolean if a field has been set.
func (o *LxcRemoteMigrateVmRequest) HasOnline() bool {
	if o != nil && !IsNil(o.Online) {
		return true
	}

	return false
}

// SetOnline gets a reference to the given PveBoolean and assigns it to the Online field.
func (o *LxcRemoteMigrateVmRequest) SetOnline(v PveBoolean) {
	o.Online = &v
}


// GetRestart returns the Restart field value if set, zero value otherwise.
func (o *LxcRemoteMigrateVmRequest) GetRestart() PveBoolean {
	if o == nil || IsNil(o.Restart) {
		var ret PveBoolean
		return ret
	}
	return *o.Restart
}

// GetRestartOk returns a tuple with the Restart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LxcRemoteMigrateVmRequest) GetRestartOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Restart) {
		return nil, false
	}
	return o.Restart, true
}

// HasRestart returns a boolean if a field has been set.
func (o *LxcRemoteMigrateVmRequest) HasRestart() bool {
	if o != nil && !IsNil(o.Restart) {
		return true
	}

	return false
}

// SetRestart gets a reference to the given PveBoolean and assigns it to the Restart field.
func (o *LxcRemoteMigrateVmRequest) SetRestart(v PveBoolean) {
	o.Restart = &v
}


// GetTargetBridge returns the TargetBridge field value
func (o *LxcRemoteMigrateVmRequest) GetTargetBridge() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetBridge
}

// GetTargetBridgeOk returns a tuple with the TargetBridge field value
// and a boolean to check if the value has been set.
func (o *LxcRemoteMigrateVmRequest) GetTargetBridgeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetBridge, true
}

// SetTargetBridge sets field value
func (o *LxcRemoteMigrateVmRequest) SetTargetBridge(v string) {
	o.TargetBridge = v
}


// GetTargetEndpoint returns the TargetEndpoint field value
func (o *LxcRemoteMigrateVmRequest) GetTargetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetEndpoint
}

// GetTargetEndpointOk returns a tuple with the TargetEndpoint field value
// and a boolean to check if the value has been set.
func (o *LxcRemoteMigrateVmRequest) GetTargetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetEndpoint, true
}

// SetTargetEndpoint sets field value
func (o *LxcRemoteMigrateVmRequest) SetTargetEndpoint(v string) {
	o.TargetEndpoint = v
}


// GetTargetStorage returns the TargetStorage field value
func (o *LxcRemoteMigrateVmRequest) GetTargetStorage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetStorage
}

// GetTargetStorageOk returns a tuple with the TargetStorage field value
// and a boolean to check if the value has been set.
func (o *LxcRemoteMigrateVmRequest) GetTargetStorageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetStorage, true
}

// SetTargetStorage sets field value
func (o *LxcRemoteMigrateVmRequest) SetTargetStorage(v string) {
	o.TargetStorage = v
}


// GetTargetVmid returns the TargetVmid field value if set, zero value otherwise.
func (o *LxcRemoteMigrateVmRequest) GetTargetVmid() int32 {
	if o == nil || IsNil(o.TargetVmid) {
		var ret int32
		return ret
	}
	return *o.TargetVmid
}

// GetTargetVmidOk returns a tuple with the TargetVmid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LxcRemoteMigrateVmRequest) GetTargetVmidOk() (*int32, bool) {
	if o == nil || IsNil(o.TargetVmid) {
		return nil, false
	}
	return o.TargetVmid, true
}

// HasTargetVmid returns a boolean if a field has been set.
func (o *LxcRemoteMigrateVmRequest) HasTargetVmid() bool {
	if o != nil && !IsNil(o.TargetVmid) {
		return true
	}

	return false
}

// SetTargetVmid gets a reference to the given int32 and assigns it to the TargetVmid field.
func (o *LxcRemoteMigrateVmRequest) SetTargetVmid(v int32) {
	o.TargetVmid = &v
}


// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *LxcRemoteMigrateVmRequest) GetTimeout() int64 {
	if o == nil || IsNil(o.Timeout) {
		var ret int64
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LxcRemoteMigrateVmRequest) GetTimeoutOk() (*int64, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *LxcRemoteMigrateVmRequest) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int64 and assigns it to the Timeout field.
func (o *LxcRemoteMigrateVmRequest) SetTimeout(v int64) {
	o.Timeout = &v
}


func (o LxcRemoteMigrateVmRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LxcRemoteMigrateVmRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Bwlimit) {
		toSerialize["bwlimit"] = o.Bwlimit
	}
	
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	
	if !IsNil(o.Online) {
		toSerialize["online"] = o.Online
	}
	
	if !IsNil(o.Restart) {
		toSerialize["restart"] = o.Restart
	}
	
	toSerialize["target-bridge"] = o.TargetBridge
	
	toSerialize["target-endpoint"] = o.TargetEndpoint
	
	toSerialize["target-storage"] = o.TargetStorage
	
	if !IsNil(o.TargetVmid) {
		toSerialize["target-vmid"] = o.TargetVmid
	}
	
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	
	return toSerialize, nil
}

func (o *LxcRemoteMigrateVmRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target-bridge",
		"target-endpoint",
		"target-storage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLxcRemoteMigrateVmRequest := _LxcRemoteMigrateVmRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLxcRemoteMigrateVmRequest)

	if err != nil {
		return err
	}

	*o = LxcRemoteMigrateVmRequest(varLxcRemoteMigrateVmRequest)

	return err
}

type NullableLxcRemoteMigrateVmRequest struct {
	value *LxcRemoteMigrateVmRequest
	isSet bool
}

func (v NullableLxcRemoteMigrateVmRequest) Get() *LxcRemoteMigrateVmRequest {
	return v.value
}

func (v *NullableLxcRemoteMigrateVmRequest) Set(val *LxcRemoteMigrateVmRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLxcRemoteMigrateVmRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLxcRemoteMigrateVmRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLxcRemoteMigrateVmRequest(val *LxcRemoteMigrateVmRequest) *NullableLxcRemoteMigrateVmRequest {
	return &NullableLxcRemoteMigrateVmRequest{value: val, isSet: true}
}

func (v NullableLxcRemoteMigrateVmRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLxcRemoteMigrateVmRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


