/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesCapabilitiesGetCpuFlagsResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesCapabilitiesGetCpuFlagsResponseDataInner{}

// NodesCapabilitiesGetCpuFlagsResponseDataInner struct for NodesCapabilitiesGetCpuFlagsResponseDataInner
type NodesCapabilitiesGetCpuFlagsResponseDataInner struct {

	// Description of the CPU flag.
	Description string `json:"description"`

	// Name of the CPU flag.
	Name string `json:"name"`

	AdditionalProperties map[string]interface{}
}

type _NodesCapabilitiesGetCpuFlagsResponseDataInner NodesCapabilitiesGetCpuFlagsResponseDataInner

// NewNodesCapabilitiesGetCpuFlagsResponseDataInner instantiates a new NodesCapabilitiesGetCpuFlagsResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesCapabilitiesGetCpuFlagsResponseDataInner(description string, name string) *NodesCapabilitiesGetCpuFlagsResponseDataInner {
	this := NodesCapabilitiesGetCpuFlagsResponseDataInner{}
	this.Description = description
	this.Name = name
	return &this
}

// NewNodesCapabilitiesGetCpuFlagsResponseDataInnerWithDefaults instantiates a new NodesCapabilitiesGetCpuFlagsResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesCapabilitiesGetCpuFlagsResponseDataInnerWithDefaults() *NodesCapabilitiesGetCpuFlagsResponseDataInner {
	this := NodesCapabilitiesGetCpuFlagsResponseDataInner{}



	return &this
}


// GetDescription returns the Description field value
func (o *NodesCapabilitiesGetCpuFlagsResponseDataInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *NodesCapabilitiesGetCpuFlagsResponseDataInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *NodesCapabilitiesGetCpuFlagsResponseDataInner) SetDescription(v string) {
	o.Description = v
}


// GetName returns the Name field value
func (o *NodesCapabilitiesGetCpuFlagsResponseDataInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NodesCapabilitiesGetCpuFlagsResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NodesCapabilitiesGetCpuFlagsResponseDataInner) SetName(v string) {
	o.Name = v
}


func (o NodesCapabilitiesGetCpuFlagsResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesCapabilitiesGetCpuFlagsResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["description"] = o.Description
	
	toSerialize["name"] = o.Name
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesCapabilitiesGetCpuFlagsResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesCapabilitiesGetCpuFlagsResponseDataInner := _NodesCapabilitiesGetCpuFlagsResponseDataInner{}

	err = json.Unmarshal(data, &varNodesCapabilitiesGetCpuFlagsResponseDataInner)

	if err != nil {
		return err
	}

	*o = NodesCapabilitiesGetCpuFlagsResponseDataInner(varNodesCapabilitiesGetCpuFlagsResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesCapabilitiesGetCpuFlagsResponseDataInner struct {
	value *NodesCapabilitiesGetCpuFlagsResponseDataInner
	isSet bool
}

func (v NullableNodesCapabilitiesGetCpuFlagsResponseDataInner) Get() *NodesCapabilitiesGetCpuFlagsResponseDataInner {
	return v.value
}

func (v *NullableNodesCapabilitiesGetCpuFlagsResponseDataInner) Set(val *NodesCapabilitiesGetCpuFlagsResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesCapabilitiesGetCpuFlagsResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesCapabilitiesGetCpuFlagsResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesCapabilitiesGetCpuFlagsResponseDataInner(val *NodesCapabilitiesGetCpuFlagsResponseDataInner) *NullableNodesCapabilitiesGetCpuFlagsResponseDataInner {
	return &NullableNodesCapabilitiesGetCpuFlagsResponseDataInner{value: val, isSet: true}
}

func (v NullableNodesCapabilitiesGetCpuFlagsResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesCapabilitiesGetCpuFlagsResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


