/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccessAclReadAclResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessAclReadAclResponseDataInner{}

// AccessAclReadAclResponseDataInner struct for AccessAclReadAclResponseDataInner
type AccessAclReadAclResponseDataInner struct {

	// Access control path
	Path string `json:"path"`

	// Allow to propagate (inherit) permissions.
	Propagate *PveBoolean `json:"propagate,omitempty"`

	Roleid string `json:"roleid"`

	Type PveAccessAclTypeEnum `json:"type"`

	Ugid string `json:"ugid"`

}

type _AccessAclReadAclResponseDataInner AccessAclReadAclResponseDataInner

// NewAccessAclReadAclResponseDataInner instantiates a new AccessAclReadAclResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessAclReadAclResponseDataInner(path string, roleid string, type_ PveAccessAclTypeEnum, ugid string) *AccessAclReadAclResponseDataInner {
	this := AccessAclReadAclResponseDataInner{}
	this.Path = path
	var propagate PveBoolean = PVEBOOLEAN__1
	this.Propagate = &propagate
	this.Roleid = roleid
	this.Type = type_
	this.Ugid = ugid
	return &this
}

// NewAccessAclReadAclResponseDataInnerWithDefaults instantiates a new AccessAclReadAclResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessAclReadAclResponseDataInnerWithDefaults() *AccessAclReadAclResponseDataInner {
	this := AccessAclReadAclResponseDataInner{}


	var propagate PveBoolean = PVEBOOLEAN__1
	this.Propagate = &propagate




	return &this
}


// GetPath returns the Path field value
func (o *AccessAclReadAclResponseDataInner) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *AccessAclReadAclResponseDataInner) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *AccessAclReadAclResponseDataInner) SetPath(v string) {
	o.Path = v
}


// GetPropagate returns the Propagate field value if set, zero value otherwise.
func (o *AccessAclReadAclResponseDataInner) GetPropagate() PveBoolean {
	if o == nil || IsNil(o.Propagate) {
		var ret PveBoolean
		return ret
	}
	return *o.Propagate
}

// GetPropagateOk returns a tuple with the Propagate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessAclReadAclResponseDataInner) GetPropagateOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Propagate) {
		return nil, false
	}
	return o.Propagate, true
}

// HasPropagate returns a boolean if a field has been set.
func (o *AccessAclReadAclResponseDataInner) HasPropagate() bool {
	if o != nil && !IsNil(o.Propagate) {
		return true
	}

	return false
}

// SetPropagate gets a reference to the given PveBoolean and assigns it to the Propagate field.
func (o *AccessAclReadAclResponseDataInner) SetPropagate(v PveBoolean) {
	o.Propagate = &v
}


// GetRoleid returns the Roleid field value
func (o *AccessAclReadAclResponseDataInner) GetRoleid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Roleid
}

// GetRoleidOk returns a tuple with the Roleid field value
// and a boolean to check if the value has been set.
func (o *AccessAclReadAclResponseDataInner) GetRoleidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Roleid, true
}

// SetRoleid sets field value
func (o *AccessAclReadAclResponseDataInner) SetRoleid(v string) {
	o.Roleid = v
}


// GetType returns the Type field value
func (o *AccessAclReadAclResponseDataInner) GetType() PveAccessAclTypeEnum {
	if o == nil {
		var ret PveAccessAclTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AccessAclReadAclResponseDataInner) GetTypeOk() (*PveAccessAclTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AccessAclReadAclResponseDataInner) SetType(v PveAccessAclTypeEnum) {
	o.Type = v
}


// GetUgid returns the Ugid field value
func (o *AccessAclReadAclResponseDataInner) GetUgid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ugid
}

// GetUgidOk returns a tuple with the Ugid field value
// and a boolean to check if the value has been set.
func (o *AccessAclReadAclResponseDataInner) GetUgidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ugid, true
}

// SetUgid sets field value
func (o *AccessAclReadAclResponseDataInner) SetUgid(v string) {
	o.Ugid = v
}


func (o AccessAclReadAclResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessAclReadAclResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["path"] = o.Path
	
	if !IsNil(o.Propagate) {
		toSerialize["propagate"] = o.Propagate
	}
	
	toSerialize["roleid"] = o.Roleid
	
	toSerialize["type"] = o.Type
	
	toSerialize["ugid"] = o.Ugid
	
	return toSerialize, nil
}

func (o *AccessAclReadAclResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
		"roleid",
		"type",
		"ugid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessAclReadAclResponseDataInner := _AccessAclReadAclResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccessAclReadAclResponseDataInner)

	if err != nil {
		return err
	}

	*o = AccessAclReadAclResponseDataInner(varAccessAclReadAclResponseDataInner)

	return err
}

type NullableAccessAclReadAclResponseDataInner struct {
	value *AccessAclReadAclResponseDataInner
	isSet bool
}

func (v NullableAccessAclReadAclResponseDataInner) Get() *AccessAclReadAclResponseDataInner {
	return v.value
}

func (v *NullableAccessAclReadAclResponseDataInner) Set(val *AccessAclReadAclResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessAclReadAclResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessAclReadAclResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessAclReadAclResponseDataInner(val *AccessAclReadAclResponseDataInner) *NullableAccessAclReadAclResponseDataInner {
	return &NullableAccessAclReadAclResponseDataInner{value: val, isSet: true}
}

func (v NullableAccessAclReadAclResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessAclReadAclResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


