/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NodesDisksInitgptRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesDisksInitgptRequest{}

// NodesDisksInitgptRequest struct for NodesDisksInitgptRequest
type NodesDisksInitgptRequest struct {

	// Block device name
	Disk string `json:"disk" validate:"regexp=^\\/dev\\/[a-zA-Z0-9\\/]+$"`

	// UUID for the GPT table
	Uuid *string `json:"uuid,omitempty" validate:"regexp=[a-fA-F0-9\\\\-]+"`

}

type _NodesDisksInitgptRequest NodesDisksInitgptRequest

// NewNodesDisksInitgptRequest instantiates a new NodesDisksInitgptRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesDisksInitgptRequest(disk string) *NodesDisksInitgptRequest {
	this := NodesDisksInitgptRequest{}
	this.Disk = disk
	return &this
}

// NewNodesDisksInitgptRequestWithDefaults instantiates a new NodesDisksInitgptRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesDisksInitgptRequestWithDefaults() *NodesDisksInitgptRequest {
	this := NodesDisksInitgptRequest{}



	return &this
}


// GetDisk returns the Disk field value
func (o *NodesDisksInitgptRequest) GetDisk() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Disk
}

// GetDiskOk returns a tuple with the Disk field value
// and a boolean to check if the value has been set.
func (o *NodesDisksInitgptRequest) GetDiskOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disk, true
}

// SetDisk sets field value
func (o *NodesDisksInitgptRequest) SetDisk(v string) {
	o.Disk = v
}


// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *NodesDisksInitgptRequest) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesDisksInitgptRequest) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *NodesDisksInitgptRequest) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *NodesDisksInitgptRequest) SetUuid(v string) {
	o.Uuid = &v
}


func (o NodesDisksInitgptRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesDisksInitgptRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["disk"] = o.Disk
	
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	
	return toSerialize, nil
}

func (o *NodesDisksInitgptRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"disk",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesDisksInitgptRequest := _NodesDisksInitgptRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNodesDisksInitgptRequest)

	if err != nil {
		return err
	}

	*o = NodesDisksInitgptRequest(varNodesDisksInitgptRequest)

	return err
}

type NullableNodesDisksInitgptRequest struct {
	value *NodesDisksInitgptRequest
	isSet bool
}

func (v NullableNodesDisksInitgptRequest) Get() *NodesDisksInitgptRequest {
	return v.value
}

func (v *NullableNodesDisksInitgptRequest) Set(val *NodesDisksInitgptRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesDisksInitgptRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesDisksInitgptRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesDisksInitgptRequest(val *NodesDisksInitgptRequest) *NullableNodesDisksInitgptRequest {
	return &NullableNodesDisksInitgptRequest{value: val, isSet: true}
}

func (v NullableNodesDisksInitgptRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesDisksInitgptRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


