/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NodesStorageUpdateattributesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesStorageUpdateattributesRequest{}

// NodesStorageUpdateattributesRequest struct for NodesStorageUpdateattributesRequest
type NodesStorageUpdateattributesRequest struct {

	// The new notes.
	Notes *string `json:"notes,omitempty"`

	// Protection status. Currently only supported for backups.
	Protected *PveBoolean `json:"protected,omitempty"`

}

// NewNodesStorageUpdateattributesRequest instantiates a new NodesStorageUpdateattributesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesStorageUpdateattributesRequest() *NodesStorageUpdateattributesRequest {
	this := NodesStorageUpdateattributesRequest{}
	return &this
}

// NewNodesStorageUpdateattributesRequestWithDefaults instantiates a new NodesStorageUpdateattributesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesStorageUpdateattributesRequestWithDefaults() *NodesStorageUpdateattributesRequest {
	this := NodesStorageUpdateattributesRequest{}



	return &this
}


// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *NodesStorageUpdateattributesRequest) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesStorageUpdateattributesRequest) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *NodesStorageUpdateattributesRequest) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *NodesStorageUpdateattributesRequest) SetNotes(v string) {
	o.Notes = &v
}


// GetProtected returns the Protected field value if set, zero value otherwise.
func (o *NodesStorageUpdateattributesRequest) GetProtected() PveBoolean {
	if o == nil || IsNil(o.Protected) {
		var ret PveBoolean
		return ret
	}
	return *o.Protected
}

// GetProtectedOk returns a tuple with the Protected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesStorageUpdateattributesRequest) GetProtectedOk() (*PveBoolean, bool) {
	if o == nil || IsNil(o.Protected) {
		return nil, false
	}
	return o.Protected, true
}

// HasProtected returns a boolean if a field has been set.
func (o *NodesStorageUpdateattributesRequest) HasProtected() bool {
	if o != nil && !IsNil(o.Protected) {
		return true
	}

	return false
}

// SetProtected gets a reference to the given PveBoolean and assigns it to the Protected field.
func (o *NodesStorageUpdateattributesRequest) SetProtected(v PveBoolean) {
	o.Protected = &v
}


func (o NodesStorageUpdateattributesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesStorageUpdateattributesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	
	if !IsNil(o.Protected) {
		toSerialize["protected"] = o.Protected
	}
	
	return toSerialize, nil
}

type NullableNodesStorageUpdateattributesRequest struct {
	value *NodesStorageUpdateattributesRequest
	isSet bool
}

func (v NullableNodesStorageUpdateattributesRequest) Get() *NodesStorageUpdateattributesRequest {
	return v.value
}

func (v *NullableNodesStorageUpdateattributesRequest) Set(val *NodesStorageUpdateattributesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesStorageUpdateattributesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesStorageUpdateattributesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesStorageUpdateattributesRequest(val *NodesStorageUpdateattributesRequest) *NullableNodesStorageUpdateattributesRequest {
	return &NullableNodesStorageUpdateattributesRequest{value: val, isSet: true}
}

func (v NullableNodesStorageUpdateattributesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesStorageUpdateattributesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


