/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClusterSdnCreateDnsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterSdnCreateDnsRequest{}

// ClusterSdnCreateDnsRequest struct for ClusterSdnCreateDnsRequest
type ClusterSdnCreateDnsRequest struct {

	// The SDN dns object identifier.
	Dns string `json:"dns" validate:"regexp=[a-zA-Z][a-zA-Z0-9]*[a-zA-Z0-9]"`

	// Certificate SHA 256 fingerprint.
	Fingerprint *string `json:"fingerprint,omitempty" validate:"regexp=([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}"`

	Key string `json:"key"`

	// the token for unlocking the global SDN configuration
	LockToken *string `json:"lock-token,omitempty"`

	Reversemaskv6 *int64 `json:"reversemaskv6,omitempty"`

	Reversev6mask *int64 `json:"reversev6mask,omitempty"`

	Ttl *int64 `json:"ttl,omitempty"`

	// Plugin type.
	Type PveClusterSdnTypeTypeEnum `json:"type"`

	Url string `json:"url"`

}

type _ClusterSdnCreateDnsRequest ClusterSdnCreateDnsRequest

// NewClusterSdnCreateDnsRequest instantiates a new ClusterSdnCreateDnsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterSdnCreateDnsRequest(dns string, key string, type_ PveClusterSdnTypeTypeEnum, url string) *ClusterSdnCreateDnsRequest {
	this := ClusterSdnCreateDnsRequest{}
	this.Dns = dns
	this.Key = key
	this.Type = type_
	this.Url = url
	return &this
}

// NewClusterSdnCreateDnsRequestWithDefaults instantiates a new ClusterSdnCreateDnsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterSdnCreateDnsRequestWithDefaults() *ClusterSdnCreateDnsRequest {
	this := ClusterSdnCreateDnsRequest{}










	return &this
}


// GetDns returns the Dns field value
func (o *ClusterSdnCreateDnsRequest) GetDns() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dns
}

// GetDnsOk returns a tuple with the Dns field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnCreateDnsRequest) GetDnsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dns, true
}

// SetDns sets field value
func (o *ClusterSdnCreateDnsRequest) SetDns(v string) {
	o.Dns = v
}


// GetFingerprint returns the Fingerprint field value if set, zero value otherwise.
func (o *ClusterSdnCreateDnsRequest) GetFingerprint() string {
	if o == nil || IsNil(o.Fingerprint) {
		var ret string
		return ret
	}
	return *o.Fingerprint
}

// GetFingerprintOk returns a tuple with the Fingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnCreateDnsRequest) GetFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.Fingerprint) {
		return nil, false
	}
	return o.Fingerprint, true
}

// HasFingerprint returns a boolean if a field has been set.
func (o *ClusterSdnCreateDnsRequest) HasFingerprint() bool {
	if o != nil && !IsNil(o.Fingerprint) {
		return true
	}

	return false
}

// SetFingerprint gets a reference to the given string and assigns it to the Fingerprint field.
func (o *ClusterSdnCreateDnsRequest) SetFingerprint(v string) {
	o.Fingerprint = &v
}


// GetKey returns the Key field value
func (o *ClusterSdnCreateDnsRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnCreateDnsRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ClusterSdnCreateDnsRequest) SetKey(v string) {
	o.Key = v
}


// GetLockToken returns the LockToken field value if set, zero value otherwise.
func (o *ClusterSdnCreateDnsRequest) GetLockToken() string {
	if o == nil || IsNil(o.LockToken) {
		var ret string
		return ret
	}
	return *o.LockToken
}

// GetLockTokenOk returns a tuple with the LockToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnCreateDnsRequest) GetLockTokenOk() (*string, bool) {
	if o == nil || IsNil(o.LockToken) {
		return nil, false
	}
	return o.LockToken, true
}

// HasLockToken returns a boolean if a field has been set.
func (o *ClusterSdnCreateDnsRequest) HasLockToken() bool {
	if o != nil && !IsNil(o.LockToken) {
		return true
	}

	return false
}

// SetLockToken gets a reference to the given string and assigns it to the LockToken field.
func (o *ClusterSdnCreateDnsRequest) SetLockToken(v string) {
	o.LockToken = &v
}


// GetReversemaskv6 returns the Reversemaskv6 field value if set, zero value otherwise.
func (o *ClusterSdnCreateDnsRequest) GetReversemaskv6() int64 {
	if o == nil || IsNil(o.Reversemaskv6) {
		var ret int64
		return ret
	}
	return *o.Reversemaskv6
}

// GetReversemaskv6Ok returns a tuple with the Reversemaskv6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnCreateDnsRequest) GetReversemaskv6Ok() (*int64, bool) {
	if o == nil || IsNil(o.Reversemaskv6) {
		return nil, false
	}
	return o.Reversemaskv6, true
}

// HasReversemaskv6 returns a boolean if a field has been set.
func (o *ClusterSdnCreateDnsRequest) HasReversemaskv6() bool {
	if o != nil && !IsNil(o.Reversemaskv6) {
		return true
	}

	return false
}

// SetReversemaskv6 gets a reference to the given int64 and assigns it to the Reversemaskv6 field.
func (o *ClusterSdnCreateDnsRequest) SetReversemaskv6(v int64) {
	o.Reversemaskv6 = &v
}


// GetReversev6mask returns the Reversev6mask field value if set, zero value otherwise.
func (o *ClusterSdnCreateDnsRequest) GetReversev6mask() int64 {
	if o == nil || IsNil(o.Reversev6mask) {
		var ret int64
		return ret
	}
	return *o.Reversev6mask
}

// GetReversev6maskOk returns a tuple with the Reversev6mask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnCreateDnsRequest) GetReversev6maskOk() (*int64, bool) {
	if o == nil || IsNil(o.Reversev6mask) {
		return nil, false
	}
	return o.Reversev6mask, true
}

// HasReversev6mask returns a boolean if a field has been set.
func (o *ClusterSdnCreateDnsRequest) HasReversev6mask() bool {
	if o != nil && !IsNil(o.Reversev6mask) {
		return true
	}

	return false
}

// SetReversev6mask gets a reference to the given int64 and assigns it to the Reversev6mask field.
func (o *ClusterSdnCreateDnsRequest) SetReversev6mask(v int64) {
	o.Reversev6mask = &v
}


// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *ClusterSdnCreateDnsRequest) GetTtl() int64 {
	if o == nil || IsNil(o.Ttl) {
		var ret int64
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterSdnCreateDnsRequest) GetTtlOk() (*int64, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *ClusterSdnCreateDnsRequest) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int64 and assigns it to the Ttl field.
func (o *ClusterSdnCreateDnsRequest) SetTtl(v int64) {
	o.Ttl = &v
}


// GetType returns the Type field value
func (o *ClusterSdnCreateDnsRequest) GetType() PveClusterSdnTypeTypeEnum {
	if o == nil {
		var ret PveClusterSdnTypeTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnCreateDnsRequest) GetTypeOk() (*PveClusterSdnTypeTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ClusterSdnCreateDnsRequest) SetType(v PveClusterSdnTypeTypeEnum) {
	o.Type = v
}


// GetUrl returns the Url field value
func (o *ClusterSdnCreateDnsRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ClusterSdnCreateDnsRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ClusterSdnCreateDnsRequest) SetUrl(v string) {
	o.Url = v
}


func (o ClusterSdnCreateDnsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterSdnCreateDnsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["dns"] = o.Dns
	
	if !IsNil(o.Fingerprint) {
		toSerialize["fingerprint"] = o.Fingerprint
	}
	
	toSerialize["key"] = o.Key
	
	if !IsNil(o.LockToken) {
		toSerialize["lock-token"] = o.LockToken
	}
	
	if !IsNil(o.Reversemaskv6) {
		toSerialize["reversemaskv6"] = o.Reversemaskv6
	}
	
	if !IsNil(o.Reversev6mask) {
		toSerialize["reversev6mask"] = o.Reversev6mask
	}
	
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	
	toSerialize["type"] = o.Type
	
	toSerialize["url"] = o.Url
	
	return toSerialize, nil
}

func (o *ClusterSdnCreateDnsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dns",
		"key",
		"type",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterSdnCreateDnsRequest := _ClusterSdnCreateDnsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterSdnCreateDnsRequest)

	if err != nil {
		return err
	}

	*o = ClusterSdnCreateDnsRequest(varClusterSdnCreateDnsRequest)

	return err
}

type NullableClusterSdnCreateDnsRequest struct {
	value *ClusterSdnCreateDnsRequest
	isSet bool
}

func (v NullableClusterSdnCreateDnsRequest) Get() *ClusterSdnCreateDnsRequest {
	return v.value
}

func (v *NullableClusterSdnCreateDnsRequest) Set(val *ClusterSdnCreateDnsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterSdnCreateDnsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterSdnCreateDnsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterSdnCreateDnsRequest(val *ClusterSdnCreateDnsRequest) *NullableClusterSdnCreateDnsRequest {
	return &NullableClusterSdnCreateDnsRequest{value: val, isSet: true}
}

func (v NullableClusterSdnCreateDnsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterSdnCreateDnsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


