/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PveQemuFormatEnum the model 'PveQemuFormatEnum'
type PveQemuFormatEnum string

// List of PveQemuFormatEnum
const (
	PVEQEMUFORMATENUM_RAW PveQemuFormatEnum = "raw"
	PVEQEMUFORMATENUM_QCOW2 PveQemuFormatEnum = "qcow2"
	PVEQEMUFORMATENUM_VMDK PveQemuFormatEnum = "vmdk"
)

// All allowed values of PveQemuFormatEnum enum
var AllowedPveQemuFormatEnumEnumValues = []PveQemuFormatEnum{
	"raw",
	"qcow2",
	"vmdk",
}

func (v *PveQemuFormatEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PveQemuFormatEnum(value)
	for _, existing := range AllowedPveQemuFormatEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PveQemuFormatEnum", value)
}

// NewPveQemuFormatEnumFromValue returns a pointer to a valid PveQemuFormatEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPveQemuFormatEnumFromValue(v string) (*PveQemuFormatEnum, error) {
	ev := PveQemuFormatEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PveQemuFormatEnum: valid values are %v", v, AllowedPveQemuFormatEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PveQemuFormatEnum) IsValid() bool {
	for _, existing := range AllowedPveQemuFormatEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PveQemuFormatEnum value
func (v PveQemuFormatEnum) Ptr() *PveQemuFormatEnum {
	return &v
}

type NullablePveQemuFormatEnum struct {
	value *PveQemuFormatEnum
	isSet bool
}

func (v NullablePveQemuFormatEnum) Get() *PveQemuFormatEnum {
	return v.value
}

func (v *NullablePveQemuFormatEnum) Set(val *PveQemuFormatEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePveQemuFormatEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePveQemuFormatEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePveQemuFormatEnum(val *PveQemuFormatEnum) *NullablePveQemuFormatEnum {
	return &NullablePveQemuFormatEnum{value: val, isSet: true}
}

func (v NullablePveQemuFormatEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePveQemuFormatEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

