/*
Proxmox Virtual Environment API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

API version: 8.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pveclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterHaGetGroupsResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterHaGetGroupsResponseDataInner{}

// ClusterHaGetGroupsResponseDataInner struct for ClusterHaGetGroupsResponseDataInner
type ClusterHaGetGroupsResponseDataInner struct {

	Group string `json:"group"`

	AdditionalProperties map[string]interface{}
}

type _ClusterHaGetGroupsResponseDataInner ClusterHaGetGroupsResponseDataInner

// NewClusterHaGetGroupsResponseDataInner instantiates a new ClusterHaGetGroupsResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterHaGetGroupsResponseDataInner(group string) *ClusterHaGetGroupsResponseDataInner {
	this := ClusterHaGetGroupsResponseDataInner{}
	this.Group = group
	return &this
}

// NewClusterHaGetGroupsResponseDataInnerWithDefaults instantiates a new ClusterHaGetGroupsResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterHaGetGroupsResponseDataInnerWithDefaults() *ClusterHaGetGroupsResponseDataInner {
	this := ClusterHaGetGroupsResponseDataInner{}


	return &this
}


// GetGroup returns the Group field value
func (o *ClusterHaGetGroupsResponseDataInner) GetGroup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *ClusterHaGetGroupsResponseDataInner) GetGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *ClusterHaGetGroupsResponseDataInner) SetGroup(v string) {
	o.Group = v
}


func (o ClusterHaGetGroupsResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterHaGetGroupsResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["group"] = o.Group
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterHaGetGroupsResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"group",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterHaGetGroupsResponseDataInner := _ClusterHaGetGroupsResponseDataInner{}

	err = json.Unmarshal(data, &varClusterHaGetGroupsResponseDataInner)

	if err != nil {
		return err
	}

	*o = ClusterHaGetGroupsResponseDataInner(varClusterHaGetGroupsResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "group")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterHaGetGroupsResponseDataInner struct {
	value *ClusterHaGetGroupsResponseDataInner
	isSet bool
}

func (v NullableClusterHaGetGroupsResponseDataInner) Get() *ClusterHaGetGroupsResponseDataInner {
	return v.value
}

func (v *NullableClusterHaGetGroupsResponseDataInner) Set(val *ClusterHaGetGroupsResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterHaGetGroupsResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterHaGetGroupsResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterHaGetGroupsResponseDataInner(val *ClusterHaGetGroupsResponseDataInner) *NullableClusterHaGetGroupsResponseDataInner {
	return &NullableClusterHaGetGroupsResponseDataInner{value: val, isSet: true}
}

func (v NullableClusterHaGetGroupsResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterHaGetGroupsResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


